### ISSUE TITLE
[Welcome to Foundation 6] No Share on Twitter button

### ISSUE THREAD

**Issue by digitalgnome** [foundation/foundation-sites#10037]
#### How to reproduce this bug:

1. Go to [http://foundation.zurb.com/sites/docs/](http://foundation.zurb.com/sites/docs/)
2. Locate Github Star button
3. According to Raffi in the Introduction to the docs video there should be a Share on Twitter button

#### What should happen:
See a Share on Twitter button
#### What happened instead:
No visible Share on Twitter button
#### Browser(s) and Device(s) tested on:
Google Chrome
Mozilla Firefox
#### Test case link:

- [CodePen with Foundation 6.3.0 and MotionUI](http://codepen.io/IamManchanda/pen/vgemXR)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/xgXdRq)

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

**Comment by kball** [comment]
This was removed in a later design iteration... @rafibomb can you take on updating that section of the video?

**Comment by DanielRuf** [comment]
Bump. So we do not need a Twitter share button? Was it only a design decision or due to other problems with the integration?

**Comment by DanielRuf** [comment]
Can we update video?

**Comment by DanielRuf** [comment]
Closing as updating the video might not be possible anymore and we might leave it like it is.
