### ISSUE TITLE
[6.3.1][Sticky] Sticky navigation does not stick in iOS Safari for iPhone

### ISSUE THREAD

**Issue by Yanchek99** [foundation/foundation-sites#10169]
#### How to reproduce this bug:

1. Must either view pen on an iPhone Safari browser or using macOS Safari in Responsive Design Mode set to any of the iPhone models.
2. Execute code pen or documentation and note that the sticky navigation is no longer sticky.
3. Works as expected for tablets and desktops

Can also reproduce against the documentation http://foundation.zurb.com/sites/docs/sticky.html#sticky-navigation

#### What should happen:
Navigation should be sticky no matter the screen size

#### What happened instead:
Navigation was not sticky in iPhone browser

#### Browser(s) and Device(s) tested on:
Safari - iPhone 7
Safari - iMac Desktop
Safari - iPad

#### Foundation Version(s) you are using:
6.3.1 Flex 

#### Test case link:
https://codepen.io/anon/pen/MoyvZW

**Comment by IamManchanda** [comment]
Hmmn... can confirm :)

**Comment by IamManchanda** [comment]
@Yanchek99 Off late you have been helping us really out with flex bugs 
Would be great if you have some feedback/bug report for our upcoming new grid (flex) - XY Grid
http://foundation.zurb.com/sites/6.4.0-rc/docs/xy-grid.html

You can create the pen from these cdn files in here https://cdnjs.com/libraries/foundation/6.4.0-rc3

**Comment by Yanchek99** [comment]
@IamManchanda Cool I will have to check it out.  Right now I am getting foundation from https://github.com/zurb/foundation-rails so I'll have to suggest a branch for the 6.4.0 changes

**Comment by matthewandrianakos** [comment]
Is there an update on this?

**Comment by andycochran** [comment]
Can anyone confirm if this is still an issue in 6.4.3?

**Comment by DanielRuf** [comment]
Still an issue in 6.5.3.

**Comment by DanielRuf** [comment]
Also this is not a browser bug as it also happens on Firefox.

**Comment by anik786** [comment]
Any update?

**Comment by joeworkman** [comment]
The demo page does indeed not work on iOS. However, only when it's displayed inside of an iframe. If you go directly to that demo it works. https://get.foundation/sites/docs/assets/partials/sticky-nav.html
