### ISSUE TITLE
ResponsiveAccrodionTabs plugin doesn't init correctly

### ISSUE THREAD

**Issue by Lazerproof** [foundation/foundation-sites#10181]
I want to use responsiveAccordionTabs with custom classes and initialize it programmatically.
Here is a pen [https://codepen.io/Lazerproof/pen/GEqLyW](url)

As you can see tabs are not initialized correctly on page load, but if you resize the window to smaller than 1024px (large breakpoint in my case ), tabs change to accordion and work as expected. Then resize back to larger that 1024px and tabs will work correctly.

I have been trying to debug this issue, but with no luck.

**Comment by kball** [comment]
@IamManchanda here's another good javascript issue to tackle

**Comment by IamManchanda** [comment]
Will look into it ... cool!
