### ISSUE TITLE
Range slider triggers change event on load

### ISSUE THREAD

**Issue by januszm** [foundation/foundation-sites#10315]
This is essentially very similar to issue https://github.com/zurb/foundation-sites/issues/6606 with Foundation 5 label. And it's mentioned in this thread: http://foundation.zurb.com/forum/posts/48357-how-to-disable-a-range-sliders--initital-movement . It seems like undesirable behaviour. `changed.zf.slider` and `moved.zf.slider` events should be emitted on actual user interaction, not on page load.

#### How to reproduce this bug:

1. Set event listener to 'changed.zf.slider' somewhere in your code.
```javascript
$(document).on('changed.zf.slider', function() {
  // do something, like ajax request
}
```
2. Set initial values for the slider with `data-initial-start`
3. Reload/Load the page
4. Slider handle will move to initial position
5. Event handler will be called, which is undesirable, because the slider wasn't changed by user (or script).

#### What should happen:
`changed.zf.slider` or `moved.zf.slider` events should not be emitted when page loads and slider has data-initial-start attribute set. It is not user/script interaction.

#### What happened instead:
`changed.zf.slider` and `moved.zf.slider` events are emitted.

#### Browser(s) and Device(s) tested on:
Chrome, Mac OS X

#### Foundation Version(s) you are using:
6.3

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.slider.js#L298
https://codepen.io/DanielRuf/pen/xWQZZO

Not sure if the issue describes a bug.
Should we make this optin as new option @ncoden?

**Comment by ncoden** [comment]
> changed.zf.slider and moved.zf.slider events should be emitted on actual user interaction, not on page load

@januszm You are right. This should be considered as a bug.

> Should we make this optin as new option

@DanielRuf Events are the same for all users. We can have multiple events around the same "action" (like before and after it is done) or the same event in various cases (like after a value is initialized/resolved/changes and we need to share it), but all events are always triggered.

In this case, there is no "data" to share at initialization, nothing new, nothing happened, so no event should be emited, and even if new datas were resolved we should not use `changed` for that as it is generally reserved for user interactions.

**Comment by yueruchi** [comment]
Is this "bug" fixed already?. I still struggle with this issue.

**Comment by yueruchi** [comment]
I tried binding change and input event in `input[type="number"]` but the event doesn't fire even after the range modified the input.

**Comment by DanielRuf** [comment]
> Is this "bug" fixed already?. I still struggle with this issue.

Not that I knew.

> I tried binding change and input event in input[type="number"] but the event doesn't fire even after the range modified the input.

Can you provide a codepen?

**Comment by DanielRuf** [comment]
Closing as we did not receive any further information.

**Comment by januszm** [comment]
If nothing has changed, i.e. it still behaves in the same way, then it is not good. Or maybe this code was improved in the new Foundation release (if any)?

**Comment by DanielRuf** [comment]
> If nothing has changed, i.e. it still behaves in the same way, then it is not good. Or maybe this code was improved in the new Foundation release (if any)?

Can you open a new issue and provide all relevant details with all details?

**Comment by januszm** [comment]
All the details are in this issue (see: "How to reproduce this bug", "What should happen", "What happened instead.").

I cannot provide more information at the moment, I'm not even actively using Foundation right now (issue is 2 years old).

**Comment by rickcurran** [comment]
Yep, just to confirm that the 'changed' event is still triggered on page load. It would be nice if there was a way to prevent this as it's quite hard to work around.

**Comment by DanielRuf** [comment]
> Yep, just to confirm that the 'changed' event is still triggered on page load. It would be nice if there was a way to prevent this as it's quite hard to work around.

Did you test Foundation Sites 6.5.3?

**Comment by DanielRuf** [comment]
If it is still happening in 6.5.3 please update the issue description, ping me and I'll reopen it.

**Comment by rickcurran** [comment]
@DanielRuf Yep, I've updated to 6.5.3 (I had 6.5.1 on this particular site I'm working on) and the 'changed' event definitely gets called on page load which contains a slider. However, in my testing just now unlike the original issue above I didn't see the 'moved' event get called, but I had thought I'd seen that get all on page load as well. I'm not sure whether this is something that going from 6.5.1 to 6.5.3 would have changed?

**Comment by omejelle** [comment]
can this be re-opened? the bug still exists
