### ISSUE TITLE
Foundation 6.4.1 custom build - number of grid columns is ignored 

### ISSUE THREAD

**Issue by saress** [foundation/foundation-sites#10386]
#### How to reproduce this bug:

1. Step one

Visit: http://foundation.zurb.com/sites/download.html/

2. Step two

Choose "Custom Build" and add another number to "The Grid # of columns" f.ex. "24"

3. Step three

Click "Download custom build"

#### What should happen:

The downloaded CSS-Files should have 24 columns for the grid

#### What happened instead:

They support only 12 columns instead

#### Browser(s) and Device(s) tested on:

Chrome latest, FF latest, Win10

#### Foundation Version(s) you are using:

6.4.1

**Comment by radoshordos** [comment]
Yes, I have same problem. Always 12 column...

**Comment by kball** [comment]
Pushed an update in the customizer repo, @rafibomb please deploy when you get a chance

**Comment by DanielRuf** [comment]
The current customizer uses the right column settings. At least I can see small-24, small-23 and so on. So I guess this is already resolved?

**Comment by DanielRuf** [comment]
> The current customizer uses the right column settings. At least I can see small-24, small-23 and so on. So I guess this is already resolved?

@colin-marshall do you see the same or can you still reproduce the initial issue?

**Comment by DanielRuf** [comment]
cc @ncoden @SassNinja @JeremyEnglert

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
