### ISSUE TITLE
changed.zf.mediaquery not triggered anymore

### ISSUE THREAD

**Issue by DanielRuf** [foundation/foundation-sites#10402]
#### How to reproduce this bug:

1. add event listener for `changed.zf.mediaquery`
2. destroy and reInit a component on resize

#### What should happen:
The `changed.zf.mediaquery` event should be thrown

#### What happened instead:
It is not thrown.

#### Browser(s) and Device(s) tested on:
Chrome 59 stable on MacOS

#### Foundation Version(s) you are using:
6.4.1

#### Test case link:

```
        $(window).on('changed.zf.mediaquery', function(event, newSize, oldSize) {
		console.log('triggered');
	});

	$(window).on("load resize orientationchange", function() {
		doSomething();
	});

	$(window).on("resize orientationchange", function() {
		$('[data-equalizer]').foundation('_destroy');
		Foundation.reInit($('[data-equalizer]'));
	});
```

**Comment by kball** [comment]
Thanks for the bug report @DanielRuf - you're probably seeing this due to a change in how Foundation is getting setup, though I've tested this is working in a  number of contexts... To help me track down what's happening for you, can you let me know how you are importing and instantiating Foundation on your page?

**Comment by DanielRuf** [comment]
> can you let me know how you are importing and instantiating Foundation on your page?

Foundation is imported with the normal file include and all components are initialized at once using the foundation function.

So far it seems like ` resize orientationchange` and destroying a component produces this behavior. Can you reproduce this?

**Comment by DanielRuf** [comment]
I try to provide a codepen in the next days.

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/XEaYNY?editors=1010 broken
https://codepen.io/DanielRuf/pen/pLrKPW?editors=1010 working

**Comment by DanielRuf** [comment]
I also guess we have to remove some event listeners as not all components remove them on their instances with `.off()`.

![image](https://user-images.githubusercontent.com/827205/37866193-6ecb2208-2f87-11e8-9d89-847bba615252.png)

**Comment by DanielRuf** [comment]
The cause is that the mediaquery check resets `this.current` on each plugin reinitialization.

https://github.com/zurb/foundation-sites/blob/0c4408883205aa8163c0990c2d06fb2e718d132a/js/foundation.equalizer.js#L41

Should be probably in none of the `_init` methods of all plugins.

**Comment by mshahov** [comment]
@DanielRuf when do you expect this to be fixed, it have been more than a year and this event still can't be used.

I am using the es6 approach and if so

`$(window).on('changed.zf.mediaquery', function(event, newSize, oldSize) {
		console.log('triggered');
	});
`

doesn't work

**Comment by DanielRuf** [comment]
> @DanielRuf when do you expect this to be fixed

Hi @mshahov I am currently not actively working on Foundation Sites anymore. Everyone is invited to provide a PR.

**Comment by joeworkman** [comment]
The `changed.zf.mediaquery` event relies on the `resize.zf.mediaquery` event. However, the `resize.zf.mediaquery` never seems to get triggered anywhere. I could not find if this has ever been triggered. I searched all the way back to 6.0.0 tag.
