### ISSUE TITLE
Update whole menu section's codepen with 6.4 series!

### ISSUE THREAD

**Issue by IamManchanda** [foundation/foundation-sites#10403]
Based on https://github.com/zurb/foundation-sites/pull/9348#issuecomment-314919193
Assigning this to myself 

@kball Can i get a latest template for the same ??

**Comment by IamManchanda** [comment]
Thanks @kball for codepen sample 
( https://codepen.io/IamManchanda/pen/gRqjEV?editors=1000 )

**Comment by IamManchanda** [comment]
Oh gosh i missed this ... 
Notes: Will try to do it tomm :D

**Comment by colin-marshall** [comment]
@IamManchanda does this still need to be done or can we close it out?

**Comment by DanielRuf** [comment]
Still relevant.

https://foundation.zurb.com/sites/docs/menu.html

**Comment by DanielRuf** [comment]
We will move to storybook to make it easier to have uptodate docs.
