### ISSUE TITLE
XY grid - discuss vw units instead of percentages for grid frame

### ISSUE THREAD

**Issue by brgrz** [foundation/foundation-sites#10467]
I'd like to discuss an option to use vw units for grid when used within grid frame because of two reasons:
1) grid frame takes up 100% screen width in most cases (well, that's probably what it was meant for in a web app style interfaces),
2) when using vw units the specified column widths remain the same even when nesting grids, which in the case of grid frame happens a lot. When using percentages two columns placed side by side (but at different nesting levels) have different widths. For instance, first one gets 20% of screen width, second one which we also set at 20% gets 20% of the nested grid's width, which results in narrower column. From developer's perspective this is probably not what he/she wanted when designing the layout (again, in general).

It would make sense to 1) switch to vw units when using .grid-frame class or 2) at least allow developer to turn on vw units via a special class.

What's Foundation's team take on this?

**Comment by IamManchanda** [comment]
cc @kball @brettsmason

**Comment by DanielRuf** [comment]
I guess this only makes sense as a new class to not break nested grids.
