### ISSUE TITLE
Dropdown Menu using Button with dropdown arrows off in Firefox

### ISSUE THREAD

**Issue by bwydev** [foundation/foundation-sites#10476]
RE: Dropdown Menu using Button with dropdown arrows. Foundation 6.4.1

Display error: In Firefox (54.01) dropdown arrow positioning is off.

Temporary fix: On the button element with dropdown arrows (set by `.menu .button { white-space: nowrap; }` ) override with `white-space: normal`;

[CodePen with Foundation 6.4.1](https://codepen.io/bwy/pen/Ljpayj)

**Comment by rafibomb** [comment]
Did some quick browser testing on this, seems to be good to me. 

Can you submit a PR for this so we can merge it in?

**Comment by DanielRuf** [comment]
![image](https://user-images.githubusercontent.com/827205/37372280-78bcade0-2712-11e8-88c3-41d974dca4a8.png)

**Comment by DanielRuf** [comment]
I can not reproduce it in Firefox anymore.
Closing because of this.
