### ISSUE TITLE
[Accordion] Open/Close Event is chaining when option multi-expand is set

### ISSUE THREAD

**Issue by npoggenburg** [foundation/foundation-sites#10486]
Hey guys,
i found a strage behaviour in the accordion component of foundation:
**Open/Close Event is chaining when option multi-expand is set.**

The problem is, that events are chained and beeing fired with a delay on heavily abusing the left click button on an accordion tab. This behaviour is in foundation a long long time, but i wanted to report it now. Multiple users of our websites have reportet this behaviour and i think its a pure improvment on stability and userbility of the component.

#### How to reproduce this bug:

1. Go to http://foundation.zurb.com/sites/docs/accordion.html#advanced-options
2. Click as fast as you can on Tab "Accordion 1"
3. Move cursor away and see the Accordion open/close several times without clicking.

#### What should happen:

Expected behaviour would be, that you click on a tab to open it, all other click events are disabled until the animation is finished. Then you can start the close event for that tab.

#### What happened instead:

All events are chaining and beeing fired late

#### Browser(s) and Device(s) tested on:
Firefox 54.0.x
Chrome 59.0.x

#### Foundation Version(s) you are using:

Foundation 6.4.1

#### Test case link:
http://foundation.zurb.com/sites/docs/accordion.html#advanced-options

**Comment by DanielRuf** [comment]
This is because of missing debouncing and triggering multiple animations.

**Comment by DanielRuf** [comment]
https://github.com/foundation/foundation-sites/blob/develop/js/foundation.accordion.js#L141
https://github.com/foundation/foundation-sites/blob/develop/js/foundation.accordion.js#L176
https://github.com/foundation/foundation-sites/blob/develop/js/foundation.accordion.js#L204
https://github.com/foundation/foundation-sites/blob/develop/js/foundation.accordion.js#L211
https://github.com/foundation/foundation-sites/blob/develop/js/foundation.accordion.js#L277
