### ISSUE TITLE
[Progress Bar] With Text HTML Semantics Incorrect

### ISSUE THREAD

**Issue by joshmedeski** [foundation/foundation-sites#10490]
There is a semantic issue with the [Progress Bar With Text](http://foundation.zurb.com/sites/docs/progress-bar.html#with-text).

A paragraph tag isn't allowed inside a span tag. Block elements (ex: `<p>`) can't be nested inside inline block elements (ex: `<span>`).

The simplest way to fix this is next span tags.

__Example:__
```
<div class="progress" role="progressbar" tabindex="0" aria-valuenow="20" aria-valuemin="0" aria-valuetext="25 percent" aria-valuemax="100">
  <span class="progress-meter" style="width: 25%">
    <span class="progress-meter-text">25%</span>
  </span>
</div>
```

Thoughts?

**Comment by rafibomb** [comment]
Yeah - makes sense to me! We'll merge in a PR on this, thanks Josh!

**Comment by Knight-Yoshi** [comment]
What about using the HTML5 progress bar? Probably would want to remove default system-like styles from it, though.

**Comment by DanielRuf** [comment]
https://foundation.zurb.com/sites/docs/progress-bar.html#native-progress
