### ISSUE TITLE
Non Motion UI classes in Reveal animations break Reveal events

### ISSUE THREAD

**Issue by zacksmash** [foundation/foundation-sites#10527]
I'm using Animate.css to animate my Reveal ins and outs. I'm finding that Foundation doesn't like that, so if it recognizes a class in the `data-animation-out` attribute that it doesn't recognize, the `closed.zf.reveal` event doesn't fire and the body class keeps the `is-reveal-open` class, which breaks the page scrolling.

#### How to reproduce this bug:

1. Create a new modal element
2. Give it a `data-animation-out` attribute, with a  non motion ui class
3. Set up a JS event to fire on `closed.zf.reveal`

#### What should happen:

Events should still fire, if I use a custom class to animate a Reveal modal.

#### What happened instead:

`closes.zf.reveal` does not fire.

#### Browser(s) and Device(s) tested on:

MacBook - Chrome, Safari, Firefox.

#### Foundation Version(s) you are using:

6.4.1

#### Test case link:

https://codepen.io/zacksmash/pen/XagajE

**Comment by rafibomb** [comment]
Just thinking, there must a definition list of classes for the JS somewhere. If that's the case, more definitions could be added.

**Comment by jhafner** [comment]
This issue may be related to this issue: https://github.com/zurb/foundation-sites/issues/10634
