### ISSUE TITLE
[Bug] Interchange not functioning in IE9

### ISSUE THREAD

**Issue by zaclem01** [foundation/foundation-sites#10668]
#### How to reproduce this bug:

1. Include an Interchange component on a page.
2. Open that page in IE9

#### What should happen:

The Interchange should perform the appropriate media query and load the resource with no error.

#### What happened instead:

The Interchange is non-functional and results in the console error:

`TypeError: Object doesn't support property or method 'matchMedia' `

due to IE9 not supporting the matchMedia function.

#### Browser(s) and Device(s) tested on:

Internet Explorer 9 - desktop
Various other browsers to confirm it was functioning as expected otherwise.

#### Foundation Version(s) you are using:

6.4.3

#### Test case link:

Can be seen in Foundations own [docs](http://foundation.zurb.com/sites/docs/interchange.html)

**Comment by zaclem01** [comment]
I should mention, I solved it by adding this [polyfill](https://github.com/paulirish/matchMedia.js/). I'd be happy to submit a PR to the core if needed.

**Comment by DanielRuf** [comment]
As we support IE9+ at the moment, what should we do here? A PR sounds good.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
