### ISSUE TITLE
Sticky 6.4.3 || document.documentElement.scrollHeight in Chrome/Chromium

### ISSUE THREAD

**Issue by h-e-r-b-e-r-t** [foundation/foundation-sites#10666]
FOUNDATION_VERSION = '6.4.3'
Working on a complex sticky menu I run into: Working on FF but not in Chrom[ium].

Reason why is here: _js/foundation.sticky.js: L.93_  _parsePoints => _btm = this.options.btmAnchor== "" ? **document.documentElement.scrollHeight** : this.options.btmAnchor._
In Chrom[ium] **document.documentElement.scrollHeight = 0**. I had to use **document.body.scrollHeight** instead!

[https://stackoverflow.com/questions/20514596/document-documentelement-scrolltop-return-value-differs-in-chrome](https://stackoverflow.com/questions/20514596/document-documentelement-scrolltop-return-value-differs-in-chrome)
 _**Chrome and Safari define their scroll on the <body> element whilst Firefox defines it on the <html> element returned by document.documentElement, for example.**_

In my case **Math.max( document.documentElement.scrollHeight, document.body.scrollHeight )** worked fine but I would suggest to use following:

[https://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript](https://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript)

```
Math.max( 
    document.body.scrollHeight, 
    document.body.offsetHeight, 
    html.clientHeight, 
    document.documentElement.scrollHeight, 
    document.documentElement.offsetHeight
 )
```

or:
[https://j11y.io/snippets/get-document-height-cross-browser](https://j11y.io/snippets/get-document-height-cross-browser)

```
 Math.max( 
    document.body.scrollHeight, 
    document.body.offsetHeight, 
    document.body.clientHeight, 
    document.documentElement.scrollHeight, 
    document.documentElement.offsetHeight,
    document.documentElement.clientHeight
)
```

**Comment by DanielRuf** [comment]
Closing as we did not get a reproducible testcase.
