### ISSUE TITLE
Clicking on menu links error out for Magellan

### ISSUE THREAD

**Issue by alininja** [foundation/foundation-sites#10706]
Hi,

Thank you for making such an amazingly useful library.  :)

I think this is a bug...

#### How to reproduce this bug:
1. Set up magellan
2. Scroll up and down and see that magellan is working
3. Click a link on the menu and notice that the page doesn't scroll to the right place
4. Notice that console shows an error
5. Remove magellan and links work, because of browser's default behavior

#### What should happen:
I expected the page to scroll to the right location, ie the element with the id# that the link is referencing.

#### What happened instead:
Errors out with:
TypeError: r(...)(...).stop is not a function

#### Browser(s) and Device(s) tested on:
Firefox 56.0 (Mac)
Chrome 61.0.3163.100 (Mac)

#### Foundation Version(s) you are using:
6.4.3

#### Test case link:
Here's a weave that shows the error: http://liveweave.com/vAvijJ

Thank you for your help!

**Comment by DanielRuf** [comment]
The provided link does not contain a reproducible testcase (anymore). Closing as invalid.

**Comment by alininja** [comment]
Thanks :)
