### ISSUE TITLE
full-height class for grid-x

### ISSUE THREAD

**Issue by DanielRuf** [foundation/foundation-sites#10766]
In the xy grid docs you set a height for the grid-x. Removing content from it will collapse it.

Currently I am missing a Foundation 6 class which sets the height to 100%.
What I am doing is creating a new class `grid-full-height` to set the height to `100%`.

````
<div class="site">
	<div class="grid-y medium-grid-frame">
                <div class="cell medium-auto medium-cell-block-container">
			<div class="grid-x grid-padding-x grid-full-height">
				<div class="cell medium-2 medium-cell-block-y">
                                ...
````

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/challenge-getting-a-full-height-sidebar/2391/3
