### ISSUE TITLE
XY Grid (vertical) improper alignment

### ISSUE THREAD

**Issue by joshwalsh** [foundation/foundation-sites#10764]
When using align-bottom in a grid-y, it results in align-right.

https://codepen.io/anon/pen/zPBxWr

I'm not sure if you consider align-bottom to be a valid use or not, but it had us perplexed for a while before fixing via other means.

**Comment by mattbag** [comment]
You can add your own classes as I'm sure you know, I would do something like this.
x&y have 2 different behaviour, I'd prefer this than overwriting modifiers based on the grid- class...
For the same principle, you can use align-right on grid-y to push at the bottom... but that feels very confusing indeed.

```
.align-bottom{
  align-items: flex-end
  &-x{align-items: flex-end}
  &-y{justify-content: flex-end}
}
```

**Comment by DanielRuf** [comment]
Closing as this can be solved with own CSS.
