### ISSUE TITLE
add momentum scrolling for components

### ISSUE THREAD

**Issue by DanielRuf** [foundation/foundation-sites#10781]
So far none of the components use `-webkit-overflow-scrolling: touch`. At least for off-canvas and other things.

Because without this we have a very bad scrolling behaviour which abruptly stops when releasing the finger from the screen.

**Comment by kball** [comment]
This seems like it should be relatively straightforward to solve. @DanielRuf do you want to take a pass at a PR?

**Comment by DanielRuf** [comment]
Related: https://github.com/zurb/foundation-sites/issues/10733

**Comment by DanielRuf** [comment]
> @DanielRuf do you want to take a pass at a PR?

Will plan it for the next week.

**Comment by DanielRuf** [comment]
It seems on `small` the `-webkit-overflow-scrolling: touch` is not applied.

**Comment by DanielRuf** [comment]
Should we apply this to all elements (as optin)?

cc @kball @SassNinja

**Comment by DanielRuf** [comment]
Bump.

This would add a new stacking context.
We set it to all (div) elements in our project and it worked very well.

Who has some more experience?
What is the best way to apply it?

**Comment by ncoden** [comment]
If we apply it, it would be in Global styles. The question is: is there any downside of this. Could it break anything in CSS or JS ? I don't know the specs for this property.

**Comment by DanielRuf** [comment]
I will pick this up again.
