### ISSUE TITLE
Recommended setup with TypeScript?

### ISSUE THREAD

**Issue by Xiaoming94** [foundation/foundation-sites#10817]
This is more like a question

I am using foundation currently in a wordpress-theme with Bower as package manager.

I see that you have a typescript declaration file in the package that gets installed with bowerr.

What is there a recommended way of setting up Foundation with TypeScript?
Have been googling for a while, and I haven't find anything useful. So I thought, maybe I could ask you guys directly.

Keep up the good work! 👍

**Comment by Owlbertz** [comment]
I am not sure whether there is an "official" way, but when I use Foundation with TypeScript I use it like you normally would without TypeScript by including it in the JavaScript and making it available in global scope. I do that by using Webpack.

I guess the answers depends on whether you create the Foundation plugins using JavaScript or if you rely on the HTML attributes.

**Comment by DanielRuf** [comment]
Closing as this depends on your project setup.
