### ISSUE TITLE
Wrapper for accordion link

### ISSUE THREAD

**Issue by claudiuTicu** [foundation/foundation-sites#10813]
Hello, 
I'm using the responsive-accordion-tabs on a project that I'm working.
For my design I would need an extra wrapper on the "a link".
Based on my analysis the issue seems to be from the accordion plugin, due to the fact that you are using
.children() ($elem.children('a')) which takes only the direct children not the nested children(https://api.jquery.com/children/).

Is there any workaround for this ?
#### How to reproduce this bug:

1. add a wrapping div for the "a link"
2. try to change the tabs in the accordion view port

#### What should happen:
changing the tabs should still work

#### What happened instead:
the tabs are inactive

#### Browser(s) and Device(s) tested on:
all browsers

#### Foundation Version(s) you are using:
6.3

#### Test case link:
https://codepen.io/Cllawz/pen/ZvOrrj?editors=1100

**Comment by gtreviranus** [comment]
Why not add your extra class to the `<a></a>`? Seems to accomplish the same thing, and works in chrome/safari/firefox for me now.

**Comment by gtreviranus** [comment]
If you have an exact code example of why you need the extra div to wrap around the link, it would make understanding this use-case a little easier I think.

**Comment by claudiuTicu** [comment]
Hello gtreviranus,
Thank you for your feedback. 
I managed to bypass that issue but still this doesn't offer enough flexibility.
Since this accordion plugin is used in the Responsive Accordion Tabs component is still an impediment for me because I need to add a carousel to the tabs title section.

Please see my example here: https://codepen.io/Cllawz/pen/zpEzvv?editors=1000

Thank you,

**Comment by geotrev** [comment]
@claudiuTicu 

Now I'm really confused about what you're trying to do based on the original post/OP and now your new codepen. 

Can you elaborate a bit on what solution you're striving for here? Seems a bit excessive if all you're doing is adding a div around the `<a>` links.

**Comment by claudiuTicu** [comment]
@geotrev 
As you can see in my pen, I'm trying to add slick on the tabs titles and remove it when it is changed from tabs to accordion on responsive.

It works fine if we come from accordion to tabs, the slick functionality is ok and the display of the elements is as it should be.
But, when we come from tabs to accordion the titles aren't appended to the correct elements do to the fact that foundation is using children and slick is wrapping an extra div to the elements.
So is breaking the layout(content is not correctly appended).
Please see this video: https://vimeo.com/250584842 and let me know if is more cleared now.
Thank you,

**Comment by DanielRuf** [comment]
Slick is not actively maintained and this is not a usecase that we cover by default.
