### ISSUE TITLE
incorrect Foundation.MediaQuery results

### ISSUE THREAD

**Issue by DanielRuf** [foundation/foundation-sites#11122]
Not sure why but the results seem incorrect.

https://codepen.io/DanielRuf/pen/JLBjBy

**Comment by SassNinja** [comment]
@DanielRuf what exactly looks incorrect to you?

On large viewport the following is 100% correct and expected imo
```
Foundation.MediaQuery.is('small only') -> false
Foundation.MediaQuery.is('small') -> true
Foundation.MediaQuery.is('medium') -> true
```

But agree this is incorrect
```
Foundation.MediaQuery.is('small down') -> true
Foundation.MediaQuery.is('medium down') -> true
```

**Comment by DanielRuf** [comment]
The results are not the expected results.

**Comment by SassNinja** [comment]
You mean `Foundation.MediaQuery.is('small')` shouldn't return `true` on large viewport?

**Comment by DanielRuf** [comment]
> You mean Foundation.MediaQuery.is('small') shouldn't return true on large viewport?

No, your other finding:

> But agree this is incorrect
> 
> Foundation.MediaQuery.is('small down') -> true
> Foundation.MediaQuery.is('medium down') -> true

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/ejmgpg

The results are still wrong, `medium down` also fires on medium and up.

**Comment by DanielRuf** [comment]
We should write some unit tests to catch this one and solve this.

**Comment by ncoden** [comment]
The MediaQuery plugin only suppor the breakpoint `only` modifier and ignore all others, this is why it returns the wrong result for `small down`, as it process it like `small`.

A bug is not to throw an error when `down` is passed.
A missing feature is not supporing `down`,

**Comment by RvWensen** [comment]
> The MediaQuery plugin only suppor the breakpoint `only` modifier and ignore all others, this is why it returns the wrong result for `small down`, as it process it like `small`.
> 
> A bug is not to throw an error when `down` is passed.
> And the missing feature is not supporting `down`,

Even that is not working: https://codepen.io/rvwensen/pen/QoVRKx?editors=1111

**Comment by DanielRuf** [comment]
@RvWensen please check the browser console.

> Foundation.MediaQuery.is is not a function

**Comment by DanielRuf** [comment]
> https://cdn.jsdelivr.net/foundation/6.0.5/foundation.min.js

6.0.5 is a *bit* old ;-)

**Comment by RvWensen** [comment]
@DanielRuf Tnx for you quick response, well thats a stupid mistake. Sorry for that!

i updated the Pen, https://codepen.io/rvwensen/pen/QoVRKx?editors=1111 but now it say's its small all the time :)

**Comment by DanielRuf** [comment]
> i updated the Pen, [codepen.io/rvwensen/pen/QoVRKx?editors=1111](https://codepen.io/rvwensen/pen/QoVRKx?editors=1111) but now it say's its small all the time :)

Because `small` is `small` and upwards.

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-sites/issues/11122#issuecomment-385324375

**Comment by RvWensen** [comment]
Ok, i think it's time for a cup of coffee ...
