### ISSUE TITLE
[Tabs] Improve tabs accessibility

### ISSUE THREAD

**Issue by ncoden** [foundation/foundation-sites#11225]
This was reported by @CGTS in an older issue. See https://github.com/zurb/foundation-sites/issues/9767#issuecomment-385547391

The main issue is the following:
> When the page tabs are activated, there is no way to move to the tab panel content with the keyboard. The arrow keys move the user to the next accordion tab while the tab key itself has nothing on which to focus within the tab panels. This will make it impossible for non-sighted users to learn what is on the tab panels.

## Expected Behavior

The tabs component should follow the W3C accessibility recommendations.

According to See https://github.com/zurb/foundation-sites/issues/9767#issuecomment-385547391:
> Manage the focus so that when an accordion tab is activated the focus immediately moves to the tab panel content.

A [W3C note](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/tabs/tabs-1/tabs.html) about Tabs accessibility give a very good example. Here are the features we do not follow. I think we should add all of them:
1. On <kbd>tab</kbd>, when focus moves into the tab link list, places focus on the active tab link.
2. On <kbd>tab</kbd>, when the tab list link is focused, moves focus to the associated tab content.
3. On <kbd>home</kbd>, moves focus to the first tab and activates it.
4. On <kbd>end</kbd>, moves focus to the last tab and activates it.

## Current Behavior

For now, the current behavior is the following:
1. On <kbd>tab</kbd>, focus do not moves into the tab link list
2. On <kbd>tab</kbd>, when the tab list link is focused, the next focusable element is focused, inside or outside of the tab content. The tab content is not focused.
3. On <kbd>home</kbd>, nothing happens.
4. On <kbd>end</kbd>, nothing happens.

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

**Comment by IamManchanda** [comment]
@ncoden As discussed I am taking this up from you ... Busy Next week but will take this up early July :)

**Comment by SassNinja** [comment]
Accessibility seems to have been improved in the meantime - I can't reproduce it
