### ISSUE TITLE
Inline checkbox and label are at different positions

### ISSUE THREAD

**Issue by githubjeka** [foundation/foundation-sites#11399]
See page https://foundation.zurb.com/sites/docs/forms.html

## What should happen?

See checboxes with  `display: inline-block;`

![image](https://user-images.githubusercontent.com/874234/42589481-c6a559c2-8549-11e8-9859-1f769c6818f0.png)

## What happens instead?

When resize window to small, the checkbox and label are at different positions

![image](https://user-images.githubusercontent.com/874234/42590097-8875b6e0-854b-11e8-891a-588d97fb5b5a.png)

## Environment
Window 10, Chrome 67

**Comment by DanielRuf** [comment]
The label should be around the input and text ;-)

**Comment by DanielRuf** [comment]
Should we update the docs @ncoden?

**Comment by joeworkman** [comment]
This seems to have already been fixed.
