### ISSUE TITLE
Responsive Expanded buttons broken in SASS version 6.5.0-rc.1

### ISSUE THREAD

**Issue by mhulet** [foundation/foundation-sites#11396]
## What should happen?

Button with class `.small-only-expanded` should expand only on small screens.

## What happens instead?

Button expands on all screen sizes.

## Possible Solution

I'm adding foundation-sites 6.5.0-rc.1 through Yarn. This can be fixed on lines 278-299 of `foundation-sites/scss/components/_button.scss`. The culprit is `#{$size}`.

```
    @if $button-responsive-expanded {
      @each $size in $breakpoint-classes {
        // @include breakpoint(#{$size} only) {
        @include breakpoint($size only) {
          &.#{$size}-only-expanded {
            @include button-expand;
          }
        }
        @if $size != $-zf-zero-breakpoint {
          // @include breakpoint(#{$size} down) {
          @include breakpoint($size down) {
            &.#{$size}-down-expanded {
              @include button-expand;
            }
          }

          // @include breakpoint(#{$size}) {
          @include breakpoint($size) {
            &.#{$size}-expanded {
              @include button-expand;
            }
          }
        }
      }
    }
```

## Test Case and/or Steps to Reproduce

1. Install foundation-sites 6.5.0-rc.1 with Yarn and set up your app to use Foundation SASS-generated CSS
2. Add `.small-only-expanded` class to a `.button`
3. Look up element CSS: expected breakpoint is not defined

```
/* line 281, /Users/michael/Code/app_name/node_modules/foundation-sites/scss/components/_button.scss */
.button.small-only-expanded {
  display: block;
  width: 100%;
  margin-right: 0;
  margin-left: 0;
}
```

## Your Environment

* Foundation for Sites 6.5.0-rc.1 (SASS version)

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
> #{$size}

This is meant for escaping variables.
Can you post a codepen where this is reproducible?

**Comment by mhulet** [comment]
Here is a CodePen with compiled CSS: https://codepen.io/mhulet/pen/QBwgXv

Uncompiled SASS file:

```
@import 'foundation-settings/app';
@import 'foundation-sites/scss/foundation';
@include foundation-button;
```

With `$button-responsive-expanded: true;` in our custom settings.

Multiple warnings shown while compiling CSS:

```
WARNING: breakpoint(): "small only" is not defined in your $breakpoints setting.
         on line 73 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 146 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 280 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/components/_button.scss, in `foundation-button'
         from line 6 of /Users/michael/Code/app-name/app/assets/stylesheets/app.scss


WARNING: breakpoint(): "medium only" is not defined in your $breakpoints setting.
         on line 73 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 146 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 280 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/components/_button.scss, in `foundation-button'
         from line 6 of /Users/michael/Code/app-name/app/assets/stylesheets/app.scss


WARNING: breakpoint(): "medium down" is not defined in your $breakpoints setting.
         on line 73 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 146 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 286 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/components/_button.scss, in `foundation-button'
         from line 6 of /Users/michael/Code/app-name/app/assets/stylesheets/app.scss


WARNING: breakpoint(): "large only" is not defined in your $breakpoints setting.
         on line 73 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 146 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 280 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/components/_button.scss, in `foundation-button'
         from line 6 of /Users/michael/Code/app-name/app/assets/stylesheets/app.scss


WARNING: breakpoint(): "large down" is not defined in your $breakpoints setting.
         on line 73 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 146 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/util/_breakpoint.scss, in `breakpoint'
         from line 286 of /Users/michael/Code/app-name/node_modules/foundation-sites/scss/components/_button.scss, in `foundation-button'
         from line 6 of /Users/michael/Code/app-name/app/assets/stylesheets/app.scss
```

There is no other place in the Foundation SCSS files where `@include breakpoint(#{$size})` is used. I see `@include breakpoint($size)` everywhere else.

**Comment by DanielRuf** [comment]
```
@import 'foundation-settings/app';
@import 'foundation-sites/scss/foundation';
@include foundation-button;
```

Why this order? The global styles and settings of foundation should be loaded before this.

See https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss

**Comment by ncoden** [comment]
I am not able to reproduce this locally. Button expanded classes are generated correctly. See https://gist.github.com/ncoden/57866145630fbd9027ade3911dec67df.

Plus, `@include breakpoint(small only)` should work fine.

@mhulet Could you check your breakpoint settings (`$breakpoints` and `$breakpoint-classes`) ?

Also, could you provide the following informations:
- Which Sass compiler do you use (node-sass / ruby-sass / etc...), which version ?
- Your Foundation settings file

Thank you.

**Comment by Backoo** [comment]
I have the same issue as @mhulet.

- I use the Ruby gem [`foundation-rails`](https://github.com/zurb/foundation-rails) 6.5.1.0.
- In my `_settings.scss` file there is:
```
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
$print-breakpoint: large;
$breakpoint-classes: (small medium large);
...
```
What could I try to solve the issue?

**Comment by DanielRuf** [comment]
Can you check which Sass version is used?

**Comment by Backoo** [comment]
@DanielRuf It's Ruby Sass 3.7.3

**Comment by dannydehaan** [comment]
I don't know if this is already fixed. I had the same problem with Foundation 6.5.3. I noticed that the default value for the variable $button-responsive-expanded is false. When i set $button-responsive-expanded: true; in my own settings file, it's working.

**Comment by DanielRuf** [comment]
> I don't know if this is already fixed.

There is no PR linked and there was no new release after 6.5.3. So it is not yet fixed.

**Comment by ignacio-gomez** [comment]
Another quick solution: I grabbed the following code from doc.scss (lines 489-531) used in https://foundation.zurb.com/sites/docs/button.html#sass-variables
See attached screenshot of inspect element.
![Screen Shot 2019-11-06 at 4 49 32 PM](https://user-images.githubusercontent.com/9618436/68350585-b0972f00-00b5-11ea-9f10-cb533895686b.png)



@media screen and (max-width: 39.9375em) {
  .button.small-only-expanded {
    display: block;
    width: 100%;
    margin-right: 0;
    margin-left: 0;
  }
}
@media screen and (min-width: 40em) and (max-width: 63.9375em) {
  .button.medium-only-expanded {
    display: block;
    width: 100%;
    margin-right: 0;
    margin-left: 0;
  }
}
@media screen and (max-width: 63.9375em) {
  .button.medium-down-expanded {
    display: block;
    width: 100%;
    margin-right: 0;
    margin-left: 0;
  }
}
@media print, screen and (min-width: 40em) {
  .button.medium-expanded {
    display: block;
    width: 100%;
    margin-right: 0;
    margin-left: 0;
  }
}
@media screen and (min-width: 64em) and (max-width: 74.9375em) {
  .button.large-only-expanded {
    display: block;
    width: 100%;
    margin-right: 0;
    margin-left: 0;
  }
}
@media screen and (max-width: 74.9375em) {
  .button.large-down-expanded {
    display: block;
    width: 100%;
    margin-right: 0;
    margin-left: 0;
  }
}
@media print, screen and (min-width: 64em) {
  .button.large-expanded {
    display: block;
    width: 100%;
    margin-right: 0;
    margin-left: 0;
  }
}

**Comment by kbeck303** [comment]
Running version `6.6` and I was getting this error when compiling `.scss` files using `"gulp": "^4.0.2"`, `"gulp-sass": "^4.0.2"`, and `"node-sass": "^4.13.1"`
```
Details:
    status: 1
    file: /app/docroot/libraries/foundation-sites/scss/components/_close-button.scss
    line: 125
    column: 12
    formatted: Error: ".close-button" failed to @extend "%zf-close-button--medium".
       The selector "%zf-close-button--medium" was not found.
       Use "@extend %zf-close-button--medium !optional" if the extend should be able to fail.
        on line 125 of docroot/libraries/foundation-sites/scss/components/_close-button.scss
>>     @extend %zf-close-button--#{$closebutton-default-size};
```

I installed `"npm-asset/foundation-sites": "6.5.3"` and was able to compile my `.scss` files. 

I hope this gets people unstuck.

**Comment by DanielRuf** [comment]
Not sure what npm-asset/foundation-sites is. The mentione selector is in the current releases an this is not relate to this issue.

https://github.com/foundation/foundation-sites/blob/develop/scss/components/_close-button.scss#L114

You might want to check your sass version.

Closing as this is a very old issue and not relevant anymore.
