### ISSUE TITLE
[Interchange] necessity of the utility library triggers is missing in Interchange docs

### ISSUE THREAD

**Issue by rianne-o** [foundation/foundation-sites#11403]
I was experiencing some issues with Interchange and Foundation 6.4.3. 
On resize, the images set in the arrays didn't get replaced. I did include all the libraries as mentioned in the docs below the 'JavaScript Reference' section. 

When I started debugging in the foundation.interchange.js file, I noticed that the event resizeme.zf.triggers was called. After including the foundation.util.triggers.js file, interchange worked as it should.

Please add foundation.util.triggers.js to the 'JavaScript Reference' section of the docs of Interchange to make sure it's up to date again.

**Comment by DanielRuf** [comment]
Hi @rianne-o,

can you provide a codepen which reproudces this and shows us this behavior / issue?

**Comment by DanielRuf** [comment]
Hi @rianne-o,

can you provide a codepen which reproduces this and shows us this behavior / issue?

**Comment by DanielRuf** [comment]
Hi @rianne-o,

thanks for reporting this.

We'll add it to the docs.

**Comment by MilesStanton** [comment]
Cant you just update foundation.interchange.js to import the triggers and initialise them directly, as is done in OffCanvas, Sticky, DropdownMenu, Reveal, Tooltip, Slider or Toggler?
