### ISSUE TITLE
There is a 1 px white gap on the left of header

### ISSUE THREAD

**Issue by Just2Archi** [foundation/foundation-sites#11422]
## Description
There a about 1px white gap on the left of header https://foundation.zurb.com/

![image](https://user-images.githubusercontent.com/36980228/43353624-7437ea6e-926f-11e8-8d4c-6ae9eba63579.png)

- macOS 10.13.6
- browser: Chrome 67.0.3396.99
- resolution: 1920x1080

It seems that it's part of a scroll bar. I notice that by zoom the page with " ⌘➕"

## Possible Solution
Just remove it.

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by ncoden** [comment]
Hi @Just2Archi, thank you for the issue!

It appears to come from the background SVG used for large screens.

**Comment by DanielRuf** [comment]
`preserveAspectRatio="none"` should fix it.

**Comment by DanielRuf** [comment]
It seems `preserveAspectRatio` does not help here and we have to check the viewBox and other alues of the svg file.

**Comment by ncoden** [comment]
Actually there is a "gap" in the SVG itself, see https://foundation.zurb.com/assets/img/home-bg-01.svg. The SVG resizing is correctly handled by the browser.

**Comment by ncoden** [comment]
No, the Foundation marketing website is not open source. I'll check if we can me it public...

**Comment by DanielRuf** [comment]
It seems this is fixed now. At least I can not reproduce it in any browser on macOS.
