### ISSUE TITLE
Nuget package has odd structure

### ISSUE THREAD

**Issue by xavierzwirtz** [foundation/foundation-sites#11438]
## What should happen?
Install nuget package using paket, and files are extracted properly.

## What happens instead?
Error is thrown during install:
```
Paket failed with
-> Error during extraction of C:\repo\packages\foundation-sites\foundation-sites.6.5.0-rc.2.nupkg.

    In rare cases a firewall might have blocked the download. Please look into the file and see if it contains text with further information.
-> UnauthorizedAccessException: Access to the path 'C:\repo\packages\foundation-sites\content\Scripts' is denied.
```

## Possible Solution
Looks like the nupkg file has something weird going on with it, extracting it manually using 7zip also fails.

## Test Case and/or Steps to Reproduce

Test Case:

How to reproduce:
1. Clone https://github.com/xavierzwirtz/foundation-nuget-repro
2. run ./.paket/paket.bootstrapper.exe
3. run ./.paket/paket.exe install

## Your Environment

- Foundation 6.4.3 and Foundation 6.5.0-rc.2. Oddly 6.4.1 works.
- Windows 10

## Checklist (all required):

- [x ] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [ x] The issue title is descriptive.
- [x ] The template is correctly filled.

**Comment by ncoden** [comment]
Thank you for the report @xavierzwirtz. I think it comes from the way we created the package using `nuget-publish`. I have to admit that I do not know or use the .NET environment. I'll take a look at it.

**Comment by ChrisK91** [comment]
I've just come across the same issue, running Visual Studio 2017 on Windows 10. This has also been reported here: https://github.com/dotnet/cli/issues/9594

**Comment by ncoden** [comment]
Thank you @ChrisK91 for the report 👍

**Comment by DanielRuf** [comment]
Is this still relevant for 6.5.3?

**Comment by DanielRuf** [comment]
This should be resolved, I see only a `Scripts` directory, no file.

<img width="879" alt="Bildschirmfoto 2019-10-19 um 17 57 17" src="https://user-images.githubusercontent.com/827205/67147937-f4a6c900-f299-11e9-9079-c738eb87fefa.png">
