### ISSUE TITLE
Sizing is incorrect for button-groups contained within the second column of tables where the any button has a space in the title

### ISSUE THREAD

**Issue by toebes** [foundation/foundation-sites#11493]
## What should happen?
The Columns in the table should not overlap when the second column is a button-group with a space in the title of the last button.

## What happens instead?
The right hand edge of the button overlaps with the next column.  Depending on the version of Foundation and the browser, you see somewhat different results, Chrome seeming to be the most problematic.  With 6.4.3 on chrome (https://codepen.io/toebes/pen/dqzJgX) the third column actually overwrites the right most portion of the button.  On Firefox it actually works properly for the 6.4.3 version but with the examples on the foundation main documentation page you see the right most edge of the button shift as you resize the window.  With Edge the problem is much more pronounced. 

## Possible Solution
Change all spaces in buttons to use &nbsp; and the problem goes mostly away.

## Test Case and/or Steps to Reproduce (for bugs)
Test Case1: https://codepen.io/toebes/pen/MqvrBZ  - Has overflow:hidden to show the problem more
Test Case2: https://codepen.io/toebes/pen/dqzJgX
Test Case3: https://codepen.io/toebes/pen/MqObXM - this makes it much more obvious

How to reproduce:
1. Create a table with a button-group in the Second column and have the second button have a space in the title.

## Context
This is a part of the UI for the Science Olympiad Code Busters Test Generation Tools (https://toebes.com/codebusters/) for managing tests.  The buttons are associated with questions to allow editing/deleting/etc of the questions.

## Your Environment
- Foundation version(s) used: 6.4.3 (and whatever the default pen version is for the samples)
- Browser(s) name and version(s): Chrome Version 68.0.3440.106 (Official Build) (64-bit), Firefox Quantum 62.0b18 (64-bit), Edge 42.17134.1.0
- Device, Operating System and version: Windows 10
- Link to your project: https://github.com/toebes/ciphers

## Checklist
- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by AKaravas** [comment]
Have you tried to give the <th> a width parameter?
For example <th width="200">. Then the whole columns would take this width and the buttons will no longer overlap the next column.

**Comment by toebes** [comment]
Certainly hard coding a width would hide the bug, but it defeats the purpose of letting the system dynamically adjust to screen layouts.  Changing the space to &nbsp; allows the table to dynamically adjust to the screen layouts, but the bug still remains.

**Comment by toebes** [comment]
I added a new test case https://codepen.io/toebes/pen/MqObXM which makes it much more obvious what is going on.

**Comment by DanielRuf** [comment]
Well, the button groups have specific styles which do not work with this use case.
And there is the flex-wrap bug https://github.com/foundation/foundation-sites/issues/9325.

https://codepen.io/DanielRuf/pen/JjjbNBj

This should be resolved by https://github.com/foundation/foundation-sites/pull/11871
