### ISSUE TITLE
Any anchor tag inside li.accordion-item opens panel

### ISSUE THREAD

**Issue by marcelox** [foundation/foundation-sites#11542]
## What should happen?

Inside a `li.accordion-item`, an independent anchor (without an `accordion-title` class) should follow its href and should not trigger the accordion handler to open its respective panel.

## What happens instead?

If I place an anchor beside an `a.accordion-title`, it opens the panel even though it doesn't have an `accordion-title` class.

## Possible Solution

In the example I placed on an codepen pen, I matched the anchor as shown below. Even though the panel is being opened, and only after that the target is fired (by the `href` attribute):

       
        $('.within-title').on('click', (e) => {
              window.location = $(e.currentTarget).attr('href');
         })

It should be another solution for preventing the anchor listening to the accordion component. How can I do that?

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/mcordeiro/pen/ePVdvL

## Your Environment

- Foundation version(s) used: 6.4.2

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by SassNinja** [comment]
@marcelox thanks for posting this issue!

The problem here is the accordion plugin does consider all `<a>` children of the item as title.

The only quick solution that comes in my mind is not using an `<a>` but something else (e.g. `<span>`).
Would this be an option for you?

**Comment by SassNinja** [comment]
@ncoden the problem we use `$().children('a')` as selector does not only affect the accordion plugin but some more (drilldownMenu, dropdownMenu, responsiveAccordionTabs).

Do you think we should take care of this or leave it?

**Comment by marcelox** [comment]
Thank you, @SassNinja! My problem is that I need a tag that leads to a link, like I did in the codepen example, would you have a look? Maybe I could use a `<button>`, but I still don't have the _clean_ possibility to have an `href` in it.

**Comment by aj1991** [comment]
> @ncoden the problem we use `$().children('a')` as selector does not only affect the accordion plugin but some more (drilldownMenu, dropdownMenu, responsiveAccordionTabs).
> 
> Do you think we should take care of this or leave it?

What about an option for overwriting defaults?

**Comment by SassNinja** [comment]
> My problem is that I need a tag that leads to a link, like I did in the codepen example, would you have a look? Maybe I could use a `<button>`, but I still don't have the clean possibility to have an `href` in it. – @marcelox 

I did take a look at your codepen – that's why I suggested a `<span>`.
Of course you can't use `href` then anymore but since you're already used JS in your codepen you could write something as `<span data-href="https://...">pseudo link</span>``

Or are you concerned about other things? (accessability, keyboard navigation etc.)?
I mean sure, using a `<a>` for a link is of course better but I've just posted this workaround so you don't need to wait for a fix.

> What about an option for overwriting defaults? – @aj1991 

An option to specify a custom selector or did you have something else in mind?

**Comment by marcelox** [comment]
Hi, @SassNinja, I have a provisional solution keeping an anchor, doing this (by removing the handler):
`$('.child-anchor-that-is-not-accordion-title').off('.zf.accordion');`
Thank you again for your help. maybe it could be good to match the selector say with its class `accordion-menu-title` in future versions of Foundation.

**Comment by aj1991** [comment]
> > What about an option for overwriting defaults? – @aj1991
> 
> An option to specify a custom selector or did you have something else in mind?

Yeah, a custom selector was in my mind - I love the opportunity to specify my own selector and have it under my control.

**Comment by heppstux** [comment]
hi folks, why not just attach the event to the a.accordion-title? it's simple and clean, doesn't need any "options" and – looking at the docs – this class is mandatory on the accordion-title anyways... for now i can live with the .off('. zf.accordion') but this still feels like monkey-patching...

**Comment by SassNinja** [comment]
> why not just attach the event to the a.accordion-title? it's simple and clean – @heppstux 

I think the most consistent way would be to add something as `data-link` and use this as selector for all related components (accordion, responsive accordion tabs, etc). However this would force everyone to adjust the markup after updating (breaking change).

Selecting by `.accordion-title` on the other hand is a quick solution but maybe too short-sighted (what about responsive accordion tabs and all other plugins thats select by `children('a')`?)

Besides it would also be a potential breaking change to use `.accordion-title` as selector bcz it's not mandatory to use it if you're doing the styling yourself.

I'm curious abt what @ncoden thinks.

**Comment by SassNinja** [comment]
Regarding the breaking change I can imagine a solution to cover both cases:
- if `children('[data-link]')` use this
- else fallback to `children('a')`

This way you get an option to exclude certain `<a>` and no existing project would break after updating.

**Comment by DaveLak** [comment]
Has anything changed with this issue? Has it been fixed in newer versions?
I've ended up here after experiencing the issue in 6.4.3.

**Comment by DanielRuf** [comment]
> Has anything changed with this issue? Has it been fixed in newer versions?

Probably not as it is still open.

> I've ended up here after experiencing the issue in 6.4.3.

6.6.3 is the latest version. If it is still the case there, then it is still not fixed.

**Comment by pattonwebz** [comment]
It is still not fixed in the latest stable :(

What would it take to get this moved forward?

**Comment by DanielRuf** [comment]
https://github.com/foundation/foundation-sites/issues/11542#issuecomment-431003603

PRs are very welcome.

**Comment by pattonwebz** [comment]
Happy to make a PR :) 

Would this type of change be considered a breaking change or a bug fix?

If it's a breaking change would it need to wait till v7 before it releases?

**Comment by DanielRuf** [comment]
> If it's a breaking change would it need to wait till v7 before it releases?

Not sure what you mean with breaking change but in my opinion this would not be a breaking change.

> This way you get an option to exclude certain `<a>` and no existing project would break after updating.

**Comment by pattonwebz** [comment]
> Not sure what you mean with breaking change but in my opinion this would not be a breaking change.

Perfect :heart:, I will try get a PR made soon then.
