### ISSUE TITLE
Compiling sass with laravel mix results in wrong references in sourcemap

### ISSUE THREAD

**Issue by bonovski** [foundation/foundation-sites#11574]
## What should happen?

**_For example:_**

An `<h1>` tag is styled in my **_custom.sass** file, which is imported as the last file to my **styles.scss**.
When I open dev tools in my browser the inspector should reference **_custom.sass** when highlighting the `<h1>` tag.

## What happens instead?

The inspector wrongly references **normalize.scss** which is a part of foundation. This happens with **all html tags** that are inside **normalize.scss** and are being styled afterwards in **_custom.sass**.
If I style a class that is not included in **normalize.scss** the sourcemap works as it should.

## Possible Solution

When I don't import foundation, sourcemapping works as expected. There seems to be a problem with normalize.scss or the mixin.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. webpack.mix.js

```
const mix  = require('laravel-mix');

// node_modules paths
const motionUI      = 'node_modules/motion-ui/src';
const foundation    = 'node_modules/foundation-sites/scss/';
const datepicker    = 'node_modules/foundation-datepicker/scss';


mix.setPublicPath('assets');


// BrowserSync and LiveReload on `npm run watch` command
mix.browserSync({
	proxy: 'http://wpdev.test',
	files: [
		'**/*.php',
		'assets/css/**/*.css',
		'assets/js/**/*.js'
	],
	injectChanges: true,
	open: false
});


if (!mix.inProduction()) {
	mix.webpackConfig({
		devtool: 'source-map'
	});
}


// Compile assets
mix.js('src/js/scripts.js', 'assets/js/scripts.min.js')
	.sass('src/scss/styles.scss', 'assets/css/styles.min.css', {
		includePaths: [foundation, motionUI, datepicker]
	} )
	.options({
		autoprefixer: {
			options: {
				browsers: [
					'last 6 versions',
				]
			}
		}
	})
	.sourceMaps();

```

2. styles.scss
```
// import sass
@import 'settings'; // override default foundation settings
@import 'foundation';
@import 'motion-ui';


// include mixins
@include foundation-everything; // include all foundation components
@include foundation-grid;

@include motion-ui-transitions;
@include motion-ui-animations;

// import foundation-datepicker
@import 'foundation-datepicker';

// base
@import 'base/variables';

// partials
@import 'partials/typography';
@import 'partials/test';
@import 'partials/off-canvas';

// custom
@import 'custom';

```

## Your Environment

- Foundation version(s) used: 6.5.0
- Browser(s) name and version(s): up-to-date chrome, firefox, safari
- Device, Operating System and version: macos, windows10
- Link to your project: 

## Checklist

- [x ] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
Hi @bonovski 👋,

I don't understand your issue very well, but you could try using [source-map-loader](https://github.com/webpack-contrib/source-map-loader) to load dependencies' sourcemaps.

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
