### ISSUE TITLE
Magellan does not receive scroll events when used by itself

### ISSUE THREAD

**Issue by mattlima** [foundation/foundation-sites#11645]
## What should happen?

When importing and using the Magellan module by itself via `new Foundation.Magellan($element)`, the Magellan nav should update on scroll. 

## What happens instead?

Magellan nav items do not update on scroll because the `Triggers` module is not initialized in the module code the way it is done, for example, in [Reveal](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L38). 

## Possible Solution

Ensure that `Triggers.init($)` [is called](https://github.com/mattlima/foundation-sites/blob/develop/js/foundation.magellan.js#L33) in the Magellan module definition.

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
```javascript
window.$ = window.jQuery = require 'jquery';
import { Foundation } from 'foundation-sites/js/foundation.core.js';
import { smoothScroll } from 'foundation-sites/js/foundation.smoothScroll.js';
Foundation.smoothScroll = smoothScroll;
import { Magellan } from 'foundation-sites/js/foundation.magellan.js';
Foundation.addToJquery($);
new Foundation.Magellan( $("my-magellan-component") );
```

When paired with boilerplate HTML, the above code will add the `is-active` class to the appropriate nav item on `load` and produce scrollToLocation when nav items are clicked, but the nav does not update on scroll. **NB `$(document).foundation()` must not be called to reproduce this.**

## Your Environment

- Foundation version(s) used: 6.5.1
- Browser(s) name and version(s): Chrome Version 70.0.3538.110 (Official Build) (64-bit)
- Device, Operating System and version: MacOS 10.13.6 running on MacBook Pro (17-inch, Early 2011)
- Link to your project: sorry, proprietary

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [ x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
@ncoden I think we have / had an issue about this or do we not know about the `Triggers` issue so far?

**Comment by DanielRuf** [comment]
@ncoden I think we have / had an issue about this or do we not know of the `Triggers` issue so far?

**Comment by DanielRuf** [comment]
Fixed by https://github.com/foundation/foundation-sites/pull/11654
