### ISSUE TITLE
Changing Gutter width ONLY in specific area

### ISSUE THREAD

**Issue by pcross1986** [foundation/foundation-sites#11677]
## Description

I am using Foundationpress theme, specifically for Wordpress, using the Foundation framework(version 6.4.3, using the X-Y Grid. I know how to change the column gutter width in the _settings sass file. However, on a specific page, where a gallery shows(using the block grid), I do not need the gutters to be so small. I only want to change the gutter widths in that area. How can I change the gutter width ONLY for those cells in the particular block grid?

## Possible Solution

I am not sure without completely hacking it and possibly wasting time.... Id like to know the best possible solution for achieving this.

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @Chris--S, did you already try the mixins from https://foundation.zurb.com/sites/docs/xy-grid.html#sass-reference?

**Comment by DanielRuf** [comment]
Hi @pcross1986, did you already try the mixins from https://foundation.zurb.com/sites/docs/xy-grid.html#sass-reference?

**Comment by pcross1986** [comment]
Thank you for the quick response....

Honestly, I am a little new to mixins. Maybe you could help me out?
All I have set is where you set the gutter widths in the _settings file, underneath the X-Y Grid settings.

My markup is....

`<section class="main-services">
<div class="grid-container">
	<div class="grid-x grid-margin-x small-up-1 medium-up-2 large-up-3 align-center">
		<div class="cell ind-service-wrapper">
			<a href="#">
				<img src="#" />
				<div class="service-title-wrapper text-center">
					<h3>Testing Title</h3>
					<div class="gradient-overlay"></div>
				</div>
			</a>
		</div>
	</div>
</div>
</section>`

So how would I use one of those mixins to change the width of the gutters for those cells?
Thank you again for your help!

**Comment by DanielRuf** [comment]
Sass mixins are functions to generate code in a selector in Sass.

Also see https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_gutter.scss
For this you have to use the Sass version of Foundation Sites.

If you do not use this version you have to manually write the codes or generate them on another way and use them for custom classes (including all defined breakpoints and settings).

**Comment by pcross1986** [comment]
I am using Sass...

**Comment by DanielRuf** [comment]
Then you can try the following:

```
.ind-service-wrapper {
  @include xy-cell(full, true, $grid-margin-gutters, margin, right left, null, false);
}

For `$grid-margin-gutters` or a custom gutter map, see https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L861-L864

**Comment by pcross1986** [comment]
Hey Daniel, thank you for your help. I apologize for the delay in getting back to you. You helped me out tremendously. For anyone wanting to know my solution:

I added:
@include xy-cell(33%, true, 30, margin, right left, null, false); to my **.ind-service-wrapper** class. 

Then I changed my markup, since I used the xy-cell mixing, I removed the **.cell** class from my block grid, and also removed my small. medium-up classes.

My finally markup was: 
`<section class="main-services">
<div class="grid-container">
	<div class="grid-x grid-margin-x align-center">
		<div class="ind-service-wrapper">
			<a href="#">
				<img src="#" />
				<div class="service-title-wrapper text-center">
					<h3>Testing Title</h3>
					<div class="gradient-overlay"></div>
				</div>
			</a>
		</div>
	</div>
</div>
</section>`

**Comment by losderpos** [comment]
How do you deal with the whitespace before the first and after the last element?

**Comment by DanielRuf** [comment]
Hi @losderpos,

Please open a new issue and provide more details.

> How do you deal with the whitespace before the first and after the last element?

**Comment by apriljunge** [comment]
@DanielRuf I think you can close this issue as this is solved

**Comment by Brayn7** [comment]
> How do you deal with the whitespace before the first and after the last element?

.layout_two_column .layout-grid {
    $large-grid-margin-gutters: (
      small: 100px,
      medium: 100px
    );
  &.grid-margin-x {
    @include xy-gutters($large-grid-margin-gutters, margin, left right, true);
  }
  .cell {
    @each $break, $value in $grid-margin-gutters {
      @include xy-cell(50%, true, $large-grid-margin-gutters, margin, right left, $break, false);
    }
  }
}
