### ISSUE TITLE
Problem with is-active

### ISSUE THREAD

**Issue by benthien** [foundation/foundation-sites#11745]
## Expected Behavior
The menu item with class .is-active should be highlighted.

...

## Current Behavior
If the list has just the class menu, then is-active produces the correct result. However, if the class .dropdown is added along with menu, the highlighting goes away. If is-active is replaced by active, everything works fine. Incidentally, the video and codepen in foundation docs still has .active, not is-active.

...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)
https://codepen.io/benthien/pen/xeemrP

Test Case: 

How to reproduce:
1.
2.
3.

## Context
I ran into the problem while constructing a top-bar navigation menu containing dropdown menus. I can get by for now using active, but I understand it is to be deprecated.

...

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Opera 58.3135.132
- Device, Operating System and version: Windows 10 Home latest version
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] This is a bug report or a feature request.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by blynnc** [comment]
I am having this problem with Foundation 6.5.3 - getting the Accordian Title to be in an is-active state (color) when it is active. Nothing I've tried works so far.

**Comment by DanielRuf** [comment]
This is documented and probably how it should be.

https://github.com/foundation/foundation-sites/blob/v6.5.3/scss/components/_dropdown-menu.scss#L160

https://github.com/foundation/foundation-sites/blob/v6.5.3/scss/components/_dropdown-menu.scss#L58-L64

<img width="760" alt="Bildschirmfoto 2019-10-19 um 20 10 09" src="https://user-images.githubusercontent.com/827205/67149527-7a337480-f2ac-11e9-8168-64b5cc703153.png">
<img width="793" alt="Bildschirmfoto 2019-10-19 um 20 10 47" src="https://user-images.githubusercontent.com/827205/67149532-8fa89e80-f2ac-11e9-8c6d-9217d570e7d8.png">

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
