### ISSUE TITLE
Plugin init events in minified version broken

### ISSUE THREAD

**Issue by pprossi** [foundation/foundation-sites#11743]
Hi, what is here the trouble with the minified version of foundation?

## What should happen?
Acordion init event should be triggered on initialization like in this codepen with unminified version of the script.

https://codepen.io/rero/pen/NmoRoa

## What happens instead?

Init Events are not triggered like in this codepen with minified version of the script.
https://codepen.io/rero/pen/jRdMva

any other events from within the plugin theme to work. like the click events.

## Test Case and/or Steps to Reproduce (for bugs)
Load minified version of Foundation JS instead of source version

## Your Environment
i've seen this in Foundation 6.4.3 and latest 6.5.3

**Comment by DanielRuf** [comment]
Hi, can you test the minified files from the releases tab here on GitHub and verify that these also do not work?

**Comment by pprossi** [comment]
Of course :) 
I've updated the codepens with the latest release.
Still not working. :(

**Comment by DanielRuf** [comment]
I meant not the CDN files but the files from the GitHub releases directly.

**Comment by pprossi** [comment]
yes. they are in... ive added some log.
> "currently loaded scripts:" "https://github.com/zurb/foundation-sites/releases/download/v6.5.3/foundation.js"

**Comment by DanielRuf** [comment]
Hm, so this seems to be a minification issue but I wonder why and where.

**Comment by pprossi** [comment]
I've no idea. But it seems to be a problem for a longer time, over different versions.

**Comment by pprossi** [comment]
Ich hatte mittlerweile ein wenig Zeit mir den Build Prozess mal anzuschauen.

https://github.com/zurb/foundation-sites/blob/80cc5700b9c68e69d266ab049c8c2e97f6df0fb7/gulp/tasks/deploy.js#L86

Hir findet sich der Uglify Prozess.
Das Problem wird hier definitiv durch die Code Zerstückelung erzeugt.

Ein wenig herumprobieren zeigte das es im besonderen um die Funktionsnamen Verschleierung geht, startet man den Build mit:
> .pipe(uglify({ warnings: true, compress: true, mangle: true, toplevel: false, keep_fnames: true  }))

Scheint alles zu funktionieren. 
Ohne Funktionsnamen Verschleierung.: 185 kb
Mit Funktionsnamen Verschleierung.: 171kb

So lange das Problem im code nicht behoben werden kann, empfehle ich diesen Größenunterschied hinzunehmen.

**Comment by DanielRuf** [comment]
@pprossi interesting findings. So it seems like uglify loses the reference at some place. We should check if terser has the same issue which is the successor to uglify.

**Comment by pprossi** [comment]
terser ändert an dem grundlegenden Problem nichts.

Eine weitere funktionierende Variante welche in einer Dateigröße von 178 kb reduziert.
> .pipe( uglify( { mangle: { keep_fnames: true } } ) )

Die Frage welche sich stellt ist, könnte eventuell der Ausschluss bestimmter Funktions Namen mittels { `mangle: { reserved:['fnname','fnname2'] }` anstelle aller, eine weitere Optimierung bringen.

Das sollte mal jemand testen der sich mit den Skripten auskennt?!?

**Comment by pprossi** [comment]
https://github.com/zurb/foundation-sites/blob/80cc5700b9c68e69d266ab049c8c2e97f6df0fb7/js/foundation.core.plugin.js#L48

Diese Codezeile funktioniert nicht in einer Obfuscierten Version der Scripte.
Funktions und Klassennamen werden durch Kürzel ersetzt, in diesem Fall hauptsächlich durch 'i' und 'n'.

Testen lässt sich das in der Basisversion des Scripts leicht durch hinzufügen der entsprechenden Listener.
```javascript
$(document).bind('init.zf.i', function (e) {
  console.log('i initialized', e.target.id);
});
$(document).bind('init.zf.n', function (e) {
  console.log('n initialized', e.target.id);
});
```
Das liefert in der Ausgabe
```
n initialized 1 outerAccordion
n initialized 2 innerAccordion
n initialized 3 exampleResponsibleTabs2
n initialized exampleDropdown2
i initialized offCanvas
...
```

Eine einfache Lösung ist der Verzicht auf die Nutzung des Konstruktor Namens an dieser Stelle und ausschließliche Nutzung des Klassennamens.

```javascript
function getPluginName(obj) {
	return hyphenate(obj.className);
}
```
**Somit lässt sich die mangle Funktion wieder vollständig nutzen.**

Wenn ich das richtig sehe sollte die Nutzung des Konstruktor Namens auch zu anderen Problemen führen wie z.B. bei der Verwendung des Plugin Namens bei der suche nach Data-Attributen wie hier:

https://github.com/zurb/foundation-sites/blob/80cc5700b9c68e69d266ab049c8c2e97f6df0fb7/js/foundation.core.plugin.js#L16

An dieser Stelle würde ebenfalls nach `data-n` bzw `data-i` Attributen gesucht werden.

Oder die entsprechende `destroy` Function.

Dies könnte u.U. einige Bugs hier betreffen.

**Comment by DanielRuf** [comment]
Hi @pprossi,

awesome, I think you have found the culprit =)

Can you provide a PR with your proposed changes so we can test them?

This would be great.

Thank you and have a nice Saturday!
