### ISSUE TITLE
Magellan with data-offset does not trigger correctly on the first item

### ISSUE THREAD

**Issue by mingyeungs** [foundation/foundation-sites#11754]
## What should happen?
Magellan with `data-offset` should should be triggered at offset positions

## What happens instead?
All menu items, but not the first one, is triggered at the correct position.

## Possible Solution

update `/js/foundation.magellan.js` line 170:

from 
`if(newScrollPos < this.points[0]){ /* do nothing */ }`

to: 
`if(newScrollPos < this.points[0] - this.options.offset - (isScrollingUp ? this.options.threshold : 0)){ /* do nothing */ }`

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/mingyeungs/full/oRerpB

## Your Environment

- Foundation version(s) used: 6.5.1
- Browser(s) name and version(s): Chrome 74.0.3729
- Device, Operating System and version: macOS High Sierra (10.13.4)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by JPustkuchen** [comment]
Yup, we can confirm this problem! Any chance to fix this?

**Comment by thomasfrobieter** [comment]
I can confirm that @mingyeungs fix works fine!

**Comment by DanielRuf** [comment]
Thanks for confirming that this resolves the issue. PRs which fix this are very welcome.
