### ISSUE TITLE
Custom Build = No CSS

### ISSUE THREAD

**Issue by spinmortgage** [foundation/foundation-sites#11795]
Generating Custom Build
https://foundation.zurb.com/sites/download.html/

With the following enabled:

XY Grid 
Typography 
Float Classes 
Visibility Classes 
Menu
Drilldown Menu
Card

Causes NO CSS file to be included in the custom build archive.

**Comment by spinmortgage** [comment]
Add "Off Canvas" and to list and CSS appears in the custom build.

**Comment by spinmortgage** [comment]
Worst luck, getting 

ENOENT: no such file or directory, stat '/tmp/tmp.6.5.1.7283e2bcebce23f812712b3a2fb68c39.zip'

with the following build:

Flex Grid 
Typography
Visibility Classes
Menu
Drilldown Menu
Columns 12
Total Gutter 1.25rem
Max-Width 25.875rem
Radius 50

**Comment by spinmortgage** [comment]
Half the combinations I build don't include CSS.

**Comment by DanielRuf** [comment]
Maybe related: https://github.com/zurb/foundation-sites/blob/develop/customizer/lib/sass.js#L60

**Comment by DanielRuf** [comment]
I can not reproduce this with https://github.com/foundation/node-foundation-customizer/pull/13

**Comment by spinmortgage** [comment]
@DanielRuf still broken.

ENOENT: no such file or directory, stat '/tmp/tmp.6.5.1.b7f80a12fcf5adadb31773141a060180.zip'

"Flex Grid" + max width change + random componets = failed

**Comment by DanielRuf** [comment]
We are aware of it, please see the linked PR which will fix it =)
