### ISSUE TITLE
Update codepen.io with importable scss reference

### ISSUE THREAD

**Issue by bozach** [foundation/foundation-sites#11806]
## Description

CodePen.io, under the official Zurb Foundation user, no longer has an up to date importable scss reference.  The last importable template is from May 2017.  You can see the issue demonstrated here:  

https://codepen.io/ZURBFoundation/pen/rmpWNK

...which imports from:

https://codepen.io/ZURBFoundation/pen/mmprJa

without the compiled sass you can't use any mix-ins, sass references, or functions.  So what happens is you have to hack around my media queries and such instead of being able to import them.  this causes a disconnect since the only other option currently is to import compiled css.  public code pens for learning/demo purposes also give less value to anyone who googles/stumbles across it because of the missing ability to use functions, base references, and mixins in scss.  

Fixing this also adds the ability for you to add demo links in your docs.

## Possible Solution

Update the importable template to the most recent version and maintain it

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by bozach** [comment]
I ended up figuring out how to do this myself.  

You are welcome to fork it for your own uses:  https://codepen.io/bozach/pen/wvwZbLL 

Then in your actual pen after linking to it as an external css file, add

`@include foundation-everything; //(or whatever base you want) ` 

You should be able to hit view compiled css afterwards and you'll see the post-processed css to verify it worked.

**Comment by DanielRuf** [comment]
We should migrate to something like storybook to be able to update the code.

**Comment by DanielRuf** [comment]
See https://github.com/foundation/foundation-sites/issues/11867
