### ISSUE TITLE
Interchange - Docs - Demonstration Codepen 

### ISSUE THREAD

**Issue by blynnc** [foundation/foundation-sites#11819]
What is incorrect, missing or could be improved?

https://codepen.io/ZURBFoundation/pen/JNZQGB?editors=1000

QUESTION - why is , small - calling a large image ?

<img data-interchange="[https://foundation.zurb.com/sites/docs/assets/img/interchange/large.jpg, small], [https://foundation.zurb.com/sites/docs/assets/img/interchange/medium.jpg, medium], [https://foundation.zurb.com/sites/docs/assets/img/interchange/large.jpg, large]">

What do you suggest to resolve this issue?

It depends on the reason a large image is being called for small
...

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] here are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @blynnc,

thanks for reporting this. These are old codepens and this was probably a typo.

See https://codepen.io/DanielRuf/pen/KKPBPab?editors=1000

Did you use our issue template? It does not seem so.

**Comment by SassNinja** [comment]
@blynnc where have you seen this codepen?

**Comment by DanielRuf** [comment]
See the first "edit in browser" at https://foundation.zurb.com/sites/docs/interchange.html.

**Comment by rafibomb** [comment]
Updated the pen for a small image on small breakpoint. Thanks for the report!

**Comment by blynnc** [comment]
So, what was the problem? Would appreciate to know what you did to fix it.

**Comment by DanielRuf** [comment]
There was `large` referenced for `small`.
