### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by DanielRuf** [foundation/foundation-sites#11827]
## Description

We should add a new linting setup for better code quality. The current one is not very good and has not modern rules.

## Possible Solution

Some eslint setup with airbnb rules.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by LakshanKarunathilake** [comment]
Interested in this contribution can I work on this

**Comment by DanielRuf** [comment]
Hi @LakshanKarunathilake,

Thanks for your interest in contributing to Foundation Sites.

Yes, you can work on this.

Feel free to ask if you have any questions or need any assustance.

**Comment by LakshanKarunathilake** [comment]
Do you guys have discord or any community chat so I can ask uncertain things and also take part in future contributions

**Comment by DanielRuf** [comment]
No discord but a forum at https://foundation.discourse.group/ and probably a gitter channel.
