### ISSUE TITLE
6.5.3 docs have wrong names for Off Canvas events.

### ISSUE THREAD

**Issue by jsgarvin** [foundation/foundation-sites#11824]
## Description

Documentation for 6.5.3 says that the [off canvas events are camel cased](https://foundation.zurb.com/sites/docs/off-canvas.html#js-events), however, [code for 6.5.3 is not](https://github.com/foundation/foundation-sites/blob/v6.5.3/js/foundation.offcanvas.js#L354).  On the other hand, code on `develop` branch [does have them camel cased](https://github.com/foundation/foundation-sites/blob/develop/js/foundation.offcanvas.js#L473).  

Docs for 6.5.3 appear to be prematurely instructing to use the camel cased versions.

## Possible Solution

Docs for 6.5.3 should be updated to match the correct event names.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @jsgarvin,

The generated docs use the right name which is the class name and the fallback name.

https://github.com/foundation/foundation-sites/blob/v6.5.3/js/foundation.offcanvas.js#L19

https://github.com/foundation/foundation-sites/blob/v6.5.3/js/foundation.offcanvas.js#L23

**Comment by DanielRuf** [comment]
Hi @jsgarvin,

Thanks for the hint, we will check this.

**Comment by besseddrest** [comment]
@DanielRuf curious - wouldn't it be pertinent to push the correct documentation asap rather than leave the incorrect version online?

**Comment by DanielRuf** [comment]
I am not in charge of the docs and I do not have the needed system access to deploy them.

**Comment by DanielRuf** [comment]
I had already forwarded it to the correct person in our team.

**Comment by SassNinja** [comment]
seems the docs were beyond the released code

however since the v6.6.0 release docs & code match again so I'm closing here
