### ISSUE TITLE
give deeplink-smudge a deeplink-offset to prevent scrolling behind a fixed menu at top of page.

### ISSUE THREAD

**Issue by Lefthandmedia** [foundation/foundation-sites#11821]
## What is missing?

if i give a data-deeplink-smudge-offset to the accordeon i expect the page to scroll the accordeon in viewport minus this offset
...

## What is wrong now ?

Right now when you have a menubar that is FIXED  and the page scrolls up to scroll the accordeon into the top of the view it is hidden behind the menubar. When i'm able to give it a offset i can make sure all accordeons that scroll into view will not be hidden
...

## Possible Solution

Create an extra data propertie for **accordeons data-deeplink-smudge-offset** and add it to the animation that scrolls the element. 
` $('html, body').animate({ scrollTop: offset.top - deeplink-offset }, this.options.deepLinkSmudgeDelay);`
...

## Context

...

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): All
- Device, Operating System and version: All

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @Lefthandmedia,

Can you share an example with us?

**Comment by Lefthandmedia** [comment]
in HTML add the newly to create option 'data-deep-link-smudge-offset'
```
<ul class="c-foldout {{modifier}}"
    data-accordion data-deep-link="true"
    data-deep-link-smudge-offset = "300"
    data-deep-link-smudge="true"
    data-deep-link-smudge-delay="600"
    data-allow-all-closed="true"
    data-multi-expand="true">
```

in foundation.accordion.js line 104
$('html, body').animate({ scrollTop: offset.top - this.options.deepLinkSmudgeOffset }, this.options.deepLinkSmudgeDelay);

**Comment by DanielRuf** [comment]
Thanks, but I meant an example with the overlapping elements as codepenso we can cover and test this usecase.

**Comment by Lefthandmedia** [comment]
Ah ok
https://codepen.io/Lefthandmedia/pen/qBWLWdy

**Comment by Lefthandmedia** [comment]
Is this issue closed and  fixed or only closed with a 'won't do' ?

**Comment by Lefthandmedia** [comment]
The only thing that needs to happen for this to work is adding '-this.options.deepLinkSmudgeOffset' to line #105 of foundation.accordion.js.
So change
`$('html, body').animate({ scrollTop: offset.top }, this.options.deepLinkSmudgeDelay);`
into
`$('html, body').animate({ scrollTop: offset.top - this.options.deepLinkSmudgeOffset }, this.options.deepLinkSmudgeDelay);`

**Comment by DanielRuf** [comment]
> Is this issue closed and fixed or only closed with a 'won't do' ?

Hi, the issue is still open.

**Comment by DanielRuf** [comment]
> The only thing that needs to happen for this to work is adding '-this.options.deepLinkSmudgeOffset' to line #105 of foundation.accordion.js.

It would be great if you could provide a PR =)

**Comment by DanielRuf** [comment]
> The only thing that needs to happen for this to work is adding '-this.options.deepLinkSmudgeOffset' to line #105 of foundation.accordion.js.

It would be awesome if you could provide a PR =)
