### ISSUE TITLE
Custom Website Download Generates 404

### ISSUE THREAD

**Issue by Lainkai** [foundation/foundation-sites#11826]
## What should happen?

A redirect/download of a customized version of foundation.css.

...

## What happens instead?

When I press the submit button, it leads to a 404. 

![image](https://user-images.githubusercontent.com/15316168/65928687-ecf7b100-e3cc-11e9-9d54-58175c8fd128.png)

...

## Possible Solution

N/A
...

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:
1. Change any one of the colors (or all of them)
![image](https://user-images.githubusercontent.com/15316168/65928735-17e20500-e3cd-11e9-860c-f4cab8a7eed7.png)

2. Press the Download Custom Build button.

## Context

I am trying to build a custom website for a local high school robotics team, and I would like to use our school colors for the primary colors, etc.

**I cannot download our custom file, let alone implement it to our project.**

...

## Your Environment

- Foundation version(s) used: Foundation 6 Complete (all check boxes checked)
- Browser(s) name and version(s): Chrome 77
- Device, Operating System and version: Chrome OS, Windows 10
- Link to your project: N/A (Download website issue)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @Lainkai,

This is a known issue and is often gone after a few minutes. Can you try again?

**Comment by DanielRuf** [comment]
Besides that you can fully customize Foundation Sites using the twmplate generated by the Foundation CLI.

**Comment by razzlepickles** [comment]
I've been seeing this for over a week

**Comment by DanielRuf** [comment]
See https://github.com/foundation/foundation-sites/issues/11095

We can currently not do much.

**Comment by Lainkai** [comment]
Yeah, I have tried all day, and the only time it works is when I leave it with default settings.

**Comment by DanielRuf** [comment]
Ok, this seems to be 100% reproducuble.

We will check this in detail.

**Comment by DanielRuf** [comment]
Ok, this seems to be 100% reproducible.

We will check this in detail.

**Comment by DanielRuf** [comment]
See https://github.com/foundation/node-foundation-customizer/pull/13

**Comment by sashabeep** [comment]
Can't download the build for more than 8 hours using different browsers. Looks like, that customizer thinking that file is already served. Maybe, temp filename generates using some session vars or so?

**Comment by DanielRuf** [comment]
Please see my previous answer.
It is a general bug and we have to deploy the fix.

**Comment by DanielRuf** [comment]
Any updates on this @joeworkman?

**Comment by BlackEagleXV** [comment]
it is still not working, even when deselecting a lot of components. Is there a documented workaround how you can do the same on your own machine?

**Comment by DanielRuf** [comment]
> it is still not working, even when deselecting a lot of components. Is there a documented workaround how you can do the same on your own machine?

We are aware of that.

Yes, you can use https://github.com/foundation/node-foundation-customizer/ which is the same project.

**Comment by DanielRuf** [comment]
> it is still not working, even when deselecting a lot of components. Is there a documented workaround how you can do the same on your own machine?

We are aware of that.

Yes, you can use https://github.com/foundation/node-foundation-customizer/ which is used here.

**Comment by DanielRuf** [comment]
For those who need a working solution: https://foundation-customizer.daniel-ruf.de/sites/download/

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/is-foundation-custom-download-gone/1454/2

**Comment by DanielRuf** [comment]
This is now hosted at https://download.get.foundation/sites/download/
