### ISSUE TITLE
Slow Race to v6.6

### ISSUE THREAD

**Issue by blynnc** [foundation/foundation-sites#11841]
What is missing?

Energy and protein bars during October 1 - 8  2019.

What is wrong now ?
81% 81% 81% 81% .......... milestone to v 6.6
Team members took off to v7 without touch down on v 6.6

Possible Solution

 Ruff in the lead  but  losing ground waiting for Reviews.

[Optional] How has this issue affected you? What are you trying
to accomplish? Providing context helps us come up with a solution
 that is most useful in the real world.

Many of us waiting for v6.6 --- how long does it take to get from 81% to 100% release ?

...

Your Environment
 N/A

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] here are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @blynnc,

thanks for the input but the issues are basically for reporting bugs.
We are aware of the current status and I try to keep this going with the others.

**Comment by DanielRuf** [comment]
> how long does it take to get from 81% to 100% release ?

So far we have no ETA.

**Comment by blynnc** [comment]
&#127875;  !!!!!!

**Comment by DanielRuf** [comment]
Can you please write me on gitter.im or our Foundatiom Slack channel? I am more active there. I check my mails only once per day.

**Comment by DanielRuf** [comment]
@blynnc, can you please write me on gitter.im or our Foundatiom Slack channel? I am more active there. I check my mails only once per day.
