### ISSUE TITLE
[Dropdown] no data-force-follow, forceFollow option, but listed in documentation

### ISSUE THREAD

**Issue by besseddrest** [foundation/foundation-sites#11842]
## Expected Behavior
Clicking an anchor link that toggles a dropdown pane should open the dropdown on the first touch, and follow the link on second touch.
...

## Current Behavior
On first touch, the dropdown is toggled but the browser follows the anchor link to the href value.

...

## Possible Solution
In the Foundation docs, data-force-follow is listed as an option, however, the foundation.dropdown.js file does not have a forceFollow option.

...

How to reproduce:
1. Create an anchor element as a dropdown toggle and dropdown pane
2. add the option `data-force-follow="false"`, or `data-options="forceFollow:false;"` to the dropdown pane
3. View the rendered code on a touch/mobile device or device emulator (I'm using Chrome's Inspector)
4. Click the anchor. It will toggle the dropdown, but also follow the link.

## Context
A user on a mobile/touch device will navigate away from the current page when trying to open the dropdown pane.

...

## Your Environment
- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Chrome 77
- Device, Operating System and version: mobile/touch devices in Chrome Inspector

## Checklist
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @besseddrest,

Thanks for your bug report.

Can you provide a codepen which reproduces this?

I see the option used at https://github.com/foundation/foundation-sites/blob/develop/js/foundation.dropdown.js#L156

**Comment by DanielRuf** [comment]
We have accidentally pushed the docs for the develop branch. This will be available in 6.6.

See https://github.com/foundation/foundation-sites/blob/v6.5.3/js/foundation.dropdown.js vs https://github.com/foundation/foundation-sites/blob/develop/js/foundation.dropdown.js

**Comment by besseddrest** [comment]
@DanielRuf Ahhhhhhh ok. I thought I was going insane. 

Is there an ETA for this release?

**Comment by DanielRuf** [comment]
No ETA for now.

Closing this one as we already have an issue about the wrong docs: https://github.com/foundation/foundation-sites/issues/11824
