### ISSUE TITLE
ERROR:  FAILED TO LOAD RESOURCE min.maps

### ISSUE THREAD

**Issue by blynnc** [foundation/foundation-sites#11844]
What should happen?

These files are not needed. 

 What happens instead?
Failed to load resource.

This is only showing up in Safari (latest version) console logs.

404 (Not Found) (foundation.min.css.map, line 0)
404 (Not Found) (foundation.min.js.map, line 0)

Possible Solution

Maybe something to do with the source dist files ? or download from
https://foundation.zurb.com/sites/download.html/ 

Im seeing this problem reported here
https://foundation.zurb.com/forum/tags/foundation.css.map

what s the definitive fix?

Test Case and/or Steps to Reproduce (for bugs)
 Can't provide one now.

How to reproduce:

1. Using standard Foundation 6.5.3
2. Basic site
3. check console error logs

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi, thanks for reporting this. The build files reference the sourcemaps.

See the last line: https://unpkg.com/browse/foundation-sites@6.5.3/dist/js/foundation.js

**Comment by DanielRuf** [comment]
We write them in general, see https://github.com/foundation/foundation-sites/blob/develop/gulp/tasks/sass.js#L31

**Comment by DanielRuf** [comment]
Related:

https://github.com/foundation/foundation-sites/issues/10997
https://github.com/foundation/foundation-sites/issues/10999
https://github.com/foundation/foundation-sites/pull/11012
https://github.com/foundation/foundation-sites/pull/10998

**Comment by DanielRuf** [comment]
Generally the browser should load the files only when you open the console / dev tools of the browser.

https://blog.praveen.science/avoiding-http-404-for-map-files-when-using-minified-css/
https://apple.stackexchange.com/questions/220526/how-do-i-disable-all-source-mapping-in-safari-devtools
https://superuser.com/questions/667325/how-do-i-disable-source-maps-in-safari
https://css-tricks.com/should-i-use-source-maps-in-production/

**Comment by blynnc** [comment]
Thanks so much for the details! I guess you can call my reaction a "kernel panic" : ).

I fixed the error message by removing
/*# sourceMappingURL=foundation.min.css.map */
from the bottom of the foundation.min.css - 6.5.3 along with the blank line space below it.
and the same for corresponding commented out js
 /*# sourceMappingURL=foundation.min.js.mapfile from the bottom of the foundation.min.js 6.5.3 

Error messages are gone in Safari.
 So - this should be fixed in upcoming release.

**Comment by DanielRuf** [comment]
> So - this should be fixed in upcoming release.

Still, browsers do not load them by default.
If you do not need that you can remove the line.

We will not change the generated files as this is a feature an it is optin.
