### ISSUE TITLE
Re: Mixing frameworks may have unwanted side-effects (and it gets worse)

### ISSUE THREAD

**Issue by salex** [foundation/foundation-sites#11857]
## What is missing?

Foundation working with Rails 6 and their decision to use Webpacker to manage javascript

After finding the solution for the [issue that I closed](https://github.com/foundation/foundation-sites/issues/11840), I proceeded to try a little more Rails 6, webpacker and Foundation. I got one step further, trying to add a top bar. Well it didn't work and after another week of mornings trying to learn more about why it didn't work, I came to the conclusion, that was pointed out in my issue, that :

### Mixing frameworks may have unwanted side-effects

My major problem (using the responsive top-bar example in the docs ) was the hamburger icon would always display initially, the viewport setting just didn't work on load. If I used a link to go to another page, the hamburger went away and things looked fine. A refresh would bring it back the hamburger.

I wasn't the only person having problems with webpacker and foundation ref [stackoverflow question](https://stackoverflow.com/questions/56674961)

I finally bit the bullet and got rid of turbolinks, added a few more things that I found in my searches and everything worked *most of the time*. In Safari, sometimes you'd get the hamburger, some times you don't. With Chrome, you *always* get the hamburger. With Firefox, you rarely get it (opps, loaded new version and just like Chrome).

I decided to post this just to let you know that Rails 6 and webpacker are going to cause you problems until someone figures out the magic way to put it together. Not being an expert in just about everything that is in the mix, this is above my pay grade! 

I've updated my [packdemo code](https://github.com/salex/packdemo) on github and still have my [live demo](http://stevealex.us:4000/) running on a test server. Think I'll take a week off.

I'm sure there are bugs everywhere - Probably even mine. I didn't post this as a bug because, well just because.

...

## What is wrong now ?

...

## Context

...

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Safari, Chrome, Firefox - latest
- Device, Operating System and version: osx, debian, rasberrium

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [ ] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @salex,

thanks for the information and sorry that you face these issues in your project.
We will take this feedback and consider how we can solve it in Foundation v7.

**Comment by DanielRuf** [comment]
Due to having many open issues we have to label the issues for v7 to revisit them later and close them. I hope this is ok for you. Otherwise we would overview.

Thanks for taking the time to find the causes / problems and letting us know.
