### ISSUE TITLE
Accordion is-active default start not working

### ISSUE THREAD

**Issue by nolafs** [foundation/foundation-sites#11858]
## What should happen?

Adding is-active to first element should open the content.

## What happens instead?

Content is not open but the state of the button is set to active. Only opening another item will allow opening the default item set on start.

**Comment by DanielRuf** [comment]
Hi @nolafs,

please use our issue template and provide a reproducible testcase and some more details.

Thank you.

**Comment by nolafs** [comment]
hi DanielRuf,

Here is the code:

,,,
<ul id="oS" class="accordion" data-accordion="j6p594-accordion" data-multi-expand="false" data-update-history="true" role="tablist">
                    
                           <li id="i-0" class="accordion-item is-active" data-accordion-item="">
                               <a href="#" class="accordion-title" aria-controls="7lzgf6-accordion" role="tab" id="i-0-label" aria-expanded="true" aria-selected="true"><i>
                                   <div><svg class="svg-inline--fa fa-check fa-w-16" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="check" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z"></path></svg></div>
                               </i>Paid Media - Planning &amp; Buying</a>
                               <div class="accordion-content" data-tab-content="" role="tabpanel" aria-labelledby="i-0-label" aria-hidden="false" id="7lzgf6-accordion">
                                   Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                               </div>
                           </li>
                    
                           <li id="i-1" class="accordion-item" data-accordion-item="">
                               <a href="#" class="accordion-title" aria-controls="jxld6p-accordion" role="tab" id="i-1-label" aria-expanded="false" aria-selected="false"><i>
                                   <div><svg class="svg-inline--fa fa-check fa-w-16" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="check" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z"></path></svg></div>
                               </i>Legal Services</a>
                               <div class="accordion-content" data-tab-content="" role="tabpanel" aria-labelledby="i-1-label" aria-hidden="true" id="jxld6p-accordion">
                                   Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                               </div>
                           </li>
                    
                           <li id="i-2" class="accordion-item" data-accordion-item="">
                               <a href="#" class="accordion-title" aria-controls="8td8t5-accordion" role="tab" id="i-2-label" aria-expanded="false" aria-selected="false"><i>
                                   <div><svg class="svg-inline--fa fa-check fa-w-16" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="check" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z"></path></svg></div>
                               </i>Creative Services</a>
                               <div class="accordion-content" data-tab-content="" role="tabpanel" aria-labelledby="i-2-label" aria-hidden="true" id="8td8t5-accordion">
                                   Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                               </div>
                           </li>
                    
                           <li id="i-3" class="accordion-item" data-accordion-item="">
                               <a href="#" class="accordion-title" aria-controls="yz5vm4-accordion" role="tab" id="i-3-label" aria-expanded="false" aria-selected="false"><i>
                                   <div><svg class="svg-inline--fa fa-check fa-w-16" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="check" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z"></path></svg></div>
                               </i>Social &amp; Community</a>
                               <div class="accordion-content" data-tab-content="" role="tabpanel" aria-labelledby="i-3-label" aria-hidden="true" id="yz5vm4-accordion">
                                   Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                               </div>
                           </li>
                    
                           <li id="i-4" class="accordion-item" data-accordion-item="">
                               <a href="#" class="accordion-title" aria-controls="qjt614-accordion" role="tab" id="i-4-label" aria-expanded="false" aria-selected="false"><i>
                                   <div><svg class="svg-inline--fa fa-check fa-w-16" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="check" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z"></path></svg></div>
                               </i>Game Evaluation</a>
                               <div class="accordion-content" data-tab-content="" role="tabpanel" aria-labelledby="i-4-label" aria-hidden="true" id="qjt614-accordion">
                                   Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                               </div>
                           </li>
                    
                           <li id="i-5" class="accordion-item" data-accordion-item="">
                               <a href="#" class="accordion-title" aria-controls="0z4u7j-accordion" role="tab" id="i-5-label" aria-expanded="false" aria-selected="false"><i>
                                   <div><svg class="svg-inline--fa fa-check fa-w-16" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="check" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z"></path></svg></div>
                               </i>Event Management &amp; Production</a>
                               <div class="accordion-content" data-tab-content="" role="tabpanel" aria-labelledby="i-5-label" aria-hidden="true" id="0z4u7j-accordion">
                                   Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                               </div>
                           </li>
                    
                    </ul>
'''

Here is the link to my the page:

https://eloquent-curran-2d10a7.netlify.com/services/

Thanks

**Comment by DanielRuf** [comment]
I can not reproduce it on https://codepen.io/DanielRuf/pen/JjjXbrE

Please try to provide a small and isolated reproducible test case.

**Comment by nolafs** [comment]
I already tried this. It works fine isolated. On the page, it fails to add display:block to the accordion-item.

**Comment by DanielRuf** [comment]
Then it may be because of the implementation or version. I will check that if I find the time.

**Comment by DanielRuf** [comment]
Thanks for the clarification.

Then it may be because of the implementation or version. I will check that if I find the time.

**Comment by nolafs** [comment]
ok, seems to work when I do production build. No idea why it doesn't work on my development build.
