### ISSUE TITLE
[Dropdown Menu] Events are camel-cased in the documentation, but not in actual plugin

### ISSUE THREAD

**Issue by besseddrest** [foundation/foundation-sites#11864]
Apologies in advance if this is not the place to report this, but I'm unable to edit this section in the documentation when I forked it.

The documentation has the events for dropdown menu camel cased, however in the JS they aren't.

Also, "dropdown pane" is in the show.zf.dropdownMenu description.

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @besseddrest,

The docs are generated from the `@fire...` annotations.

The currently deployed docs are the wrong ones.

We have accidentally deployed the develop docs which have the new method names.

See https://github.com/foundation/foundation-sites/issues/11824

Closing this one as duplicate.
