### ISSUE TITLE
Foundation type definitions do not match the latest version of JQuery

### ISSUE THREAD

**Issue by tszutu** [foundation/foundation-sites#11868]
## What should happen?
Able to run a project with the latest jQuery version and Foundation 6. 

## What happens instead?

Running into build issues with the type definitions because they are not up to date with the latest jQuery version. 

![image](https://user-images.githubusercontent.com/2660852/67129913-bb485d80-f1b4-11e9-9cc1-35e3e02390c0.png)

## Possible Solution

Update the type definitions to match the latest JQuery type definitions. 

How to reproduce:
1. Create a project with latest foundation 6 branch and any jQuery 3.0+ 
    a. I have tested it other jQuery versions it the issue happened as soon as the I hit 3.0
2. Project will not be built. 

## Context

Run into build errors. I've created a custom foundation-site to match the jQuery type in order for foundation to run properly with my solution. 

I have my solution here:  
https://github.com/tszutu/foundation-sites/commit/96f6d256723e82472e4a30986eab45666bc16660

## Your Environment

- Foundation version(s) used: 6.5.1
~ @types/jquery: 3.3.29

## Checklist

- [ x] I have read and follow the CONTRIBUTING.md document.
- [ x] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi, this is probably a problem with `@types/jquery` in combination with your TypeScript version.

https://www.google.com/search?q=ts2314+typescript+jquery

Please provide a reproducible test case as repo.

The described steps are not sufficient.

Let me know when you have updated the issue description.

Labeling the issue as invalid (missing details) and closing it for now. We will reopen it when we have the required details.
