### ISSUE TITLE
Button Group SCSS file outdated in `npm`?

### ISSUE THREAD

**Issue by proimage** [foundation/foundation-sites#11874]
## What should happen?

When I install `foundation-sites` via `npm install -f foundation-sites`, I would expect to have the latest version of the files. Specifically, I would expect the `node_modules/foundation-sites/scss/components/_button-group.scss` to have the `button-group-no-gaps` mixin, as seen here: https://github.com/foundation/foundation-sites/blob/a79f821c7c94b6d69ec3f3bf851a74af91444b84/scss/components/_button-group.scss#L80

## What happens instead?

I get a version of the `_button-groups.scss` file _without_ the aforementioned mixin.

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
1. In a terminal window, create and browse to a fresh, blank directory.
2. Type `npm install foundation-sites` and press _ENTER_.
3. Once installed, open up `node_modules/foundation-sites/scss/components/_button-group.scss` and go to line ~79 to see the comments that precede the `button-group-expand` mixin (see attached: 
[_button-group.zip](https://github.com/foundation/foundation-sites/files/3747134/_button-group.zip) )

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): (irrelevant)
- Device, Operating System and version: Windows 10 build 1903
- Link to your project: (irrelevant)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @proimage,

the `develop` branch contains changes for Foundation v6.6.

For Foundation v6.5.3 see https://github.com/foundation/foundation-sites/blob/v6.5.3/scss/components/_button-group.scss

**Comment by proimage** [comment]
Okaaaaay, there's no indication (that _I_ can see—perhaps I'm missing it) that the linked file is in a `develop` branch, but I totally get that that's basically subject to the whims of GitHubs's UI'.

However, this is confusing as heck:

![image](https://user-images.githubusercontent.com/1027523/67160335-575e9a00-f358-11e9-8b24-6eac841efd7c.png)

Jus' saying.... ¯\_(ツ)_/¯

**Comment by DanielRuf** [comment]
> We have accidentally pushed the docs for the develop branch. This will be available in 6.6.

https://github.com/foundation/foundation-sites/issues/11842
https://github.com/foundation/foundation-sites/issues/11824

Closing as duplicate.
