### ISSUE TITLE
Change documentation sidebar font family to increase legibility 

### ISSUE THREAD

**Issue by cam424** [foundation/foundation-sites#11895]
## Description
Font awesome's documentation sidebar nav is now Proxima Nova.

## Possible Solution
To improve legibility, I propose changing the font back to Helvetica Neau or some other easier to read typeface.

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @cam424,

Thanks for your issue.

I am not aware that Foundation Sites uses Fontawesome.

Can you clarify what you mean?

**Comment by cam424** [comment]
Sorry Daniel, autocorrect got the best of me. Foundation's documentation sidebar is what I meant!

Again, my apologies!

**Comment by DanielRuf** [comment]
Thanks, I will check this.

**Comment by DanielRuf** [comment]
Thanks for the clarification, I will check this.

**Comment by DanielRuf** [comment]
https://github.com/foundation/foundation-docs/search?utf8=%E2%9C%93&q=proxima&type=

https://github.com/foundation/foundation-docs/blob/34f7beab89610c9a528c46fc6267e92a90a96c93/scss/_typography.scss#L8

I'll have to check what caused this. When was this Helvetica? Maybe I can check a cached version.

**Comment by DanielRuf** [comment]
![image](https://user-images.githubusercontent.com/827205/67744015-aa071880-fa20-11e9-9d5c-a44613900c84.png)

It seems the Proxima Nova font is not loaded in general (as thirdparty resource) but referenced. And I guess you have it installed.

Hm, seems it is still there: https://github.com/foundation/foundation-sites/tree/develop/docs/assets/fonts

But we have removed these styles for the sidebar and other components in the past:
https://github.com/foundation/foundation-sites/blob/develop/docs/assets/scss/docs.scss

When we remove the rule from the foundation-docs repo it will be Robot on my system (Ubuntu), probably Helvetica or Arial on others (inherited from the body):
> font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;

Is this ok? Or should we completely remove the Proxima Nova usage from the docs and other parts?

**Comment by cam424** [comment]
That would be amazing!

**Comment by DanielRuf** [comment]
Hi @cam424,

Thanks for your feedback. Can you give me feedback on the linked PRs? This would be awesome =)

**Comment by cam424** [comment]
Looks good Daniel! Thanks for the quick turn around. Going to close this and keep an eye on the PR.
