### ISSUE TITLE
Responsive Accordion Tabs not re-initiating

### ISSUE THREAD

**Issue by laurenwilliams92** [foundation/foundation-sites#11909]
#What should happen? 

Upon calling reInit - it should take into account any changes to content and re-apply the plugin.

## What happens instead?

The plugin doesn't appear to update and apply to the new content. 

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
1. Manually set new accordiontabs:
new Foundation.ResponsiveAccordionTabs($('#expander-2 .accordion'));
2. Do ajax request which updates the content i.e adds an extra class to the accordion item
3. Call reinit: Foundation.reInit($('#expander-2 .accordion'));

On manual set:
![image](https://user-images.githubusercontent.com/32837730/68466919-3679be00-020d-11ea-8c5c-d315ba76e4f0.png)

On reinit: 
![image](https://user-images.githubusercontent.com/32837730/68466971-4d201500-020d-11ea-90d8-3b5661cc9501.png)

## Context
Trying to change a class within the accordion item dependant on ajax response - which applies a :after to the element.

## Your Environment
- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Chrome 78 & Firefox 70

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @laurenwilliams92,

thanks for reporting this.
Can you also provide a codepen so we can directly reproduce and check this?

Or a small repository as reproducible testcase? This would be very helpful for us.

**Comment by laurenwilliams92** [comment]
> Hi @laurenwilliams92,
> 
> thanks for reporting this.
> Can you also provide a codepen so we can directly reproduce and check this?
> 
> Or a small repository as reproducible testcase? This would be very helpful for us.

Sorry I'm unable to provide this. 

We are using vue.js as well which consists of a lot of data - codepen and jsfiddle make it impossible to get a working replica. I can possibly give you a few code snippets for the specific areas.

updated() {
            console.log('updated');
            if(this.accordionMenu) {
                console.log('should - reinit');
                Foundation.reInit($('#expander-' + this.activeEnrolment.id + ' .accordion'));
            } else {
                this.accordionMenu = new Foundation.ResponsiveAccordionTabs($('#expander-' + this.activeEnrolment.id + ' .accordion'));
            }
        },

**Comment by DanielRuf** [comment]
> We are using vue.js as well which consists of a lot of data - codepen and jsfiddle make it impossible to get a working replica. I can possibly give you a few code snippets for the specific areas.

What about https://codesandbox.io/?

**Comment by SassNinja** [comment]
> We are using vue.js as well which consists of a lot of data

I think you don't need Vue to reproduce the issue because (according to what you said) it's rather about changing content of an already initialized instance of ResponsiveAccordionTabs and calling the reInit method

Should be possible to mock this without Vue
(we just need to reproduce the issue, not your exact setup if it's not relevant for the issue)

**Comment by laurenwilliams92** [comment]
Managed to get this working on codesanbox.

https://codesandbox.io/s/vue-template-2cgdr

**Comment by laurenwilliams92** [comment]
Bump... has anyone had a chance to look at this yet? It's currently a major blocker for myself.

**Comment by SassNinja** [comment]
@laurenwilliams92 I'm unable to reproduce the issue with your codesandbox or rather cannot reproduce the state shown in your sceenshots

please provide more details (e.g. when exactly does the problem occur)

**Comment by laurenwilliams92** [comment]
@SassNinja If you click on the first yellow dot, it shows correctly. 

If you then click on the second yellow dot you will notice that 'Lick 01' appears out of place.

As mentioned before when the length of the content changes, it does not reinit properly.


See lines 3216 - updated() and showExpander() methods

**Comment by laurenwilliams92** [comment]
> Bump... has anyone had a chance to look at this yet? It's currently a major blocker for myself.

**Comment by DanielRuf** [comment]
We did not yet have the needed time to take a closer look.

**Comment by laurenwilliams92** [comment]
@DanielRuf No worries. I was actually able to fix this myself, it seemed to be vue.js issue.

For anyone else stumbling across this, I added a :key to my element that the tabs were attached too and incremented this after my ajax call. This then forced Vue to update the whole thing.
