### ISSUE TITLE
Latest changes from github are not reflected in npm registery. 

### ISSUE THREAD

**Issue by sandymantri** [foundation/foundation-sites#11911]
## Description
Hey,

I tried to install foundation sites using `npm install foundation-sites` command. However, I could not see some of the fixes getting reflected there. Specifically, the if-else condition in [this scss file](https://github.com/foundation/foundation-sites/blob/d4bc558efaec9d42f4536228ef8fef0d131f6930/scss/typography/_print.scss#L24 ) is not present and causing black and white print all the time. 

Not sure if there is already an issue logged for this if yes please point me to that. Appreciate your help.

## Possible Solution

Publishing package to npm repository again may help.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @sandymantri,

you can see the code of the latest release on https://github.com/foundation/foundation-sites/tree/v6.5.3

Current develop branch contains changes for the upcoming v6.6 release.

**Comment by sandymantri** [comment]
Hi @DanielRuf 
But these changes are in the master branch too but still not in https://github.com/foundation/foundation-sites/tree/v6.5.3 is this expected?

**Comment by DanielRuf** [comment]
Yes, this is expected.
