### ISSUE TITLE
foundation.core.js:173 TypeError: Cannot read property 'plugin' of undefined

### ISSUE THREAD

**Issue by bpollardFlow** [foundation/foundation-sites#11913]
## What should happen?
We shouldn't get an error in the browser console.
...

## What happens instead?
We get this error in the browser console.
foundation.core.js:173 TypeError: Cannot read property 'plugin' of undefined
...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. It happens on all pages (since all pages have the foundation reference).
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Chrome 78.0.3904.97
- Device, Operating System and version: Windows 10
- Link to your project: 
https://www.flowauto.com

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @bpollardFlow,

Thanks for reporting this.

Can you provide a codepen as reproducible testcase?

**Comment by DanielRuf** [comment]
>     1. It happens on all pages (since all pages have the foundation reference).

I can not reproduce this in Firefox. We need an isolated reproducible testcase.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
