### ISSUE TITLE
$accordionmenu-arrow-size not used in all places

### ISSUE THREAD

**Issue by BlakeHancock** [foundation/foundation-sites#11914]
## What should happen?
Changing $accordionmenu-arrow-size should change the accordion menu arrow size.

## What happens instead?
Nothing, stays as 6px always.

## Possible Solution
[Replace the 6px on this line with $accordionmenu-arrow-size](
https://github.com/foundation/foundation-sites/blob/develop/scss/components/_accordion-menu.scss#L157)

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:
1. Change the value of $accordionmenu-arrow-size
2. Set up accordion menu with sub items and data-submenu-toggle="true"
3. See that arrow size doesn't change.

## Your Environment
Latest foundation release 6.5.3

## Checklist
- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @BlakeHancock,

thanks for spotting this.
Do you want to provide a PR to fix this? That would be awesome.

**Comment by BlakeHancock** [comment]
Sure, I won't be able to get to it though til Saturday/Sunday.
