### ISSUE TITLE
Custom download - error "ENOENT: no such file or directory ..."

### ISSUE THREAD

**Issue by mrengy** [foundation/foundation-sites#11918]
## What should happen?
On https://foundation.zurb.com/sites/download.html/#customizeFoundation , when choosing options and clicking "download custom build", the zip should download
...

## What happens instead?
otherwise blank page shows an error of "ENOENT: no such file or directory, stat '/tmp/tmp.6.5.1.1a3c3740ed4d405350aba3b87dd5ade3.zip' "

<img width="1109" alt="2019-11-23_1002" src="https://user-images.githubusercontent.com/2223603/69480923-0ec45180-0dda-11ea-8a45-aea6a91a2bc9.png">

...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. go to https://foundation.zurb.com/sites/download.html/#customizeFoundation
2. choose these options : 
![Screenshot_2019-11-23 Download Foundation for Sites](https://user-images.githubusercontent.com/2223603/69480872-60201100-0dd9-11ea-884e-53c5bc66953c.png)

3. click "download custom build"

## Context

Trying to download a minimal build with the components shown to get started on a project
...

## Your Environment

- Foundation version(s) used: 6
- Browser(s) name and version(s): Firefox 70.0.1 (64-bit)
- Device, Operating System and version: Mac OS 10.14.6
- Link to your project: 

## Checklist

- [X ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one. - there are #10826 and #10826 but both are closed . What should I do in this case? Contributing.md doesn't provide guidance for that case, so I'm creating a new issue.
- [ X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @mrengy,

Please see https://github.com/foundation/foundation-sites/issues/11826

Closing as duplicate.
