### ISSUE TITLE
Sticky not working anymore on 6.6.0 

### ISSUE THREAD

**Issue by smokingweb** [foundation/foundation-sites#11928]
## What should happen?

Sticky component should work

## What happens instead?

Sticky component does not work at all, also on the official doc related page 

## Possible Solution

don't know

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 
https://get.foundation/sites/docs/sticky.html

How to reproduce:
1. simply scroll the page

## Context

...

## Your Environment

- Foundation version(s) used: 6.6.0
- Browser(s) name and version(s): chrome, brave
- Device, Operating System and version: OSX 10.13.6
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by joeworkman** [comment]
This has already been fixed in #11924
