### ISSUE TITLE
Buttons within a Button Group do not obey the button sizes set in _settings.scss

### ISSUE THREAD

**Issue by joshtipton28** [foundation/foundation-sites#11923]
## What should happen?
When applying a class such as <a class="button small">Link</a> within a Button Group, it should inherit the small button sizing set out in _settings.scss

## What happens instead?
The small button size is overridden by the standard button size.

## Possible Solution
Apply the button sizing to button groups.

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
1. Create a button group
2. Inside the button group, place a link or button with the class"button small"

## Your Environment

- Foundation version(s) used: 6.5.0
- Browser(s) name and version(s): Chrome
- Device, Operating System and version: Windows 10

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @joshtipton28,

Please provide a reproducible testcase as codepen. That would be very helpful.

**Comment by joshtipton28** [comment]
https://codepen.io/joshtipton28/pen/VwYYXeM

**Comment by joshtipton28** [comment]
Nevermind, I see that the sizing is supposed to be added to the button-group, not the button. https://foundation.zurb.com/sites/docs/button-group.html
