### ISSUE TITLE
theme update lost site help! 

### ISSUE THREAD

**Issue by KendallHunter** [foundation/foundation-sites#11921]
## What should happen? My site should update and still be visible

...

## What happens instead? I updated my site, and apparently foundation press master, and lost my homepage graphics and bluehost is saying it's an issue with the theme, not something they can help with. 

...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by KendallHunter** [comment]
Bluehost has told me  to contact the theme vendor regarding the issue and ask them the requirements of the theme so that we can help you . CAn you please help. Thanks

**Comment by DanielRuf** [comment]
Closing as duplicate and this is the wrong project.
