### ISSUE TITLE
The link to "older versions" of the documentation is broken

### ISSUE THREAD

**Issue by kcwms** [foundation/foundation-sites#11926]
## Description

The link to "Older Versions" reports Page Not Found
https://get.foundation/sites/docs/v/5.5.3/index.html
![Screenshot_20191206_203429](https://user-images.githubusercontent.com/29052675/70366967-baa17e80-1869-11ea-995e-050d0e0d5f32.png)

...

## Possible Solution

Fix the broken link??
...

## Checklist

- [x ] I have read and follow the CONTRIBUTING.md document.
- [ x] There are no other issues similar to this one.
- [ x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @kcwms,

Thanks for reporting this. The new website is still WIP and we are aware of it.

**Comment by kcwms** [comment]
@DanielRuf thanks for the feedback. 

I know this is an old question, but my new employer has standardized on v5.*.... Is there a way i can get the old docs? github? pdf?

The solution in this [thread](https://foundation.zurb.com/forum/posts/24927-can-i-get-the-foundation-docs-offline) doesn't work as the repo no longer exists or I don't have access.

**Comment by joeworkman** [comment]
We are working on getting the v5 docs online. Thanks for your patience.

**Comment by DanielRuf** [comment]
https://github.com/foundation/foundation-docs still exists. Also there is still the old tag / release at https://github.com/foundation/foundation-sites

You can either use Zeal or Dash (only macOS) to use the old docs even offline.

Also see https://foundation.discourse.group/t/new-website-feedback/41

**Comment by DanielRuf** [comment]
See https://get.foundation/sites/docs-v5/

Please let us know at https://foundation.discourse.group/t/new-website-feedback/41 if you miss something.
