### ISSUE TITLE
Sticky Top Bar not working after 6.5.3

### ISSUE THREAD

**Issue by ecabuk** [foundation/foundation-sites#11924]
## What should happen?

Top bar should be sticky when page scrolled.

## What happens instead?

Nothing.

## Test Case and/or Steps to Reproduce (for bugs)

I was following to tutorials on the documentation and I couldn't manage to work sticky top bar. Then I downgraded 6.4.3 and it started to work.

Here is the test case, I only changed the version numbers.

Foundation 6.4.3 (Working)

https://codepen.io/ecabuk/pen/JjoYNMq

Foundation 6.6.0 (Not working)

https://codepen.io/ecabuk/pen/LYEpyew

**Comment by DanielRuf** [comment]
6.5.3:

https://codepen.io/DanielRuf/pen/PowPmrj

**Comment by DanielRuf** [comment]
Seems to work here: https://codepen.io/DanielRuf/pen/KKwdmOx?editors=1010

**Comment by DanielRuf** [comment]
Works here too:

https://codepen.io/DanielRuf/pen/XWJmgWL

**Comment by DanielRuf** [comment]
These are different:

https://cdn.jsdelivr.net/npm/foundation-sites@6.6.0/dist/js/foundation.min.js
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.0/js/foundation.min.js

The Cloudflare version works.

**Comment by DanielRuf** [comment]
Ugh, this is 6.5.3: https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.0/js/foundation.min.js

cc @rafibomb @joeworkman

**Comment by DanielRuf** [comment]
Found the culprit using `git bisect`.

```
git bisect bad
3fb505600fa8e61e7ef76c5f6b8b999650f99192 is the first bad commit
commit 3fb505600fa8e61e7ef76c5f6b8b999650f99192
Author: Nicolas Coden <nicolas@ncoden.fr>
Date:   Mon Aug 6 23:55:30 2018 +0200

    fix: validate "MediaQuery.is()" input and returns an error for invalid modifiers

 js/foundation.util.mediaQuery.js | 21 +++++++++++++++------
 1 file changed, 15 insertions(+), 6 deletions(-)
```

**Comment by DanielRuf** [comment]
Got this error:

```
Error: 
      invalid breakpoint passed to MediaQuery.is().
      Expected a breakpoint breakpoint name formatted like "<size> <modifier>", got "medium".
```

**Comment by kevinmu17** [comment]
Updated to 6.6.1 but the problem is still here...

**Comment by DanielRuf** [comment]
Probably some cache.

**Comment by guyvanbael** [comment]
using 6.6.1 but issue is still there.
@kevinmu17  what file did you do your changes in?

**Comment by DanielRuf** [comment]
@guyvanbael please provide the URL of the file that you have sued. On cdnjs the version 6.6.1 contains the code of 6.5.3.

**Comment by guyvanbael** [comment]
@DanielRuf my project was created using the cli. 
`<div data-sticky data-options="stickyOn: small; marginTop:1;" style="width:100%;" id="pageStart">`
It seems to work when marginTop is set to 1, but then you have a margin of course. So i worked around it by adding an id and setting margin-top to 0
