### ISSUE TITLE
[Equalizer] Not working in Foundation 6.6

### ISSUE THREAD

**Issue by amygilbert** [foundation/foundation-sites#11934]
## What should happen?
Using Equalizer plug-in, cards should be the same height.
...

## What happens instead?
Equalizer plug-in has no effect on card height
...

## Possible Solution

Not a solution but I did notice using the browser DOM inspector that the inline style added by js was height: auto in 6.6, while it was height: 369px in 6.5.3. See codepen's below
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 
Foundation 6.5.3: https://codepen.io/amygilbert/pen/abzNMyx
Foundation 6.6: https://codepen.io/amygilbert/pen/zYxqbEe

How to reproduce:
See test cases above

## Context

My site makes extensive use of Equalizer and Cards. I can't upgrade to 6.6 until this bug is fixed
...

## Your Environment

- Foundation version(s) used: 6.5.3 and 6.6
- Browser(s) name and version(s): Google Chrome Version 79.0.3945.79 (Official Build) (64-bit) and Firefox Version 71.0 (64-bit)
- Device, Operating System and version: Windows 10 Pro version 1909
- Link to your project: https://phoenixsoftware.com/

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @amygilbert,

thanks for reporting this. We already have issues about this. Please check next time if there is a relevant issue =)

See https://github.com/foundation/foundation-sites/issues/11933

**Comment by amygilbert** [comment]
Sorry about that. I did do a search but I was only looking at open issues (the default). I'll remove the filter next time. New to this.

**Comment by DanielRuf** [comment]
No problem.

GitHub has a new feature to show relevant issues when you create one. You should be able to see it there.

**Comment by amygilbert** [comment]
I used that but only includes open issues. I gave them some feedback that you should be able to change the scope.

**Comment by DanielRuf** [comment]
I see the following when I create a new issue:

![Screenshot_20191211-195421](https://user-images.githubusercontent.com/827205/70650787-fd8b9980-1c4f-11ea-8697-e5a740aeada3.jpg)
