### ISSUE TITLE
Equalizer doesn't seem to work anymore

### ISSUE THREAD

**Issue by motiejuss** [foundation/foundation-sites#11933]
## What should happen?

Callout heights should equalize. Doesn't seem to work anymore after Foundation 6.6.0 upgrade. 

## What happens instead?

They don't

## Possible Solution

Add data-equalize-by-row="true"

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://get.foundation/sites/docs/equalizer.html

**Comment by DanielRuf** [comment]
Hi @motiejuss,

thanks for reporting this.
I think this should be fixed by https://github.com/foundation/foundation-sites/pull/11925

I will test this now.

Please use the issue template next time.

**Comment by DanielRuf** [comment]
Hi @motiejuss,

thanks for reporting this.
I think this should be fixed by https://github.com/foundation/foundation-sites/pull/11925

I will test this now.

Please also use the issue template next time.

**Comment by DanielRuf** [comment]
Yes this is fixed by my PR:

![image](https://user-images.githubusercontent.com/827205/70619941-4888bb00-1c16-11ea-9aa2-587d6006fc33.png)

We already have other reports about this so I will close this one here.

Thanks for letting us know.
