### ISSUE TITLE
Unable to find joyride in 6+ version

### ISSUE THREAD

**Issue by vimalnair007** [foundation/foundation-sites#11939]
## What should happen?

We are currently using foundation 4 and upgrading to latest(6.6.0) but one of key feature foundation.joyride is missing after 6 upgrade.
I did investigated on the history and found that some sources said it to be ready and released as part of 6.2 but never released. No conclusion found anywhere.

Please share resolution on this and alternatives if any ( Posting this here for help since Zurb foundation forum not allowing new help queries ).

I really appreciate getting any response on this from anyone.

**Comment by DanielRuf** [comment]
Hi @vimalnair007,

It was extracted from Foundation and it is a standalone jQuery plugin.

https://github.com/zurb/joyride

**Comment by DanielRuf** [comment]
The new forum is at https://foundation.discourse.group/.

**Comment by vimalnair007** [comment]
@DanielRuf Thanks for the quick reply :)

Yes i was able to find this and trying it out with foundation 6.6.0.

But it looks like this repository is not maintained. Would you suggest to use this?

**Comment by DanielRuf** [comment]
2 years: https://github.com/zurb/joyride/commits/master

I can not say much, never used it.
