### ISSUE TITLE
SOLUTION for gulpfile.js warning message re Autoprefixer browsers option

### ISSUE THREAD

**Issue by ITZAP** [foundation/foundation-sites#11941]
**This is a SOLUTION to the previous Issue #11780 I posted in June 2019 regarding:**

**gulpfile.js** | Replace Autoprefixer browsers option to Browserslist config

## What is missing?

Using the **Foundation CLI** command "foundation new", download latest ZURB Foundation **v6.6.1**; the Basic Web Template with SASS compiler for Windows 10. (Very good, many thanks for your excellent work!)

In the **project root folder** we then get the usual **gulpfile.js** file, which is run upon entering the console command "**foundation build**" or "**foundation watch**", resulting in the "**app.css**" file being compiled and saved into the "css" folder.

Open **gulpfile.js** and take note that **Line 19 still says**:
`autoprefixer({ browsers: ['last 2 versions', 'ie >= 9'] })`
...

## What is wrong now ?

That autoprefixer line produces the Warning Message mentioned previously in Issue #11780

> Replace Autoprefixer browsers option to Browserslist config.
> Use browserslist key in package.json or .browserslistrc file.

...

## Possible Solution

(1) In **gulpfile.js**, change Line 19 to simply read:
`autoprefixer()`

(2) In the **project root folder**, create a new plain text file and save it with the filename "**.browserslistrc**"
Note there is a DOT in front of that filename.
Add this text content to that file:

(hash symbol) Browserslist settings to produce CSS supported by these Browsers
(greater than symbol) 1%
last 2 versions
ie >= 9
...

This file should be **distributed as standard** in the Foundation project fileset.

For further details about other browser option settings available, [see here >>](https://github.com/browserslist/browserslist)
## Context

NOW when you enter the console command "**foundation build**" or "**foundation watch**" your CSS file will be compiled perfectly, **WITHOUT any Warning message** whatsoever.
...

## Your Environment

- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): Google Chrome, Firefox, Microsoft Edge, Safari.
- Device, Operating System and version: Windows 10 Desktop PC.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @ITZAP,

Thanks for reporting this. I think we already have issues and a PR for this.

You can safely ignore this for now, it is just a warning.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
