### ISSUE TITLE
Reveal animation in doesn't work in 6.6.1

### ISSUE THREAD

**Issue by Lazerproof** [foundation/foundation-sites#11943]
## What should happen?

Reveal opening should be animation with animation that set in a data attribute.

## What happens instead?

Only reveal closing is animated. 

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

https://jsfiddle.net/fxrwdvbe/ - 6.6.0 works
https://jsfiddle.net/L9tvkg07/ - 6.6.1 doesn't work

## Your Environment

- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): Chrome 78.0.3904.108
- Device, Operating System and version: Win 10 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @Lazerproof,

Thanks for reporting this.
Can you provide codepen links instead of jsfiddle? That would be very helpful.

**Comment by DanielRuf** [comment]
In general your 6.6.0 version is in fact 6.5.3, see https://github.com/cdnjs/cdnjs/issues/13636

That's why we do not recommend cdnjs (you can try unpkg).

**Comment by vimalnair007** [comment]
Facing same problem after upgrading to 6.6.1!

**Comment by DanielRuf** [comment]
Hi @vimalnair007,

can you provide a codepen which we can use as testcase? That would be awesome.

**Comment by DanielRuf** [comment]
I found the culprit using `git bisect`.

It seems the code was needed here but lacked a proper comment.
c9b7c7a3f4b517ef6e688886e503e2327d2f17ad

See also https://gist.github.com/paulirish/5d52fb081b3570c81e3a

**Comment by vimalnair007** [comment]
@DanielRuf I tested your fix by manually adding changes to foundation.min.js and animation working as expected on reveal.

Can you please add this changes to dist files as well?

Thank you for the fix and expecting PR to be merged soon.

**Comment by DanielRuf** [comment]
> Can you please add this changes to dist files as well?

dist files are generally not updated in a PR. If needed I can provide patched dist versions.

We update dist files on prepublish / prepare.

**Comment by DanielRuf** [comment]
Depending on your project you can use `git apply`, `patch` or `[patch-package](https://npmjs.com/patch-package)] to apply the patches.

**Comment by DanielRuf** [comment]
Depending on your project you can use `git apply`, `patch` or [`patch-package`](https://npmjs.com/patch-package) to apply the patches.

**Comment by vimalnair007** [comment]
Thanks for the information. Its okay, i have applied it manually for now in my project - hope it will not cause any problem. I wanted dist files in repo with final changes and prevent adding manual fix to keep remote and local files in sync.

I hope your changes will be part of next patch release dist after it is merged.

**Comment by DanielRuf** [comment]
> I hope your changes will be part of next patch release dist after it is merged.

Yes, this is planned for the next patch release.

cc @joeworkman

**Comment by tlatsas** [comment]
Thank you for the fix! Any rough idea when the next patch version is expected?

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/reveal-animation-in-bug/1780/2
