### ISSUE TITLE
Unable to import specific scss files to main.scss 

### ISSUE THREAD

**Issue by vimalnair007** [foundation/foundation-sites#11947]
## What should happen?

I'm working on upgrading foundation 4.2.3 to latest 6.6.1 and facing issue while importing specific scss file in main.scss.

As per 4.2.3 version we used the following scss files in main.scss files and it used to import in target main.css file as expected,

```
// Zurb Foundation framework 4.2.3
@import "foundation/variables";
@import "foundation/components/global";
@import "foundation/components/grid";

```

## What happens instead?

When i import the same in 6.6.1 version, target main.css file generated will not have any data converted from listed scss files. I updated the directory structure as per latest version.

```
// Zurb Foundation framework 6.6.1
@import "foundation/util/util";
@import "foundation/global";
@import "foundation/grid/grid";

```
Just to catch the error i emptied the entire main.scss file and added only above three lines and ran the below which resulted in empty main.css,

`/usr/bin/sass --no-cache main.scss main.css
`

Looking for inputs on whether is there any particular order to import selected scss files in latest version or what would be causing this problem.

Any help on this is really appreciated.

**Comment by DanielRuf** [comment]
Hi @vimalnair007,

this is a huge step, from 4 to 6.

We have changed many things.
Please take a look at https://github.com/foundation/foundation-zurb-template/blob/master/src/assets/scss/app.scss

**Comment by DanielRuf** [comment]
And you probably have not these: https://github.com/foundation/foundation-sites/blob/develop/scss/foundation.scss#L9-L16

Best is to use one of the current templates and creating a new project. We have no migration guide for 5 => 6 afaik.

**Comment by vimalnair007** [comment]
@DanielRuf Thanks for the details. 

Yes i agree, it involve huge changes considering upgrade from 4 to 6. But Mainly we are using foundation for reveal plugin only.

And css for reveal modal we have customized as per our project so i am not importing it from scss files. Though i wanted to import grids scss which i am unable to when i pass it as mentioned above.

**Comment by vimalnair007** [comment]
Basically i want CSS to include only this feature https://get.foundation/sites/docs/grid.html

**Comment by DanielRuf** [comment]
Well, the vendor files are at least required. Some files are also required for the grid file. You should be able to remone file by file to see which are really required, including mixins and functions.

**Comment by DanielRuf** [comment]
Well, the vendor files are at least required. Some files are also required for the grid file. You should be able to remove file by file to see which are really required, including mixins and functions.

**Comment by vimalnair007** [comment]
Sure will work on that.

Thanks for sharing inputs.

**Comment by DanielRuf** [comment]
Hib@vimalnair007,

did you find a working solution?

**Comment by vimalnair007** [comment]
@DanielRuf , I did not find importing with scss files. Since we are using very limited feature from foundation we picked only limited css data to main.css file and modified as per our need. This is work around solution only.

**Comment by DanielRuf** [comment]
Ok, because you closed the issue without further comment.
