### ISSUE TITLE
License text or copyright notice(s) missing in dist source files

### ISSUE THREAD

**Issue by vimalnair007** [foundation/foundation-sites#11950]
## What is missing?
As we are upgrading from foundation 4 to 6, we had to get 3rd party library reviewed from approval team. But this was rejected with following comment,

"License text or copyright notice(s) missing: The JavaScript files -- both standard and minified -- are missing a copyright notice and license. Use of this may result in copyright infringement."

As i have noticed till v5.5.3 we had license and copyright details available in source files.

## What is wrong now ?
License text or copyright notice(s) missing in dist and source files

## Possible Solution
License details needs to be added as part of dist files.

Please share your opinion on this.

**Comment by DanielRuf** [comment]
> Use of this may result in copyright infringement.

This is not completely true.
We use the MIT license and use an extra LICENSE file and the `license` field in package.json.

Some files like the unminified dist css file contain the notice.

You are just required to preserve the notice where it is (if we have it in files). But not explicitely add it afaik.

https://choosealicense.com/licenses/mit/

**Comment by vimalnair007** [comment]
Hi @DanielRuf , Any inputs?

**Comment by DanielRuf** [comment]
Please keep in mind that we have holidays here in Germany.

**Comment by DanielRuf** [comment]
Closing as this might be changed / fixed in the future. We will track this in https://github.com/foundation/foundation-sites/issues/11675
