### ISSUE TITLE
SCSS Settings for skipping rendering elements

### ISSUE THREAD

**Issue by wesselbaum** [foundation/foundation-sites#11958]
## Expected Behavior

In Settings I would like to have a possibility to not style an element entirely. 
Example: 
I would like to style the hr completely my way. Before rewriting all the foundation styles I would like to specify not rendering it in the settings.

## Current Behavior

No possibility to disable single styles

## Possible Solution

Providing something like following in the settings:
`$hr-render: false;`

## Test Case and/or Steps to Reproduce (for bugs)

...

## Context

...

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): all
- Device, Operating System and version: all
- Link to your project: -

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @wesselbaum,

So far you can only clone and remove `import` statements.

Adding this feature would be too much work.

I don't think that is supported by any frontend framework.

**Comment by DanielRuf** [comment]
Hi @wesselbaum,

So far you can only clone and remove `import` statements.

Adding this feature would be too much work.

I don't think that this is supported by any frontend framework.

**Comment by wesselbaum** [comment]
Although I agree with the amount of work, wouldn't it be a nice feature to take a closer look at?
The `import` path is a rabit hole and staying up to date gets a much harder task.

**Comment by DanielRuf** [comment]
As it's a complete framework and nothing that is needed by most I don't think that this is really needed.

I see no real use cases and the needed effort outweighs the possible benefits.

**Comment by wesselbaum** [comment]
You may be right. The data and work savings would be minimal. 
Thank you for the explanations!

**Comment by DanielRuf** [comment]
You might want to apply `initial` values in some cases:

https://developer.mozilla.org/en/docs/Web/CSS/initial

Also tools like `uncss`, `purgecss` and so on could be helpful.

**Comment by DanielRuf** [comment]
You might want to apply `initial` values in some cases, maybe combined with `all`:

https://developer.mozilla.org/en/docs/Web/CSS/initial

https://caniuse.com/#feat=css-all

Also tools like `uncss`, `purgecss` and so on could be helpful.
