### ISSUE TITLE
Foundation grid system does not work at all

### ISSUE THREAD

**Issue by howsendrag** [foundation/foundation-sites#11968]
Hi. I'm new to foundation. I downloaded it and used the foundation's template. So, buttons and other things works correctly, but I have some problems with grid system; I copy the code samples, but still not working.
This is my code:

![Untitled](https://user-images.githubusercontent.com/59917308/72429459-d93a4580-3744-11ea-81a9-8ed6b0cd0ba8.png)

**Comment by DanielRuf** [comment]
Hi @howsendrag,
the current default grid is the XY grid.

https://get.foundation/sites/docs/xy-grid.html

> XY grid is the default Foundation grid. It is present by default in foundation.css of CDN link or package managers.

It uses `grid-x` and `cell`:
https://get.foundation/sites/docs/xy-grid.html#basics

From where exactly did you copy the examples?
I think they might still use the old flex grid.

**Comment by howsendrag** [comment]
> Hi @howsendrag,
> the current default grid is the XY grid.
> 
> https://get.foundation/sites/docs/xy-grid.html
> 
> > XY grid is the default Foundation grid. It is present by default in foundation.css of CDN link or package managers.
> 
> It uses `grid-x` and `cell`:
> https://get.foundation/sites/docs/xy-grid.html#basics
> 
> From where exactly did you copy the examples?
> I think they might still use the old flex grid.

I copied from the foundation docs. I downloaded the foundation with default settings. Do you mean I should use "cells" instead of "columns"? Right?

**Comment by DanielRuf** [comment]
> I copied from the foundation docs

Please provide the exact URL =)

> Do you mean I should use "cells" instead of "columns"? Right?

Exactly. This is mentioned in the docs for the grid.

**Comment by howsendrag** [comment]
Link: https://get.foundation/sites/docs/#
Thanks a lot for your help 🤘🏻🖤

**Comment by DanielRuf** [comment]
I don't see the mentioned examples or code there.

**Comment by DanielRuf** [comment]
Closing as the URL does not show the mentioned code there.
