### ISSUE TITLE
select:not([multiple]) overwrites default selectors

### ISSUE THREAD

**Issue by kimek** [foundation/foundation-sites#11969]
## What should happen?
Previous styling for select tag using selectors like  `.randomClass select` or `select`  should apply padding too.

## What happens instead?

select:not([multiple]) overwrites select, even .randomClass select 

## Possible Solution
Replace 
```
select:not([multiple]) {
    padding-top: 0;
    padding-bottom: 0;
}
```
with
```
select:not([multiple]) {
    line-height: 1;
}
```

**Comment by DanielRuf** [comment]
Hi @kimek,

please use our issue template and provide a codepen as reproducible testcase.

**Comment by DanielRuf** [comment]
Closing as the issue does not follow our issue template.

Please add the required information and we will reopen it.
