### ISSUE TITLE
.hide-for-small-only and related visibility classes always hide for print media

### ISSUE THREAD

**Issue by akaspick** [foundation/foundation-sites#11961]
## What should happen?
.hide-for-small-only should show content when printing.  .hide-for-print controls the visibility of content when printing.
...

## What happens instead?
.hide-for-small-only hides content when printing.

...

## Possible Solution
In foundation.css:

```
@media print, screen and (max-width: 39.99875em) {
  .hide-for-small-only {
    display: none !important; } }
```
Remove print in the @media list.

...

How to reproduce:
1. Add .hide-for-small-only to an element
2. Show a print preview
3. The element with .hide-for-small-only is hidden

...

## Your Environment
- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): Firefox
- Device, Operating System and version: Max OSX

**Comment by akaspick** [comment]
Is this a bug or is this done on purpose for some reason I'm unaware of?  I see no reason why .hide-for-small-only (and related classes) would always hide when printing when .hide-for-print is supposed to take care of that behavior.

**Comment by DanielRuf** [comment]
Afaik we have a setting in the sass version which defines the print breakpoint.

Also related:

https://github.com/foundation/foundation-sites/pull/10979

**Comment by DanielRuf** [comment]
But this is correct and not a bug.

**Comment by DanielRuf** [comment]
Afaik we have a setting in the sass version which defines the print breakpoint.

Also related:

https://github.com/foundation/foundation-sites/pull/10979

But this is correct and not a bug.

`.hide-for-print` is a helper class to conditionally hide elements when printing. Like galeries or other elements.

**Comment by akaspick** [comment]
@DanielRuf So to clarify, `.hide-for-small-only` is always supposed hide elements when printing?  I agree, `.hide-for-print` should always hide when printing, but what's what's the rationale to make `.hide-for-small-only` always hide when printing as well?

**Comment by DanielRuf** [comment]
Exactly. We often overwrote it in projects with `!important`.

**Comment by akaspick** [comment]
@DanielRuf So what's the recommended way to conditionally hide elements depending on screen size, but always show them when printing?

The current behavior for `.hide-for-small-only` just doesn't seem to make sense to me.

In the following example: https://jsfiddle.net/y2w0r1am/1/ the header `<h1 class="hide-for-large-only">Test</h1>` is shown (the output area is small so the header is shown).  Right click the output frame and do a print preview and the `h1` tag is hidden.  Why?

**Comment by DanielRuf** [comment]
a `show-for-print` class with `display: ... !important`. We have no reset afaik.

**Comment by DanielRuf** [comment]
See https://github.com/foundation/foundation-sites/pull/10979#issuecomment-373959270

**Comment by DanielRuf** [comment]
And also the comments: https://github.com/foundation/foundation-sites/pull/10979/files

**Comment by DanielRuf** [comment]
Currently I see no bug / issue with this.
The comment is also quite clear: https://github.com/foundation/foundation-sites/blob/develop/scss/util/_breakpoint.scss#L30

**Comment by akaspick** [comment]
@DanielRuf Ok, fair enough, the scss is documented with the behavior, but the site docs mention nothing regarding print results for the visibility classes... https://get.foundation/sites/docs/visibility.html

So `$print-breakpoint` appears to be what I need to modify, but if I want to include the `small` breakpoint in print, there's nothing smaller than that to specify; `$print-breakpoint: null;` doesn't work.

**Comment by akaspick** [comment]
@DanielRuf I've changed my code to use `.show-for-medium` instead and I get the desired behavior.  The .hide related classes related to print just don't make much sense to me, so I'll just stop using them now that I have an alternate solution.  Thanks for the guidance.
