### ISSUE TITLE
Tab's match-height option could use min-height instead of height, this would better accommodate dynamic content changes or miscalculated heights due to images being lazyloaded

### ISSUE THREAD

**Issue by philwolstenholme** [foundation/foundation-sites#11975]
## What is wrong now ?

`data-match-height="true"` sets a `height` not `min-height` value and so if additional content is added to the tab it does not automatically expand in height.

## Possible Solution

We could set `min-height` instead of height. Then all the tabs would line up visually on page load, but would also expand with any dynamic content changes or lazyloaded in images requiring more space.

## Context

* We lazyload images and so these are not taken into account when Foundation calculates the tab heights
* We have a component with a 'Show more' button. Using this button makes the component's content expand out of the tabs

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by philwolstenholme** [comment]
Happy to raise https://github.com/foundation/foundation-sites/compare/develop...philwolstenholme:patch-1 as a PR if this sounds sensible to the maintainers?

**Comment by DanielRuf** [comment]
Hi @philwolstenholme,

Thanks, a PR is very welcome.

Can you please shorten the title? It's a bit long.
