### ISSUE TITLE
Source Ordering is using default breakpoint values instead of custom

### ISSUE THREAD

**Issue by Visiluna** [foundation/foundation-sites#11972]
## BACKGROUND

`foundation.min.css` sets the `medium` breakpoint to its default value of 640px.
I have set the `medium` breakpoint to 768px in my `_settings.scss` file using
```
$breakpoints: (
  small: 0,
  medium: 768px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
```
and the new value is successfully compiled into `app.css`.
`app.css` is loaded _after_ `foundation.min.css` so its values should override the defaults.

Using the XY Grid I have:
```
<div class="grid-x">
   <div class="cell small-12 medium-6 medium-order-2">ONE</div>
   <div class="cell small-12 medium-6 medium-order-1">TWO</div>
</div>
```

## What should happen?
`<div>` ONE should be displayed full width followed by `<div>` TWO displayed full width at all widths from 1px to 767px. (ONE above, TWO below)
At all widths 768px and higher, `<div>` TWO should be displayed first at half width followed by `<div>` ONE displayed second at half width. (TWO on left, ONE on right)

## What happens instead?
`<div>` ONE is displayed at full width followed by `<div>` TWO displayed at full width at all widths from 1px to 639px. (ONE above, TWO below)
Starting at 640px, `<div>` TWO is displayed at full width followed by `<div>` ONE displayed at full width. (TWO above, ONE below).
Starting at 768px, `<div>` TWO is displayed at half width followed by `<div>` ONE displayed at half width. (TWO on left, ONE on right).

Column width is correctly honoring the custom setting of the `medium` breakpoint.
Source ordering is using the default setting of the `medium` breakpoint instead of the custom setting.

## Possible Solution
None

## Test Case and/or Steps to Reproduce (for bugs)
Test Case: http://lowthermal.dev.visiluna.com/test

How to reproduce:
1. At test case URL (above), resize browser window to various widths.
2. Note the changes that occur at 640px and 768px.

## Context
Column width change and source order change should occur at the same viewport width.

## Your Environment
- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): Various, including Chrome 79, Safari 13.0.3, iOS Safari
- Device, Operating System and version: Various
- Link to your project: 

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @Visiluna,

generally you have to set the values / settings before loading Foundation as it defines the default values if they are not set.

See https://github.com/foundation/foundation-zurb-template/blob/master/src/assets/scss/app.scss#L3-L4

**Comment by Visiluna** [comment]
That’s exactly the order mine loads in, so I should be good there.

**Comment by Visiluna** [comment]
I'm not sure if you are referring to where I said, "...app.css is loaded after foundation.min.css so its values should override the defaults." I wasn't referring to the order the .scss files are imported in. I was referring to the order the compiled .css files are in my HTML.

```
<link rel="stylesheet" type="text/css" href="/node_modules/foundation-sites/dist/css/foundation.min.css">
<link rel="stylesheet" type="text/css" href="/css/app.css">
```

**Comment by DanielRuf** [comment]
If you want to modify Foundation you have to use the scss version, not the css version as you compile a custom version of it. So loading the original css with the original compiled code is not what you want.

**Comment by DanielRuf** [comment]
> foundation.min.css sets the medium breakpoint to its default value of 640px.
I have set the medium breakpoint to 768px in my _settings.scss file using

Both `@media` rules will trigger, you can not modify or move breakpoints in normal css.

**Comment by Visiluna** [comment]
I am using the SCSS version. I guess my original post wasn’t clear. The CSS I referred to in my last comment is the CSS compiled from SCSS.

**Comment by DanielRuf** [comment]
But then you do not need the original foundation.min.css at ll as this would add the original media queries too.

Please update your question to clarify the setup. So far: please use onle the output from the scss version, and do not load foundation.min.css.

**Comment by DanielRuf** [comment]
> `app.css` is loaded _after_ `foundation.min.css` so its values should override the defaults.

This is not how it should be as I already wrote.

**Comment by DanielRuf** [comment]
After deleting `<link rel="stylesheet" type="text/css" href="/node_modules/foundation-sites/dist/css/foundation.min.css">`the `40em`rule is gone.

<img width="341" alt="Bildschirmfoto 2020-01-24 um 00 15 50" src="https://user-images.githubusercontent.com/827205/73032264-ea6b0c80-3e3e-11ea-9336-d52c93f70c87.png">


Also js files should be always loaded after all the content in body right before `</body>`.

**Comment by Visiluna** [comment]
Ah. Somehow I wasn’t clear that `foundation.min.css` was redundant. I’ll remove that and retest as soon as possible (computer is in the shop) and close this if that takes care of it. 

Thanks for the clarification. That should also make my pages a good bit leaner.

**Comment by Visiluna** [comment]
Well, I was able to test your solution without waiting for my computer to be repaired and it has, indeed, fixed my issue.

I've been including both `foundation.min.css` as well as my compiled `app.css` on every project for years. I'm honestly shocked I haven't run into a similar issue before now.

Thank you, @DanielRuf. I appreciate your assistance.
