### ISSUE TITLE
[Orbit] feature request-  allow multiple slides at once and/or preview adjacent slides.

### ISSUE THREAD

**Issue by aliciahubbard-ur** [foundation/foundation-sites#11976]
## Expected Behavior
It would be really nice to be able to create more advanced slider layouts with Foundation, specifically the ability to display more than 1 slide at once and/or show a partial preview of the previous and next slides.   The major standalone slider libraries, like [slick](https://kenwheeler.github.io/slick/) natively support these sort of more advanced slider layouts.

...

## Current Behavior
There seems to be no way to do this with Orbit without a whole lot of hacking, as your slider library actively hides previous/next slides and has them all stacked on top of each other.

...

## Possible Solution
Please natively support these sorts of advanced slider layouts!

Another possible solution would be to tweak how Orbit works so these sorts of layouts can be achieved with some CSS styles.  A lot of other libraries position the slides side by side in one big long container that is then absolutely positioned within a container with overflow: hidden.  This scheme allows easily altering a slider with some css to achieve more advanced layouts like showing so many pixels of the previous and next slides or displaying multiple slides at once.  There may be a reason you didn't take this approach, and proposed solution #1 would be preferred.

...

## Context
I tried to create a fancier slider layout that the graphic designer on our team had designed, but was unable to do so because of the massive amount of technical debt it would create.  There are a lot of use-cases for this type of slider, like displaying a slider of multiple products or wanting to encourage users to click through the slider by showing a little teaser of the next image, but currently using Foundation is restricting us to simple 1-up layouts.

P.S. - An option to change how many slides are displayed at different device sizes would be important if the ability to show multiple slides is added.

...

## Your Environment
- Foundation v6.6.1
- all browsers and devices
- Project not publicly visible

## Checklist

- [ x] I have read and follow the CONTRIBUTING.md document.
- [x ] This is a bug report or a feature request.
- [ x] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @aliciahubbard-ur,
> Please natively support these sorts of advanced slider layouts!

Orbit is just a very simple slider. We recommend alternatives like swiper which has much more features and is actively maintained (unlike slick).
