### ISSUE TITLE
Clarification On Roadmap Statement: "Support for React Exists"

### ISSUE THREAD

**Issue by peterbaxter-cvp** [foundation/foundation-sites#11973]
## What is missing?
In organizations that develop in FOundation and React.JS, it is highly desirable, from a consistency, user experience, productivity and quality standpoint, if Foundation worked in the React.JS environment. 

## What is wrong now ?
On the Project Roadmap
https://github.com/foundation/foundation-sites/wiki/Project-Roadmap
the next version of Foundation does not include any support for React because the roadmap states that support for React exists.  After searching, I find no sites that offer the Foundation package in React. There are some partial modules but none that are close to functionally complete. 

## Possible Solution
Support for React and potentially other JS development systems should be evaluated and treated as a requested feature. The statement that support exists for React, Angular, Ember  and Vue is ambiguous and lacks analysis that allows technical interchange, discussion or options. 

## Context
Our organization is currently moving from Bootstrap to Foundation, and also attempting to integrate Foundation into React development. Because Foundation does not support React, we are forced to maintain two sets of controls and styles (one for Foundation and one for React.JS).

**Comment by DanielRuf** [comment]
Hi,

that means that there are solutions for React from the community.

See https://github.com/digiaonline/react-foundation

**Comment by DanielRuf** [comment]
> Instead we should work with the community to achieve high quality integrations in every framework.

**Comment by peterbaxter-cvp** [comment]
Thank you for sharing "there are solutions for React from the community". Let me clarify. 
If an Foundation organization wanted/demands/requires a similar user experience from both JavaScript (ie Foundation) and React.JS dev, there is no solution that can provide a similar development and UX. What I am referring to is a module for React.JS that incorporates the CSS, controls, events and behaviors from Foundation. The Digiaonline link is a partial set of controls, based on the Foundation JavaScript and control properties from over 2 years ago. 
My ticket also asks for a better definition of what "exists" represents in terms of React, Angular, Vue, Ember support. A reference to Foundation exists? Anything exists? A complete representation of the Foundation Building Blocks exists?  In my view, at a minimum, the CSS, Controls and Events would need to "exist", or some quantification of those items, eg CSS- 100%, Controls-40%, Events-30%, Building Blocks-10%.  
React and Vue are extremely popular Web development platforms. Integrating with one, both, all (?) continues the Foundation project's goal for building the most advanced, responsive front end in the world. The need for Foundation in those platforms is great -- and yes there are frameworks available, such as Fabric UI, Material UI and others. But there is not a UI framework solution that can be used in a JavaScript solutions as well as a native Ember, Vue or React module.

**Comment by DanielRuf** [comment]
We can and will not maintain different implementations. As it is already described we rely on the community here, also because we are a very small group of volunteers.

This includes such quantifications like 100% of Foundation Sites CSS / JS etc supported by it. These are different implementations with their own structure and logic but the classes from Foundation.

Also Foundation Sites is now a community project.

We are aware of it that it could be better and we are working on many improvements for Foundation Sites 7 like dropping jQuery usage. And this includes also creating reusable parts for any framework. But the implementation details / usage is nothing that we handle for now.

**Comment by peterbaxter-cvp** [comment]
I recognize that resources are limited. I commend all the volunteers for dedicating their time and effort. It is a valuable and needed service. 
I am not suggesting a design solution that requires different implementations. In fact, without analyzing the technical needs, it is impossible to quantify how big/small a job this might be. But, unless the statement "exists" is removed from the Roadmap, this task can never be evaluated. 

My suggestion is to place this ("Provide React Module for Foundation") on the feature list for a future release, and let it go through the standard assessment process for inclusion. Perhaps change the statement from "exists" to "un-maintained partial port (not verified)"

**Comment by DanielRuf** [comment]
> "un-maintained partial port (not verified)"

Afaik it is actively maintained =)

We will think about this. There will be definitely changes in v7 to enable the possibility to consume Foundation Sites in almost any JS framework.

Thanks for your feedback and valuable input.
