### ISSUE TITLE
Typo: Incorrect case for "mouseleave.zf.dropdownmenu" in foundation.dropdownMenu.js#L153

### ISSUE THREAD

**Issue by iamcanadian1973** [foundation/foundation-sites#11989]
Sorry for the short bug report and not following the guidelines, but it's just a typo in the source code.

Bug:
Imouseleave.zf.dropdownmenu should be mouseleave.zf.dropdownMenu

Where: 
https://github.com/foundation/foundation-sites/blob/develop/js/foundation.dropdownMenu.js#L153

**Comment by DanielRuf** [comment]
Hi @iamcanadian1973,

thanks for reporting this. It seems there are more cases in this file where it is lowercased.
Do you want to provide a PR for this?

**Comment by iamcanadian1973** [comment]
I’m not really sure how to create a pull request. ☹

I’m always working alone, so I’ve never needed to.

**Comment by iamcanadian1973** [comment]
I’m thinking I just clone the Repo, makes some changes, and then do a pull request?

**Comment by DanielRuf** [comment]
Ok, you first fork the repository at the top right:

![grafik](https://user-images.githubusercontent.com/827205/74009638-edf4ac80-4983-11ea-97b3-04bc43433a17.png)


Then you can either clone it locally or work on GitHub

![grafik](https://user-images.githubusercontent.com/827205/74009671-0369d680-4984-11ea-8b23-459eabc1c9fd.png)

On your terminal:
`git clone git@github.com:iamcanadian1973/foundation-sites.git`
Then `cd fpundation-sites && git checkout -b fix/11989-dropdownmenu-event-name-typo`

On GitHub you can also create the branch:

![grafik](https://user-images.githubusercontent.com/827205/74009960-a4589180-4984-11ea-9f62-0fbd2c85d494.png)

Work on the js file. After that:

`git add . && git commit -m 'fix: use correct event name - closes #11989 && git push -u origin fix/11989-dropdownmenu-event-name-typo`

On GitHub you can then open the pull request.

![grafik](https://user-images.githubusercontent.com/827205/74009865-6ce9e500-4984-11ea-938e-9958e7a51e4c.png)

https://github.com/foundation/foundation-sites/compare

GitHub should already propose the pull request at the top.
If not click `compare across forks` and then select your user on the right side and your new branch.

![grafik](https://user-images.githubusercontent.com/827205/74010102-fb5e6680-4984-11ea-89e8-7499e2102be4.png)

![grafik](https://user-images.githubusercontent.com/827205/74010125-0dd8a000-4985-11ea-8715-a44d1c0ae446.png)

And then click the big green button:

![grafik](https://user-images.githubusercontent.com/827205/74010152-19c46200-4985-11ea-9baf-2a4188629cc0.png)

Fill out the PR template / description and click the submit button at the bottom right:

![grafik](https://user-images.githubusercontent.com/827205/74010188-2ea0f580-4985-11ea-9eac-bc137e146d12.png)

**Comment by DanielRuf** [comment]
Ok, you first fork the repository at the top right:

![grafik](https://user-images.githubusercontent.com/827205/74009638-edf4ac80-4983-11ea-97b3-04bc43433a17.png)


Then you can either clone it locally or work on GitHub

![grafik](https://user-images.githubusercontent.com/827205/74009671-0369d680-4984-11ea-8b23-459eabc1c9fd.png)

On your terminal:
`git clone git@github.com:iamcanadian1973/foundation-sites.git`
Then `cd foundation-sites && git checkout -b fix/11989-dropdownmenu-event-name-typo`

On GitHub you can also create the branch:

![grafik](https://user-images.githubusercontent.com/827205/74009960-a4589180-4984-11ea-9f62-0fbd2c85d494.png)

Work on the js file. After that:

`git add . && git commit -m 'fix: use correct event name - closes #11989 && git push -u origin fix/11989-dropdownmenu-event-name-typo`

On GitHub you can then open the pull request.

![grafik](https://user-images.githubusercontent.com/827205/74009865-6ce9e500-4984-11ea-938e-9958e7a51e4c.png)

https://github.com/foundation/foundation-sites/compare

GitHub should already propose the pull request at the top.
If not click `compare across forks` and then select your user on the right side and your new branch.

![grafik](https://user-images.githubusercontent.com/827205/74010102-fb5e6680-4984-11ea-89e8-7499e2102be4.png)

![grafik](https://user-images.githubusercontent.com/827205/74010125-0dd8a000-4985-11ea-8715-a44d1c0ae446.png)

And then click the big green button:

![grafik](https://user-images.githubusercontent.com/827205/74010152-19c46200-4985-11ea-9baf-2a4188629cc0.png)

Fill out the PR template / description and click the submit button at the bottom right:

![grafik](https://user-images.githubusercontent.com/827205/74010188-2ea0f580-4985-11ea-9eac-bc137e146d12.png)

**Comment by DanielRuf** [comment]
> I’m thinking I just clone the Repo, makes some changes, and then do a pull request?

Exactly. I have described a bit the steps in my last response.

**Comment by DanielRuf** [comment]
Most of this is also described at https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
