### ISSUE TITLE
W3C Css validation - I get errors with Foundation 6.6.1

### ISSUE THREAD

**Issue by mikkelschultz** [foundation/foundation-sites#11988]
## Expected Behavior

Validate my site: https://www.laaneberegner.dk/ with no errors/warning on http://jigsaw.w3.org/css-validator/

## Current Behavior

**I get 4 errors:**
URI: https://www.laaneberegner.dk/css/app661.css
476 -> too few values for the property "width"
552 -> p: Property "text-rendering" doesn't exist: "optimizeLegibility"
578 -> h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6: Property "text-rendering" doesn't exist: "optimizeLegibility"
799 -> *: Property "color-adjust" doesn't exist: "economy"

**and more then 1000 warnings like:**
"-webkit-text-size-adjust" is an unknown vendor extension
":-moz-focusring" is an unknown vendor extended pseudo-class
The value "ButtonText" is deprecated

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case:
Go to: http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.laaneberegner.dk%2F&profile=css3&usermedium=all&warning=1

How to reproduce:
1. Go to http://jigsaw.w3.org/css-validator/
2. Type in URL: https://www.laaneberegner.dk/
3. Click on button "Check"

## Context

As I understand, Google likes sites better of they follow the w3c standards :-)

This "bug" was initially reported here: https://foundation.discourse.group/t/w3c-css-validation-i-get-errors-woth-foundation/947/2 and i was asked to open the issue here in github.

## Your Environment

- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): Chrome 79
- Device, Operating System and version: Windows 10
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/w3c-css-validation-i-get-errors-woth-foundation/947/4

**Comment by DanielRuf** [comment]
Hi @mikkelschultz,

Thanks for reporting this.

The warnings can be ignored.

I will check the 4 findings

> 476 -> too few values for the property "width"

> 552 -> p: Property "text-rendering" doesn't exist: "optimizeLegibility"

> 578 -> h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6: Property "text-rendering" doesn't exist: "optimizeLegibility"

> 799 -> *: Property "color-adjust" doesn't exist: "economy"

**Comment by DanielRuf** [comment]
Also see https://github.com/foundation/foundation-sites/blob/4c290be2da77da71b170273e1666b7b537b2eb0f/scss/util/_mixins.scss#L144 and https://github.com/foundation/foundation-sites/blob/4c290be2da77da71b170273e1666b7b537b2eb0f/scss/util/_mixins.scss#L153

I'm closing this as these are not actual bugs.
