### ISSUE TITLE
Foundation.reInit not for everything?

### ISSUE THREAD

**Issue by stillworks** [foundation/foundation-sites#11992]
## What should happen?
Foundation.reInit('tabs');
...

## What happens instead?
Error. 
foundation.core.js:122 ReferenceError: We're sorry, '_init' is not an available method for this element
...

## Context

I have some dynamically created vertical tabs. Through jquery I added the a#anchors and id's to the elements. Unfornuallty  clicking the tabs won't work.

And results in 
foundation.core.js:173 Error: Syntax error, unrecognized expression: #
    at Function.se.error (jquery.min.js?v=3.4.1:2)
...

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): All of them
- Device, Operating System and version: Mac, Mamp, Drupal
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @stillworks 
please provide a codepen as reproducible testcase so we can check that.,

**Comment by DanielRuf** [comment]
Hi @stillworks 
please provide a codepen as reproducible testcase so we can check that.

**Comment by DanielRuf** [comment]
`_init` is there so this might be probably an issue with the minified version of Foundation.

The unminified foundation.js should work.

https://github.com/foundation/foundation-sites/blob/v6.5.3/js/foundation.tabs.js#L46

**Comment by DanielRuf** [comment]
Works here:
https://codepen.io/DanielRuf/pen/ZEGYKRL?editors=1111
https://codepen.io/DanielRuf/pen/MWwYmPb

`$(document).foundation()` should be called to initialize the components. `reInit` is only for reapplying a few thins. Calling `$(document).foundation()` multiple times does also work.

Please read https://get.foundation/sites/docs/javascript.html#adding-content-to-plugins carefully.

It is only for already initialized plugins / components.

Closing as the issue template was not correctly filled, no reproducible testcase provided and the question should be answered now.
