### ISSUE TITLE
Breakpoints mixin issues v6.6.1

### ISSUE THREAD

**Issue by RestlessCoder** [foundation/foundation-sites#11995]
## What should happen?
I should be able to use mixins breakpoint in sass compile to css using gulp task.
My ' _settings.scss'

```
 $breakpoints: (
      small: 0,
  msmall: 480px,
   medium: 640px,
   xmedium: 769px,
   large: 1024px,
   xlarge: 1200px,
   xxlarge: 1440px,
 );
 $breakpoints-hidpi: (
  hidpi-1: 1,
   hidpi-1-5: 1.5,
  hidpi-2: 2,
   retina: 2,
  hidpi-3: 3
 );
 $print-breakpoint: large;
$breakpoint-classes: (small msmall medium xmedium large xlarge);
```

...

## What happens instead?

> WARNING: breakpoint(): "small" is not defined in your `$breakpoints` or `$breakpoints-hidpi` setting.
>          on line 92 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in function `breakpoint`
>          from line 152 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in mixin `breakpoint`
>          from line 28 of scss/layout/large-hero.scss
>          from line 72 of scss/app.scss
> 
> WARNING: breakpoint(): "medium down" is not defined in your `$breakpoints` or `$breakpoints-hidpi` setting.
>          on line 92 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in function `breakpoint`
>          from line 152 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in mixin `breakpoint`
>          from line 33 of scss/layout/large-hero.scss
>          from line 72 of scss/app.scss
> 
> WARNING: breakpoint(): "medium" is not defined in your `$breakpoints` or `$breakpoints-hidpi` setting.
>          on line 92 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in function `breakpoint`
>          from line 152 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in mixin `breakpoint`
>          from line 48 of scss/layout/large-hero.scss
>          from line 72 of scss/app.scss
> 
> WARNING: breakpoint(): "large" is not defined in your `$breakpoints` or `$breakpoints-hidpi` setting.
>          on line 92 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in function `breakpoint`
>          from line 152 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in mixin 

        
...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): 
- Device, Operating System and version: Windows 10
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @RestlessCoder,

please provide a repository as reproducible testcase.

**Comment by RestlessCoder** [comment]
Hi @DanielRuf

Here you go. Repository for the breakpoints issues
https://github.com/RestlessCoder/Foundation-Breakpoint-Testing

**Comment by DanielRuf** [comment]
This is caused by https://github.com/RestlessCoder/Foundation-Breakpoint-Testing/blob/master/scss/utilities/_spacing.scss#L18-L23 and https://github.com/RestlessCoder/Foundation-Breakpoint-Testing/blob/master/scss/utilities/_font-size.scss#L9-L14

I debugged this using [`@debug`](https://sass-lang.com/documentation/at-rules/debug)

```
/Users/danielruf/projects/Foundation-Breakpoint-Testing/node_modules/foundation-sites/scss/util/_breakpoint.scss:79 DEBUG: breakpoints values: (: 0, l: 1024px, m: 1023px, s: 640px)
WARNING: breakpoint(): "medium" is not defined in your `$breakpoints` or `$breakpoints-hidpi` setting.
         on line 93 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in function `breakpoint`
         from line 153 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in mixin `breakpoint`
         from line 2 of scss/_testing.scss
         from line 69 of scss/app.scss
```

**Comment by DanielRuf** [comment]
This is caused by https://github.com/RestlessCoder/Foundation-Breakpoint-Testing/blob/master/scss/utilities/_spacing.scss#L18-L23 and https://github.com/RestlessCoder/Foundation-Breakpoint-Testing/blob/master/scss/utilities/_font-size.scss#L9-L14

In your case you overwrite the `$breakpoints`variable at https://github.com/RestlessCoder/Foundation-Breakpoint-Testing/blob/master/scss/utilities/_spacing.scss#L26 and https://github.com/RestlessCoder/Foundation-Breakpoint-Testing/blob/master/scss/utilities/_font-size.scss#L17

I debugged this using [`@debug`](https://sass-lang.com/documentation/at-rules/debug)

```
/Users/danielruf/projects/Foundation-Breakpoint-Testing/node_modules/foundation-sites/scss/util/_breakpoint.scss:79 DEBUG: breakpoints values: (: 0, l: 1024px, m: 1023px, s: 640px)
WARNING: breakpoint(): "medium" is not defined in your `$breakpoints` or `$breakpoints-hidpi` setting.
         on line 93 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in function `breakpoint`
         from line 153 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in mixin `breakpoint`
         from line 2 of scss/_testing.scss
         from line 69 of scss/app.scss
```

**Comment by DanielRuf** [comment]
Not sure where this code is from but it looks like https://gist.github.com/stephencostello/8e8a5a935e4f44dbd2c17504c7102570

You have to adjust the code or change your setup to fix this.
