### ISSUE TITLE
Multilevel dropdown - submenus do not open/show on click

### ISSUE THREAD

**Issue by rmsdev** [foundation/foundation-sites#11997]
## Expected Behavior

Open/show submenu on click with options
data-disable-hover="true" data-click-open="true"

https://codepen.io/IamManchanda/pen/jmKPdM

## Current Behavior

Does not work with foundation v6.6.1
Only first level gets shown, click on submenu has no effect

## Possible Solution

Works with foundation v6.5.1

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Download or setup latest Version with index.html file -> https://get.foundation/sites/docs/installation.html
2. add https://codepen.io/IamManchanda/pen/jmKPdM
with options
data-disable-hover="true" data-click-open="true"

## Context

...

## Your Environment

- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): chrome, firefox
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @rmsdev,

thanks for reporting this. See https://foundation.discourse.group/t/foundation-v6-6-1-v6-6-0-breaks-nested-dropdown-menus/1012/4 which is relevant.

**Comment by DanielRuf** [comment]
Here is the correct codepen: https://codepen.io/DanielRuf/pen/xxGwpVm?editors=1000

**Comment by DanielRuf** [comment]
6.6.0 seems to work so it was introduced between 6.6.0 and 6.6.1

https://codepen.io/DanielRuf/pen/gOpaoGw?editors=1000

**Comment by DanielRuf** [comment]
Ah no, it started after 6.5.3. This one was incorrectly uploaded as 6.6.0 but is 6.5.3: https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.0/js/foundation.min.js

**Comment by DanielRuf** [comment]
I did some bisecting. As I've expected, it's the same commit which causes this:

```
git bisect good      
3aade104619a2fbf758a1dc7b1b8cb24eb76bcd1 is the first bad commit
commit 3aade104619a2fbf758a1dc7b1b8cb24eb76bcd1
Author: Nicolas Coden <nicolas@ncoden.fr>
Date:   Sun Aug 19 23:50:03 2018 +0200

    fix: avoid stopping event propagation when not necessary
    
    Stopping the event propagation prevent the user to watch for the event at an higher level. If it was needed to prevent a duplicate behavior in a component, others methods should be used like debouncing the event.
    
    Changes:
    - Remove `stopPropagation` and `stopImmediatePropagation` from everywhere we do not want to cancel the event (AccordionMenu, Drilldown, DropdownMenu, Tabs, Tooltip).
    - Update `DropdownMenu._removeBodyHandler` to also ignore click events on the element itself.
    
    Others changes:
    - Clean up `DropdownMenu._events` a bit.
    - Add explainaitions where `stopPropagation` is still used (Triggers).
    
    See https://github.com/zurb/foundation-sites/issues/11457

 js/foundation.accordionMenu.js |  1 -
 js/foundation.drilldown.js     |  4 ----
 js/foundation.dropdownMenu.js  | 19 ++++++++++---------
 js/foundation.tabs.js          |  1 -
 js/foundation.tooltip.js       |  2 --
 js/foundation.util.triggers.js |  4 +++-
 6 files changed, 13 insertions(+), 18 deletions(-)
```

**Comment by DanielRuf** [comment]
3aade104619a2fbf758a1dc7b1b8cb24eb76bcd1
