### ISSUE TITLE
6.6.1 Abide  - cannot prevent submitting form

### ISSUE THREAD

**Issue by hillbilly007** [foundation/foundation-sites#12009]
## Expected Behavior
I want to use Abide to validate the form and then prevent the form from submitting using
$("#form) .on("submit", function(ev) {
    ev.preventDefault();
    console.log("Submit for form id "+ev.target.id+" intercepted");
  });

## Current Behavior
The Form submits when I use Foundation 6.6.1.
If I use Foundation 6.4.3 then I can intercept the form.

## Possible Solution
Sorry - No idea  - still a junior.

## Test Case and/or Steps to Reproduce (for bugs)
Here is the buggy version with Foundation 6.6.1:
https://newkiller.nathanhilldesign.co.uk/testform-F-6-6-1.php

Here is the working version with Foundation 6.4.1
https://newkiller.nathanhilldesign.co.uk/testform.php

## Context
I want to have multiple steps to the form and submit via ajax so I do not want the form to force a page reload on submit.

## Your Environment
Currently using Foundation 6.6.1 with JQuery 3.4.1

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by hillbilly007** [comment]
SOLUTION!

Please note I am using the "DOWNLOAD VERSION" of Foundation 6.6.1. That is where the bug creeps in somewhere.

If I use the CDNS:
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.1/js/foundation.min.js

Then the prevent form works as it should - so maybe that download version you supply needs a tweak?

**Comment by DanielRuf** [comment]
> If I use the CDNS:
> [cdnjs.cloudflare.com/ajax/libs/foundation/6.6.1/js/foundation.min.js](https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.1/js/foundation.min.js)

This contains an old version (6.5.3) as you can see in the file. Please try https://unpkg.com/foundation-sites@6.6.1/dist/js/foundation.min.js

Because I think this is not fixed there. Also please try https://unpkg.com/foundation-sites@6.6.1/dist/js/foundation.js

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/abide-validate-certain-parts-of-form-only/1222/8

**Comment by hillbilly007** [comment]
> > 
> Because I think this is not fixed there. Also please try https://unpkg.com/foundation-sites@6.6.1/dist/js/foundation.js

Yes that works - thank you.

**Comment by DanielRuf** [comment]
Ok, thanks for the feedback.

I think the cause is described in #11743 which will land in the next release.
