### ISSUE TITLE
Off canvas absolute and grid-y

### ISSUE THREAD

**Issue by kickbk** [foundation/foundation-sites#12016]
I just started playing with Foundation and it seems great.
I am basing my layout (https://codepen.io/kickbk/pen/mdJXKMZ) on the XY Grid and Off Canvas examples.

What I expect to have is the off canvas div pushing the off-canvas-wrapper, add that transparent overlay on top of it, and because I use a `off-canvas-wrapper` with `off-canvas-absolute` classes, it should appear below the header.

Notice that I am using the `grid-y` and `grid-frame` classes twice:

1. To keep the header at the top and the rest below it
2. Applied to the main div I want to keep the main content below the header and the footer at the bottom of the page.

First of all - the fact that foundation can do all that with a few classes is very impressive.

BUT, I am running into the following issues:
1. The off canvas does not push `main` to the right when it pulls from the left.
2. If stops adding that white transparent background on top of `main`

But more importantly, could someone who knows foundation really well please have a look at my code below and let me know if I am doing something wrong?

```
<div class="grid-y medium-grid-frame">
  <header class="cell shrink header">
    <button type="button" class="button" data-toggle="offCanvas">
      open
    </button>
    HEADER
  </header>
  <div class="off-canvas-wrapper cell medium-auto medium-cell-block-container">
    <div class="off-canvas-absolute position-left" id="offCanvas" data-off-canvas>
      <h1>OFF CANVAS</h1>
      <button class="close-button" aria-label="Close menu" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <main class="off-canvas-content grid-y medium-grid-frame">
      <div class="cell medium-auto medium-cell-block-container">
        MAIN CONTENT
      </div>
      <footer class="cell shrink footer">
        <h3>FOOTER</h3>
      </footer>
    </main>
  </div>
</div>
```

**Comment by SassNinja** [comment]
Hi @kickbk 

the reason is quite simple: you've forgotten to add the necessary `data-off-canvas-content` attribute.

after having added it both will work, overlay & push
```html
<main data-off-canvas-content class="off-canvas-content grid-y medium-grid-frame">
```
