### ISSUE TITLE
Orbit looping issues

### ISSUE THREAD

**Issue by joeworkman** [foundation/foundation-sites#12015]
## What happens?

When Orbit is looping back to the first slide, it ceases to function in v6.6.1

## Possible Solution

I need to investigate this further

## Test Case and/or Steps to Reproduce (for bugs)
Test Case: https://codepen.io/joeworkman/pen/MWwrpoy?editors=1000

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by reinhardmohr** [comment]
Hi, Joe,
I had this issue about four weeks ago. It‘s a javascript problem in the css version. It was fixed in the developer version. There is a fix somewhere on GitHub with two lines of javascript.
I was searching everywhere for more information but could only find this information in my memory. Sorry for not providing more details.
Thanks for your continuing work for foundation!
Reinhard

**Comment by mmaxluca** [comment]
I have the same issue [here](https://codepen.io/Maxvilander/pen/wvaPXbp)'s the codepen. It seems it doesn't work in v. 6.6.0 and 6.6.1, i tested 6.5.3 and it works.

**Comment by DanielRuf** [comment]
Here is the full comparison between 6.5.3 and 6.6.0:

https://github.com/foundation/foundation-sites/compare/v6.5.3..v6.6.0

**Comment by Syed51214** [comment]
[best pack n play for sleeping](https://bestpacknplays.reviews/) If you're thinking of skipping the crib, a pack n play yard can provide a great sleeping environment for your kid. Top rated pack and play offer a lot more than just ...

**Comment by joeworkman** [comment]
This was fixed in 6.6.2. My bad for not referencing this issue in the PR.

**Comment by DanielRuf** [comment]
> This was fixed in 6.6.2. My bad for not referencing this issue in the PR.

Which PR exactly? I can not find a relevant PR here.

**Comment by DanielRuf** [comment]
Do you mean https://github.com/foundation/foundation-sites/pull/11944? Never checked if this fixes this. Was this PR the needed fix?

**Comment by joeworkman** [comment]
I verified. It's working now for me in the released version
