### ISSUE TITLE
Not possible to donwload 5.5.3

### ISSUE THREAD

**Issue by morgoth** [foundation/foundation-sites#12018]
I cannot find a CSS/JS files for 5.5.3 version anywhere.
I donwnloaded the source from https://github.com/foundation/foundation-sites/releases/tag/v5.5.3 however with such an old build setup, looks like it's not really possible to build it nowadays.

BTW, is there any guide how to upgrade from 5.x to 6.x?

**Comment by DanielRuf** [comment]
Hi @morgoth,

Please try `npm i foundation-sites@5.5.3` or use the files from https://unpkg.com/foundation-sites/

We have no upgrade guide and we do not support v5 anymore. The best is to create a new v6 project and migrate v5 components and code to v6.
