### ISSUE TITLE
Compatibility with the latest versions of node-sass and sass

### ISSUE THREAD

**Issue by bobbylej** [foundation/foundation-sites#12010]
## What should happen?
Foundation should work with Angular version 9. Foundation should be compatible with the latest versions of node-sass and sass.

## What happens instead?
After upgrading my project from Angular 7 to Angular 9 I cannot compile scss files from foundation-sites. I assume that it happens because Angular along with version 8 stops using [node-sass](https://github.com/sass/node-sass) and starts using [sass](https://github.com/sass/dart-sass) compiler or it's somehow connected to it. Even after installing the same node-sass version as it was used before migration to Angular 9 it's still impossible to compile foundation files. 

While trying to build my Angular project I'm getting such errors (There are two cases): 

- Using node-sass
```
ERROR: media query expression must begin with '('
An unhandled exception occurred: media query expression must begin with '('
```

- Using sass
```
ERROR in ./src/scss/app.scss (node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src??embedded!node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js??ref--15-3!./src/scss/app.scss)
Module build failed (from node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: $lightness: Expected 0 to have unit "%".
    ╷
231 │   $color-hover: scale-color($color, $lightness: $hover-lightness);
    │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/foundation-sites/scss/components/_button.scss 231:17  button-hollow-style()
  dist/gutwin-shared/scss/components/_button.scss 123:3              @import
```
```
ERROR: (small: 0, medium: 640px, large: 1024px, xlarge: 1200px, xxlarge: 1440px) isn't a valid CSS value.
   ╷
36 │ $-zf-breakpoints-keys: map-to-list($breakpoints, 'keys');
   │                                    ^^^^^^^^^^^^
   ╵
  node_modules/foundation-sites/scss/util/_breakpoint.scss 36:36            @import
  projects/gutwin-shared/src/scss/components/_modal.scss 2:9                @import
  projects/gutwin-shared/src/lib/components/modal/modal.component.scss 1:9  root stylesheet
```

## Possible Solution

Fix Foundation's files so it will be compatible with the latest versions of node-sass and sass.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: I cannot publish my code

How to reproduce:
1. Create Angular 9 app
2. Add foundation-sites to project
3. Use breakpoint mixin from foundation
4. Try to build your project

## Context

Upgrading project from Angular 7 to Angular 9

## Your Environment

- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): -
- Device, Operating System and version: macOS Mojave
- Node version: 12.16.0
- Angular version: 9.0.4
- Angular CLI version: 9.0.4
- ng-packagr version: 9.0.2
- node-sass version: 4.13.1
- sass version: 1.23.3
- Link to your project: -

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @bobbylej,

we already use node-sass 4, see https://github.com/dlmanning/gulp-sass/blob/v4.0.2/package.json#L29

Regarding the node-sass error, please see https://github.com/sass/libsass/issues/1766, https://github.com/sass/node-sass/issues/1270 and other related issues.

Your Sass setup may use the wrong variant (scss vs sass).

> ERROR: media query expression must begin with '('
> An unhandled exception occurred: media query expression must begin with '('

Not sure where this error occurs. Please provide more information and context.

**Comment by bobbylej** [comment]
Hi @DanielRuf,

Thanks for the answer!

I saw that it's working fine with Angular 7 and node-sass 4.12.0, but after using the same version of node-sass for Angular 9 I'm getting this error.

I'm not sure where this error occurs, because there is a lack of info in error message. The full message looks like that:
```
[error] Error: media query expression must begin with '('
    at Object.module.exports.renderSync (node_modules/node-sass/lib/index.js:441:16)
    at StylesheetProcessor.renderPreProcessor (node_modules/ng-packagr/lib/styles/stylesheet-processor.js:61:22)
    at StylesheetProcessor.process (node_modules/ng-packagr/lib/styles/stylesheet-processor.js:44:34)
    at Object.readResource (node_modules/ng-packagr/lib/ts/cache-compiler-host.js:78:57)
    at TsCompilerAotCompilerTypeCheckHostAdapter.loadResource (node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:502:37)
    at Object.get (node_modules/@angular/compiler/bundles/compiler.umd.js:27843:94)
    at DirectiveNormalizer._fetch (node_modules/@angular/compiler/bundles/compiler.umd.js:19642:47)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:19764:72
    at Array.map (<anonymous>)
    at DirectiveNormalizer._loadMissingExternalStylesheets (node_modules/@angular/compiler/bundles/compiler.umd.js:19764:18)
```
In my project I'm not using media queries directly, only by using `breakpoint` mixin imported from `node_modules/foundation-sites/scss/util/_breakpoint.scss` file. So I'm guesing that error can occur in 167 line (`@media print, screen and #{$str} {`) and 172 line (`@media screen and #{$str} {`). 

However, I tried to generate new, empty angular library it the same project and I used `breakpoint` mixin in there and this library was built successfully. So at this moment, I'm not 100% sure. Will try to investigate it a bit more.

**Comment by Syed51214** [comment]
[street skateboard 2](https://electricskateboards.best/) Street Skate 2 is a very popular extreme sport game that has 3D graphics that perhaps makes the game play even more interesting. Here in this point scoring ...

**Comment by bobbylej** [comment]
I was wrong. The problem was that in some files, where I used `breakpoint` mixin, I had to import also `node_modules/foundation-sites/scss/util/_value.scss` file. So I just added `@import '~foundation-sites/scss/util/value';` before `@import '~foundation-sites/scss/util/breakpoint';`.
It fixed my problems with foundation after migration to Angular 9.

I'm closing this issue.

**Comment by DanielRuf** [comment]
Thanks for the update that it works now.

You might also want to check https://github.com/foundation/foundation-sites/blob/develop/scss/util/_util.scss and use our template which includes everything:

https://github.com/foundation/foundation-zurb-template/blob/master/src/assets/scss/app.scss

Because it sounds like you handpicked some parts and copied them into your setup which might work but could also easily break as you have seen.

**Comment by bobbylej** [comment]
Thanks for this tip, it would help me to avoid such errors for sure, but I prefer to import only required things to not overload my app.

**Comment by DanielRuf** [comment]
Well, you can easily remove the imports for the unneeded components in this template. Everything else are mostly utils and do not add extra content if not used. That's the advantage of sass / scss.

Better than missing some parts that you may still need ;-)

**Comment by DaveyJake** [comment]
> I was wrong. The problem was that in some files, where I used `breakpoint` mixin, I had to import also `node_modules/foundation-sites/scss/util/_value.scss` file. So I just added `@import '~foundation-sites/scss/util/value';` before `@import '~foundation-sites/scss/util/breakpoint';`.

@bobbylej  Thank you for this! For months, I've had to copy and paste a the `_breakpoint.scss` file from version `6.5.1` to make it work.  Added the `_value.scss` file solved my issue. Again, THANK YOU!!!

**Comment by JeremyCaney** [comment]
@DanielRuf: I'm encountering a similar issue when (finally!) migrating from `node-sass` to `sass`. When I attempt to import the `breakpoint` SCSS file in order to get access to e.g., the `breakpoint()` function using:

```
@use 'foundation-sites/scss/util/breakpoint' as *;
```

I receive the error:

```
Error in plugin "sass"
Message:
    node_modules/foundation-sites/scss/util/_breakpoint.scss
Error: ("small": 0, "medium": 640px, "large": 1024px, "xlarge": 1200px, "xxlarge": 1440px) isn't a valid CSS value.
   ╷
39 │ $-zf-breakpoints-keys: map-to-list($breakpoints, 'keys');
   │                                    ^^^^^^^^^^^^ value
   │                        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unknown function treated as plain CSS
   ╵
  node_modules/foundation-sites/scss/util/_breakpoint.scss 39:36  @use
  Shared/Styles/Style.scss 8:1                                    root stylesheet
```

I've tried loading `value` prior to this, as suggested by @bobbylej, as well as some other files, but to no avail:

```
@use 'foundationSettings' as *;
@use "variables" as *;
@use 'foundation-sites/scss/util/value' as *; 
```

I'm not certain if this is a bug, or if it's me misunderstanding how to properly import these functions. Any thoughts?

This is using the following relevant dependencies:
```
"foundation-sites": "^6.9.0",
"gulp": "^4.0.2",
"gulp-sass": "^5.1.0",
"sass": "^1.80.6",
```
