### ISSUE TITLE
[Buttons] Mixins for :host selectors

### ISSUE THREAD

**Issue by TvrtkoM** [foundation/foundation-sites#12024]
## What is missing?
Mixins only work for regular elements selectors, not for `:host`. Probably not only buttons but also other components using pseudo selectors

## What is wrong now ?
button mixins don't generate valid css for `:host` pseudo selector. It generates `:host:hover` instead of `:host(:hover)`. Workaround is to add one more wrapping element in component template and use mixin on it

## Possible Solution
Adding boolean argument to mixins or creating mixins specifically for `:host`.
I'm volunteering to supply PR if this is something Foundation wants.

## Your Environment
- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): latest Chromium
- Device, Operating System and version: xubuntu

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @TvrtkoM,

thanks for reporting this.
But I do not really understand what you mean. There is no `:host` in the scss files and css files at all:

<img width="248" alt="Bildschirmfoto 2020-03-22 um 23 00 40" src="https://user-images.githubusercontent.com/827205/77261750-149b4800-6c91-11ea-8791-e6feb1f5ae43.png">

<img width="244" alt="Bildschirmfoto 2020-03-22 um 23 02 04" src="https://user-images.githubusercontent.com/827205/77261759-2bda3580-6c91-11ea-9413-2af6e800e361.png">

**Comment by DanielRuf** [comment]
Hi @TvrtkoM,

thanks for reporting this.

But I do not really understand what you mean. There is no `:host` in the scss files and css files at all:

<img width="248" alt="Bildschirmfoto 2020-03-22 um 23 00 40" src="https://user-images.githubusercontent.com/827205/77261750-149b4800-6c91-11ea-8791-e6feb1f5ae43.png">

<img width="244" alt="Bildschirmfoto 2020-03-22 um 23 02 04" src="https://user-images.githubusercontent.com/827205/77261759-2bda3580-6c91-11ea-9413-2af6e800e361.png">

**Comment by DanielRuf** [comment]
Please provide some code so that we can reproduce this.

**Comment by DanielRuf** [comment]
If you mean `&:hover`, these are the correct and normal selectors in SCSS.
So far we have no special support for Shadow DOM.

As Foundation Sites still has to support and supports IE 10 and 11 we do not provide such solutions so far. Also see https://caniuse.com/#feat=mdn-api_shadowroot_host

**Comment by DanielRuf** [comment]
Related:

https://github.com/sass/sass/issues/1436#issuecomment-56225206
https://github.com/sass/sass/issues/1425

**Comment by TvrtkoM** [comment]
```scss
:host {
   @include button-hollow-style;
}
```
doesn't have e.g. `:hover` pseudo-class compiled to
```css
:host(:hover) { /* ... */ }
```
but
```css
:host:hover { /* ... */ }
```

But nevertmind, after thinking about this a bit, it would be pretty hard to implement it as mixin considering other usecases such as `:hover(.class-name) { @include ...; }`

Nevertheless it's something scss compiler will probably have to deal with.

Workaround is having additional element inside component shadow dom

**Comment by TvrtkoM** [comment]
> As Foundation Sites still has to support and supports IE 10 and 11 we do not provide such solutions so far. Also see https://caniuse.com/#feat=mdn-api_shadowroot_host

Hope Foundation 7 will not have to support IE or Edge past Edge Chromium based. :)
