### ISSUE TITLE
SRI integrity check for 6.6.3 from CDN is failing

### ISSUE THREAD

**Issue by br3nt** [foundation/foundation-sites#12047]
## What should happen?

Using the CDN links defined on the website I should be able to import foundation-sites.

Eg from the website:
```html
<!-- Compressed CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css" integrity="sha256-Q2fXBbKhtsyhYrSLa7hXCNV+FdhbQhyrjks8Kic0u/U=" crossorigin="anonymous">

<!-- Compressed JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/js/foundation.min.js" integrity="sha256-tdB5sxJ03S1jbwztV7NCvgqvMlVEvtcoJlgf62X49iM=" crossorigin="anonymous"></script>
```

## What happens instead?

I get the following error messages in Chrome:

> Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css' with computed SHA-256 integrity 'ogmFxjqiTMnZhxCqVmcqTvjfe1Y/ec4WaRj/aQPvn+I='. The resource has been blocked.
> localhost/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/js/foundation.min.js' with computed SHA-256 integrity 'pRF3zifJRA9jXGv++b06qwtSqX1byFQOLjqa2PTEb2o='. The resource has been blocked.

As you can see, the integrity hashes differ.  For example for *foundation.min.js*: `Q2fXBbKhtsyhYrSLa7hXCNV+FdhbQhyrjks8Kic0u/U=` vs `ogmFxjqiTMnZhxCqVmcqTvjfe1Y/ec4WaRj/aQPvn+I=`.

I can confirm that Chrome is reporting the correct hash because when I check in the terminal I get the same hash:
```sh
curl https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css \
| openssl dgst -sha256 -binary | openssl base64 -A
```

Yields `ogmFxjqiTMnZhxCqVmcqTvjfe1Y/ec4WaRj/aQPvn+I=`.

**Comment by DanielRuf** [comment]
Hi @br3nt,

Thanks for letting us know.

You can simply change your hash value to `ogmFxjqiTMnZhxCqVmcqTvjfe1Y/ec4WaRj/aQPvn+I=`.

We will update it.

@joeworkman that has to be updated after every release.

**Comment by DanielRuf** [comment]
We can copy the values from the jsdelivr pages:

![Screenshot_20200412-105202](https://user-images.githubusercontent.com/827205/79064723-bcfa6600-7cab-11ea-83c8-2be35c009a99.jpg)

**Comment by DanielRuf** [comment]
The values are updated and the changes were deployed to the documentation website.
