### ISSUE TITLE
[Installation] Download Link not working

### ISSUE THREAD

**Issue by stocktonsimon** [foundation/foundation-sites#12041]
The "Download Foundation" link on https://get.foundation/sites/docs/installation.html doesn't appear to work.

The link gives the following error.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>CEF6038E76B3433E</RequestId>
<HostId>
juFZS5p2Qly4QIUqcXseGBYVFe5p8gOAzsirk+gor0eYd5EHsFtjm0L+YavDnMerlHwhaJgGbVU=
</HostId>
</Error>

**Comment by DanielRuf** [comment]
Hi @stocktonsimon,

we are aware of it. Please see https://github.com/foundation/foundation-sites/issues/12040#issuecomment-607313935

> We are already aware of this and are working on a fix. You can also download from unpkg:
> 
> https://unpkg.com/foundation-sites@6.6.2/dist/js/foundation.min.js
> https://unpkg.com/foundation-sites@6.6.2/dist/css/foundation.min.css

**Comment by DanielRuf** [comment]
PS: https://dhbhdrzi4tiry.cloudfront.net/downloads/releases/Foundation-6.6.1-CSS-project.zip still works.

**Comment by stocktonsimon** [comment]
Thanks Daniel,

I am finding it a bit of a minefield as the documentation appears to suggest that the download contains the foundation.css and foundation.js files containing the code and app.css and app.js to add user code. However, these links appear not to have these files.

**Comment by DanielRuf** [comment]
> I am finding it a bit of a minefield as the documentation appears to suggest that the download contains the foundation.css and foundation.js files containing the code and app.css and app.js to add user code. However, these links appear not to have these files.

The app.js file contains all JS code. Same for app.css. Including Foundation Sites.

<img width="1026" alt="Bildschirmfoto 2020-04-05 um 15 15 13" src="https://user-images.githubusercontent.com/827205/78499331-57105a80-7750-11ea-82da-e4b8ae8ee860.png">

Not sure if there was something changed or if the docs are just outdated regarding this.

@joeworkman please check that.

Anyways, PRs are very welcome to improve / fix this text @stocktonsimon.
