### ISSUE TITLE
Main download button giving error page

### ISSUE THREAD

**Issue by craigvt** [foundation/foundation-sites#12040]
## What should happen?

https://get.foundation/sites/docs/installation.html
Download button that all other links direct to is causing an error, preventing users from downloading.
Should trigger download or direct to download page.

## What happens instead?

404 error page

## Possible Solution

Possibly a Cloudfront issue. Not sure.

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. try to download from website
2.
3.

## Context

It has prevented me from downloading Foundation to use in my project.

## Your Environment

- Foundation version(s) used: na
- Browser(s) name and version(s):  Firefox
- Device, Operating System and version:  Ubuntu Linux 19.10
- Link to your project: na

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @craigvt,

thanks for reporting this.

We are already aware of this and are working on a fix. You can also download from unpkg:

https://unpkg.com/foundation-sites@6.6.2/dist/js/foundation.min.js
https://unpkg.com/foundation-sites@6.6.2/dist/css/foundation.min.css

**Comment by DanielRuf** [comment]
https://dhbhdrzi4tiry.cloudfront.net/downloads/releases/Foundation-6.6.1-CSS-project.zip


Can you check https://dhbhdrzi4tiry.cloudfront.net/downloads/releases/Foundation-6.6.2-CSS-project.zip @joeworkman?

**Comment by craigvt** [comment]
Thank you for the quick response! I was able to get the items needed.
