### ISSUE TITLE
Support for server-side validation for Abide

### ISSUE THREAD

**Issue by br3nt** [foundation/foundation-sites#12058]
## What is missing?

There are two main features missing that would support server-side validation: 

* Initiating form validation on page load
* Displaying server-side validation messages

## What is wrong now?

In order to display server-side validation messages, we need to jump through a few hoops.

* We need to register a custom validator
* We need to attach the custom validator to each element
  * The custom validator could either always return false; or
  * We can query the element for an additional data attribute which indicates the validation state

This is an example from a Rails erb view:

```erb
<%= form_tag(registration_path, id: 'registration-form', data: { abide: true }, novalidate: true) do %>
  <fieldset>
    <legend><h1>Registration</h1></legend>

    <div data-abide-error class="alert callout" style="display: none;">
      <p><i class="fi-alert"></i>Please complete the form</p>
    </div>

    <fieldset class="input-group">
      <label for="email">
        What is your contact email?
      </label>
      <input id="email"
        name="registration[email]" type="email" required
        data-server-side-invalid data-validator="server-side"
        placeholder="your@email.com"
        value="<%= @registration.email %>">
      <span
        class="form-error"
        data-form-error-for="email"
        data-form-error-on="server-side">
        A server-side validation message!
      </span>
    </fieldset>

    <fieldset class="input-group">
      <label for="password">
        What password will use to secure your account?
      </label>
      <input id="password"
        name="registration[password]" type="text" required
        data-server-side-valid data-validator="server-side"
        placeholder="Password"
        pattern="^.{10,72}$"
        value="<%= @registration.password %>"
      >
      <span
        class="form-error"
        data-form-error-for="password"
        data-form-error-on="pattern">
        Your password must be between 10 and 72 characters.
      </span>
      <span
        class="form-error"
        data-form-error-for="password"
        data-form-error-on="server-side">
        This server-side error message should bbe hidden!
      </span>
    </fieldset>

    <input type="submit" class="button" value="Register">
  </fieldset>
<% end %>

<% if !@registration.valid? %>
  <script>
    // attach a custom server-side validator
    Foundation.Abide.defaults.validators['server-side'] = ($el, required, parent) => {
      return $el.data('server-side-invalid') === undefined;
    }

    // validate the form on page load
    $(document).on('turbolinks:load', () => {
      $('#registration-form').foundation('validateForm')
    })
  </script>
<% end %>
```

## Possible Solution

Use a data attribute on the form element to initiate validation on load, such as `data-abide-validate-on-load`.  This would prompt Abide to run the validations once It is ready.

Eg:
```html
<form data-aide novalidate data-abide-validate-on-load>
  ...
</form>
```

Provide a default data attribute that can be added to input elements, such as `data-server-side-invalid`, that will show error messages for the input which match `data-form-error-on="server-side"`.

Eg:
```html
<input id="password" name="password" type="password" required
  data-server-side-invalid
  value="bob">
<span class="form-error"
  data-form-error-for="email"
  data-form-error-on="server-side">
  Password needs to be greater than 10 characters.
</span>
```

This solution is nice because it:
* fits in nicely with Abide's declarative style.  
* is simple and intuitive.
* doesn't require any changes to existing validation rules.
* reduces the amount of boilerplate code required to support server-side validation messages.  

## Your Environment

- Foundation version(s) used: foundation-rails (6.6.2.0)
- Browser(s) name and version(s): Chrome 81.0.4044.122
- Device, Operating System and version: Mac, Docker, Ubuntu

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @br3nt,

so far we do not have any components with any serverside logic or implementation.
This also depends on the used backend. In general the backend framework should independently do the validations and output the HTML as needed.

In general you can set a field as invalid if needed.
See the part in the docs where the invalid fields are already marked as such:

https://get.foundation/sites/docs/abide.html#error-state

I mean the part with `Yo, you had better fill this out.` which uses `is-invalid-label` and `is-invalid-input`.

> on the form element to initiate validation on load

So this should be already the case.
I think I miss the real problem, use case and I think additional validators can be added by anyone if needed. We provide only some basic frontend validators and this is a pure .

In your case `Password needs to be greater than 10 characters.` is covered by `min-length` on the input.

If you think the addition makes sense (there can be multiple results from the serverside validation so one message alone makes not much sense) feel free to privde a PR.

**Comment by br3nt** [comment]
Hi @DanielRuf,

Oops, I didn't pick my server-side example too well, did I?  I just copied and pasted the HTML from dev tools 🤦

A realistic server-side message for a sign-up form would be "That email is already taken".

I just want to reiterate that my intention isn't to find help about the best validator for password length or problems with login/signup forms, but rather, to find a solution for the general and common problem of presenting one or more server-side error message to the user in the same format as client-side error messages and mark up the invalid elements immediately.

Most of the time, this will only happen after the user submits a form that passes client-side validation.  The server receives and validates the submission, but finds something wrong, and must redisplay the form to the user with the addition of the server error messages.

I hope this is clear to you now.

> In general you can set a field as invalid if needed.

Thanks for pointing me to the [error-state example](https://get.foundation/sites/docs/abide.html#error-state) example.  I must admit I didn't quite understand what was going on in that example until your explanation.  I can confirm this solution does work, but having to add code to add 4 classes/attributes on three different elements is cumbersome and probably error-prone. I just tested how validation works again and noticed a fifth attribute being added, `data-invalid`.

I would like to seek out a better solution.

> We provide only some basic frontend validators and this is a pure

Bootstrap actually makes similar comments about wanting to stay away from server-side stuff.  Personally I don't understand this stance at all. Forms are the only HTML elements designed specifically to talk to the backend.  The use-case I have outlined in also extremely common.  I think it's only logical and natural to provide some sugar.

> So this should be already the case.

Yes, I agree with you that nothing extra needs to be added to the form element.

However, I'm now thinking that a better approach would be to have Abide check for any elements with the `data-invalid` attribute on page load.  For any matching inputs, Abide can then do its thing by adding all the mark-up in the same way it currently does for invalid inputs.

The only remaining problem is to get the server-side error message to show up.  As you suggested, the `is-visible` class can be added.

I think this would be a relatively elegant and simple solution.

Does this seem reasonable to you?

Can you suggest the places in the code that would be most appropriate to modify to achieve this?

**Comment by DanielRuf** [comment]
> However, I'm now thinking that a better approach would be to have Abide check for any elements with the data-invalid attribute on page load. For any matching inputs, Abide can then do its thing by adding all the mark-up in the same way it currently does for invalid inputs.

Isn't this already the case?

**Comment by br3nt** [comment]
No.  Nothing happens if you add `data-invalid` to an input.

But... I think this is the code that could be added to *foundation.abide.js* to achieve that effect:

```js
_checkInvalidInputs() {
  this.$inputs.each(($el, i) => {
    if (shouldSkipValidation($el) return;
    addErrorClasses($el);
  }
}

// extracted from `validateInput()`
function shouldSkipValidation($el) {
  // don't validate ignored inputs or hidden inputs or disabled inputs
  return $el.is('[data-abide-ignore]') || $el.is('[type="hidden"]') || $el.is('[disabled]')
}
``` 

I think `_checkInvalidInputs()` would then need to be called from `_init()`.

**Comment by DanielRuf** [comment]
I meant https://get.foundation/sites/docs/abide.html#error-state as solution. There is no such attribute like `data-invalid` that we support.

**Comment by DanielRuf** [comment]
```html
<form data-abide>
  <!-- Add role="alert" -->
  <!-- Add "display: block" -->
  <div data-abide-error class="alert callout" aria-live="assertive" role="alert" style="display: block;">
    <p><i class="fi-alert"></i> There are some errors in your form.</p>
  </div>
  <!-- Add "is-invalid-label" -->
  <label class="is-invalid-label">
    Name
    <!-- Add "is-invalid-input" -->
    <!-- Add aria-invalid="true" -->
    <input id="example4Input" aria-describedby="example4Error" type="text" required
      class="is-invalid-input" aria-invalid="true">
    <!-- Add "is-visible" -->
    <span id="example4Error" class="form-error is-visible">This field is required.</span>
  </label>
</form>
```

This should be sufficient for now. Your issue is about some new feature. For now we will fix bugs in v6 and new features are planned for v7, not v6 anymore.

**Comment by br3nt** [comment]
That’s a shame.

For when this is revisited... I suggested to attach this new functionality to ‘data-invalid’ because it one of the attributes added by ‘addErrorClasses()’ and it’s nice and short.

**Comment by DanielRuf** [comment]
Generally it is meant to work like in the error state example. The `data-invalid`attribute is not meant for this. At least there are better approaches.

Also as framework we cover only a few and the most used use cases and not such custom implementations and logic. This does not mean we are not adding this but the benefit of this feature request is very small so far and this could introduce bugs and unwanted side effects.

**Comment by br3nt** [comment]
Yes, I get that it’s meant to work like the error-state example. It’s the ‘addErrorClasses()‘ that programmatically transforms a non-error state into the error-state example you’re referring to. So it makes sense that the solution must at least call this function.

So something still needs to trigger that function. I want to make a pull request for consideration for V7, but I’m still not clear what I would be acceptable for your to act as a trigger to run ‘addErrorClasses()‘ on the requested classes.

I want to understand so I can make the best choice that works for Foundation. What is ‘data-invalid’ intended for and why is it not a good trigger? The other possibility I can think of is using ‘is-invalid-input’ class as a trigger. The reason I didn’t suggest this earlier is because it is a style mark up, not a semantic mark up.

> the benefit of this feature request is very small

This will solve a very large use case. I suspect anyone using a backend or frontend framework or a template engine to render their HTML will appreciate this feature. It doesn’t matter whether it’s Node.js, Laravel, Rails, React, Vue. Having to re-render a form with error states received after a server request (either by form submit or ajax) is a large part of rendering forms. It also doesn’t matter if we take a SSR or CSR approach. An invalid server response which requires different information from the user needs the form to be rerendered with the additional error states.

Yes, we could programmatically add the 4 different classes and attributes to every invalid element, but this is much more error prone than adding a single class/attribute to every required element manually. Especially, considering that in major version jumps, Foundation could decide to change the names or locations of those classes/attributes which would require users to update a lot of code. However, adding a single class/attribute to an invalid input and deferring to Abide to do the heavy lifting of markup means changes to the implementation would require only minor changes by users.

**Comment by pstanton** [comment]
@DanielRuf 
 
> In your case `Password needs to be greater than 10 characters.` is covered by `min-length` on the input.

min-length has some documentation somewhere? I've tried adding 

```
<input type="password" name="pass1" data-min-length="5" required placeholder="Password" />
and
<input type="password" name="pass1" min-length="5" required placeholder="Password" />
```

neither work...
