### ISSUE TITLE
No mixin named -xy-cell-properties

### ISSUE THREAD

**Issue by sofi2406** [foundation/foundation-sites#12053]
## What should happen?
Should compile.

## What happens instead?
Giving error like 
**@include -xy-cell-properties($size, $-gutter-margin, $vertical);
          ^
      No mixin named -xy-cell-properties
      in ..\node_modules\foundation-sites\scss\xy-grid\_cell.scss (line 268, column 12)**

## Possible Solution

Please add a mixing for -xy-cell-properties
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @sofi2406,

Did you update all scss files and include all files from our repo?

How did you solve it?

**Comment by G-Rath** [comment]
@DanielRuf I've having this on one of our projects, using the latest `foundation-sites` on npm.

It seems like this in [this commit](https://github.com/foundation/foundation-sites/commit/f774749a7b16c2f124cb714a043f7b527acd9921#diff-7424d0e58baf51b884325e601e3b8edd) `-xy-cells-properties` was broken up into a few new functions, but [one call was missed](https://github.com/foundation/foundation-sites/commit/f774749a7b16c2f124cb714a043f7b527acd9921#diff-7424d0e58baf51b884325e601e3b8eddR227) (you'll have to expand the file to see the highlighted line), and [still exists in the latest version](https://github.com/foundation/foundation-sites/blame/develop/scss/xy-grid/_cell.scss#L268).

Why this hasn't broken for others before I'm not entirely sure.

I'm still looking into thi, and my scss is a bit rusty so could be wrong about that being the problem. Any help looking into this would be welcomed :)

**Comment by DanielRuf** [comment]
Well, as you can read a few lines above the static method is deprecated so you can expect that it will not work at all in the future.

**Comment by DanielRuf** [comment]
Well, as you can read a few lines above, the static method is deprecated. So you can expect that it will not work at all in the future.

**Comment by G-Rath** [comment]
For sure, but it's never worked since being deprecated as far as I can tell, so you might as well just remove it in that case?

**Comment by DanielRuf** [comment]
We'll do so in v7.

**Comment by G-Rath** [comment]
Does that mean you're open to fixing this in v6, so that the deprecated function will work without erroring?

**Comment by DanielRuf** [comment]
If we have a reproducible issue (please open a new one with all relevant details) maybe. But as it is deprecated it's ok to have it broken (old code was just forgotten to be removed). We did not touch the deprecated method.

We encourage to migrate to the new method:

> Use `xy-cell()` instead with `$output: (size gutters)` to not generate the cell base.

I would label it as `wontfix` as the comments are quite clear.

**Comment by G-Rath** [comment]
Again I'm sorry but I'm not quite following: Are you saying that if I open an issue with a reproduction, you'll close it as a `wontfix`?

> But as it is deprecated it's ok to have it broken

Sure, in *major versions*, but this function was broken *in the same PR that deprecated it*, which means you made an undocumented breaking change.

> We encourage to migrate to the new method:

And I shall do so when I have the time and resources to do so - in the meantime since the method is *deprecated* but not removed, I'd expect it to continue working for at least *one* version.

------

At the very least you might as well remove the code right now since it will never work, so there's no point in waiting for v7 to remove it.

**Comment by DanielRuf** [comment]
PRs which fix this are very welcome. But we can not guarantee if and when we will release a new patch release.

For Foundation Sites 6.x are new major versions as we introduce breaking changes in them, so 6.6.0 was one (see the changelog).

v7 will be a big breaking SemVer API change.

**Comment by allthesignals** [comment]
@G-Rath did you find a workaround for this? I have seen this exact issue more than I can count (or care to remember). For a couple of reasons we are stuck with the version until we can (one day hopefully) replace Foundation with something else.

**Comment by G-Rath** [comment]
@allthesignals unfortunately I don't think so no - we ended up locking the version constraint and am in the process of moving away from foundation due to these sorts of issues.
