### ISSUE TITLE
name/value of submit buttons/inputs are not sent on submit for Abide enabled forms

### ISSUE THREAD

**Issue by br3nt** [foundation/foundation-sites#12066]
## What should happen?

When a form is submitted, the name/value pair associated with a submit button or submit input is submitted along with the other name/value pairs from other input elements.

## What happens instead?

When Abide validation is enabled on a form, the name/value pair of a submit button is **not** sent along with the other name/value pairs from other input elements.

This is caused when `e.preventDefault()` is called on the form's submit event.

To be fair, this effect happens for any form where `e.preventDefault()` is called on the submit event of a form.  But  Abide does call `e.preventDefault()` so we get this effect for Abide enabled forms.

## Possible Solution

Don't call `e.preventDefault()`.
If submit functionality needs to be overridden, `false` should be returned from the on submit callback.

## Test Case and/or Steps to Reproduce (for bugs)

This is the setup of our form:

```html
<form id="test" method="post" data-abide novalidate>
  <input type="text" name="text" required>
  <button type="submit" name="submit" value="next">Next</button>
  <button type="submit" name="submit" value="save">Save</button>
</form>
```

Now click on one of the submit buttons.

Look at the Form data sent for the request in the Network tab of dev tools.  You can see that only the name/value of the hidden field was sent:

```
text: Some text
```

Now let's override the part of Abide that causes the unexpected behaviour.  Open up the console and run the following command to remove the call to `e.preventDefault()`:

```js
$('#test').find('[type="submit"]').off('click.zf.abide keydown.zf.abide')
```

Now click on one of the submit buttons.

Look at the Form data sent for the request in the Network tab of dev tools.  You can see that the name/value pairs for both the submit button and the hidden field were sent.  This is the expected behavior.

```
text: Some text
submit: next
```

By removing `e.preventDefault()`, we regain the expected functionality where the name/value pair of the submit button is sent with the form submission.

## Context

I want to provide "Save & Exit" and "Next" next. buttons for my form.
The user will be re-directed to different pages based on which submit button they click.

Because the name/value pair of the submit button is being stripped out of the form submission, I cannot check server-side which submit input/button was clicked.

I could probably find some hacky workaround using javascript, but why should I when the default behavior of the form is being overridden by javascript in the first place?

## Your Environment
- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): Chrome
- Device, Operating System and version: Mac Mojave
- Link to your project: private project

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
I think we already had an issue about that. The button should not have the name `submit`.

Renaming it resolves it. This is because of how `$.submit()` works which is a known jQuery issue.

We won't change that again.

**Comment by DanielRuf** [comment]
See also https://foundation.discourse.group/t/submit-button-not-working/902

**Comment by DanielRuf** [comment]
> Don't call e.preventDefault().
If submit functionality needs to be overridden, false should be returned from the on submit callback.

To clarify this, we can not directly return something as we have to do further things, catch the event and run `$.submit()` and so on.

**Comment by DanielRuf** [comment]
Also see the additional notes at https://api.jquery.com/submit/

**Comment by DanielRuf** [comment]
> ```
> <form id="test" method="post" data-abide novalidate>
>   <input type="text" name="text" required>
>   <button type="submit" name="submit" value="next">Next</button>
>   <button type="submit" name="submit" value="save">Save</button>
> </form>
> ```

We use no `name="submit"` in our doc for good reasons ;-)

The second form works here:

https://codepen.io/DanielRuf/pen/RwWjVKj

**Comment by DanielRuf** [comment]
The following works:

https://codepen.io/DanielRuf/pen/RwWjVKj

```
<form id="test2" method="post" data-abide novalidate>
  <input type="text" name="text2" required>
  <button class="submit" name="submit" value="next">Next</button>
  <button class="submit" name="submit" value="save">Save</button>
</form>
```

**Comment by DanielRuf** [comment]
The following works:

https://codepen.io/DanielRuf/pen/RwWjVKj

```
<form id="test" method="post" data-abide novalidate>
  <input type="text" name="text" required>
  <button class="submit" name="submit" value="next">Next</button>
  <button class="submit" name="submit" value="save">Save</button>
</form>
```

**Comment by br3nt** [comment]
Ahh... damn... the example I provided was not correct. 

Please let me restate my case and reconsider on the following evidence.

Firstly, the name of the buttons or inputs is irrelevant. 

Both of the following examples do not work (the key/value for the button/input is not sent).
I have added a codepen for demonstration: https://codepen.io/br3nt/pen/pojdwog?editors=1010

```html
<form id="test" method="post" data-abide novalidate>
  <h1>Example: &ltbutton type="submit"&gt</h1>
  <input type="text" name="text" required>
  <button class="button" type="submit" name="example1" value="next">Next</button>
  <button class="button" type="submit" name="example1" value="save">Save</button>
</form>

<form id="test" method="post" data-abide novalidate>
  <h1>Example: &ltinput type="submit"&gt</h1>
  <input type="text" name="text" required>
  <input class="button" type="submit" name="example2" value="next">
  <input class="button" type="submit" name="example2" value="save">
</form>
```

> To clarify this, we can not directly return something as we have to do further things, catch the event and run $.submit() and so on.

Please disregard my comment about returning `false`.  This comment is regarding canceling form submission which is not applicable in this example.

However, what is relevant is the call to `e.preventDefault()`.  It should **not** be made. Not only is this call unnecessary, but it is also the cause of the problem that I have outlined.

As you pointed out, *phpfui* also pin-pointed `e.preventDefault()` as the problem in [the link you provided](https://foundation.discourse.group/t/submit-button-not-working/902).

The pull request, #12067, fixes the problem that has been outlined twice now.

Please reconsider this issue as a valid problem and PR #12067 as a valid solution.

**Comment by br3nt** [comment]
For anyone encountering this issue, the following code can be used to override the problematic code:

```html
// put this after your form
$(document).ready(() => {
  $("form").find('[type="submit"]').off('click.zf.abide keydown.zf.abide')
})
```

**Comment by DanielRuf** [comment]
It was added in https://github.com/foundation/foundation-sites/commit/f237c0ffeb0d82b63410deebdd8cc9ef4943ebde

See also https://github.com/foundation/foundation-sites/pull/11613

The linked forum topic mentiones different solutions which all work like in my codepen. As this is technically not broken when using the code from my codepen we will not change that for now.

**Comment by DanielRuf** [comment]
> However, what is relevant is the call to `e.preventDefault()`. It should **not** be made. Not only is this call unnecessary, but it is also the cause of the problem that I have outlined.

No, the element is the problem. This is a jQuery issue. Please check my codepen which works for me.

The issue is known in jQuery for a very long time and there are multiple relevant issues and bug report about this:
https://stackoverflow.com/a/14175782/753676
https://bugs.jquery.com/ticket/4652
https://github.com/jquery/jquery/issues/2321#issuecomment-102667799

**Comment by DanielRuf** [comment]
It was added in https://github.com/foundation/foundation-sites/commit/f237c0ffeb0d82b63410deebdd8cc9ef4943ebde

See also https://github.com/foundation/foundation-sites/pull/11613

The linked forum topic mentions different solutions which all work like in my codepen. As this is technically not broken when using the code from my codepen we will not change that for now.

> However, what is relevant is the call to `e.preventDefault()`. It should **not** be made. Not only is this call unnecessary, but it is also the cause of the problem that I have outlined.

No, the element is the problem. This is a jQuery issue. Please check my codepen which works for me.

The issue is known in jQuery for a very long time and there are multiple relevant issues and bug report about this:
https://stackoverflow.com/a/14175782/753676
https://bugs.jquery.com/ticket/4652
https://github.com/jquery/jquery/issues/2321#issuecomment-102667799

**Comment by br3nt** [comment]
The submit buttons in your codepen don't have `type="submit"` and so your example doesn't experience the problem because the event handler from line 67 doesn't get triggered because the buttons don't have `type="submit"`.

**Comment by DanielRuf** [comment]
> The submit buttons in your codepen don't have `type="submit"` and so your example doesn't experience the problem because the event handler from line 67 doesn't get triggered because the buttons don't have `type="submit"`.

Did you try to click the buttons without any input? It does the validation step, so I see nothing wrong here.

**Comment by br3nt** [comment]
Yes.  Leaving the input blank triggers the validation step and marks up the input as expected.
However, when you enter text in the text field and submit the form, it's the key/value from the submit button that doesn't get submitted along with the input's key/value.

**Comment by DanielRuf** [comment]
https://github.com/foundation/foundation-sites/issues/12066#issuecomment-623112513

Please see the linked issues from the jQuery bugreports for the submit/serialize method.

**Comment by DanielRuf** [comment]
We could change it to the native submit method (https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit) but so far the `e.preventDefault()` is required and we will not remove it in the current version.

@SassNinja what do you think?

**Comment by DanielRuf** [comment]
We could change it to the native submit method (https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit) but so far the `e.preventDefault()` is required and we will not remove it in the current version.

@SassNinja what do you think?

As `type="submit"` is duplicate using `<button>` without it hould be sufficient.

**Comment by DanielRuf** [comment]
We could change it to the native submit method (https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit) but so far the `e.preventDefault()` is required and we will not remove it in the current version.

@SassNinja what do you think?

As `type="submit"` is duplicate using `<button>` without it should be sufficient.

**Comment by DanielRuf** [comment]
The result of dynamically triggered `submit()` is expected, even in vanilla JS.
So if you want this value you have to use one of the workarounds (no `type="submit"` and so on.

Also see https://stackoverflow.com/a/1709352/753676

**Comment by br3nt** [comment]
I've updated the pen with a third example that does the same thing but with `e.dreventDefault()` commented out and it seems to working as expected and also sends the submit buttons key/value.

I don't know how example 3 can be working if it is `this.$element.submit()` that is the problem.

Also, if you use an input instead of a button, `type="submit"` is required and is perfectly reasonable HTML.

I really don't mean to be a pain about this.  It's just a really annoying "feature" that is causing some unnecessary obscure edge cases.

Well, at least it's documented again.
