### ISSUE TITLE
check backticks / code parts in docs

### ISSUE THREAD

**Issue by DanielRuf** [foundation/foundation-sites#12062]
## Expected Behavior

It should be displayed as `code`.

## Current Behavior

We can see the backticks at https://get.foundation/sites/docs/drilldown-menu.html#_showmenu

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by apriljunge** [comment]
It looks like this is an issue of [Panini](https://github.com/foundation/panini) as this section is autogenerated from [sources](https://github.com/foundation/foundation-sites/blob/develop/js/foundation.drilldown.js#L397).

**Comment by DanielRuf** [comment]
This was already resolved by fixing the parsing of the files.
