### ISSUE TITLE
Auto sized cells are pushed outside the grid

### ISSUE THREAD

**Issue by eleikopetter** [foundation/foundation-sites#12069]
## What should happen?

It would be nice if Auto sized cells took the appropriate space on a new "row" if the previous cell(s) add up to the full width.

## What happens instead?

Auto sized cells are pushed outside the grid unless you have grid-padding-x applied.

The behaviour is inconsistent with or without grid-padding.

## Possible Solution

Changing to flex-basis: auto for .cell

How come it's 0px for cell.auto?

## Test Case and/or Steps to Reproduce (for bugs)

https://codepen.io/pettere/pen/VwvyqbJ

## Context

A component with dynamic data where the number of columns is not predetermined and you can use a full width cell to break to a new "row" of cells.

## Your Environment

- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): Chrome
- Device, Operating System and version: WIndows 10
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
For me it looks like this in Firefox when I open your codepen:

![grafik](https://user-images.githubusercontent.com/827205/81114114-abf6ea80-8f21-11ea-9b01-84574d233a49.png)

**Comment by DanielRuf** [comment]
Hi @eleikopetter,

it was / is like this for a very long time now. See https://github.com/foundation/foundation-sites/commit/ceb01d403f097e8a364d6f39ecb8f4c8954afbd0

**Comment by DanielRuf** [comment]
I think your case is a specific corner case / use case which requires some additional styles.

https://get.foundation/sites/docs/xy-grid.html

Normally you build them semantically like this: https://codepen.io/DanielRuf/pen/ZEbvwZE

**Comment by eleikopetter** [comment]
Fair enough! Thanks for your help. Appreciate it.
