### ISSUE TITLE
UglifyJS and Reveal component - In strict mode code, functions can only be declared at top level or immediately within another function. [./node_modules/foundation-sites/js/foundation.reveal.js:284,6]

### ISSUE THREAD

**Issue by fclaussen** [foundation/foundation-sites#12065]
## What should happen?
Using webpack to compile, it should compile the JS (using the explicit-pieces.js file) without any issues.

## What happens instead?
We get an error when we uncomment the Reveal component in explicit-pieces.js
`ERROR in js/app.js from UglifyJs
In strict mode code, functions can only be declared at top level or immediately within another function. [./node_modules/foundation-sites/js/foundation.reveal.js:284,6][js/app.js:13135,8]`

After a lot of digging, I figured the problem was with the package-lock. It works when I copy the same lock as another project has the same build. I tested just swapping the foundation-sites piece of the lock file but that didn't work. It most likely has to do with an UglifyJS update or maybe even Babel.

## Test Case and/or Steps to Reproduce (for bugs)
https://codesandbox.io/s/misty-hill-phv85
It's my first time using this site so I think you need to fork this sandbox to be able to use a terminal.
Then you want to run `rm -fr node_modules/` just to be safe and then `npm install` and then `npm run prod`

You will see two package-lock.json files there. One that works and one that doesn't.
Just rename the files and repeat the steps above.

## Context
This affects me big time. I now have a precious package-lock that I need to keep using for new projects otherwise it won't compile if I want to use the Reveal component.

## Your Environment

- Foundation version(s) used: 
package.json says: "foundation-sites": "^6.5.0-rc.3",
working lock says: 
```
"foundation-sites": {
      "version": "6.5.3",
      "resolved": "https://registry.npmjs.org/foundation-sites/-/foundation-sites-6.5.3.tgz",
      "integrity": "sha512-ZwI0idjHHjezh6jRjpPxkczvmtUuJ1uGatZHpyloX0MvsFHfM0BFoxrqdXryXugGPdmb+yJi3JYMnz6+5t3K1A==",
      "dev": true
    },
```
non-working lock says:
```
"foundation-sites": {
      "version": "6.6.3",
      "resolved": "https://registry.npmjs.org/foundation-sites/-/foundation-sites-6.6.3.tgz",
      "integrity": "sha512-8X93wUAmUg1HhVv8uWMWnwoBLSQWSmFImJencneIZDctswn724Bq/MV1cbPZN/GFWGOB/9ngoQHztfzd4+ovCg==",
      "dev": true
    },
```
- Device, Operating System and version: Macbook Pro, Webpack 4 and Node v10.16.3

## Checklist
- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @fclaussen ,

This is a problem with uglify. You can use terser instead of the old uglifyjs.

**Comment by DanielRuf** [comment]
Related: https://github.com/foundation/foundation-sites/issues/11628

**Comment by DanielRuf** [comment]
Hi @fclaussen,

This is a problem with uglify. You can use terser instead of the old uglifyjs.

You can also disable the strict mode.

Related: #11628

**Comment by DanielRuf** [comment]
Please try https://webpack.js.org/plugins/terser-webpack-plugin/

**Comment by fclaussen** [comment]
@DanielRuf The strict mode is actually happening on the Reveal file.

Replacing UglifyJS with Terser seems to have worked too!

Thanks
