### ISSUE TITLE
Abide filter the button value in the form

### ISSUE THREAD

**Issue by arjen-t** [foundation/foundation-sites#12071]
## What should happen?
The (submit)button in the form contains the property name.
When user fulfilled the abide form validation. The button value should be provided in the request.

## What happens instead?
The (submit)button value gets never send in the request.

## Possible Solution

Unknown. I notice this behaviour occurs from version 6.6.0 and above.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/arjen-t/pen/mdeXJRW

How to reproduce >= 6.6.0
1. Run form validation with any jquery version and a foundation version >= 6.6.0
2. fulfill form validation with abide
3. Request does not contain the (submit)button value

How to reproduce with version < 6.6.0
1. Run form validation with any jquery version and a foundation version < 6.6.0
2. fulfill form validation with abide
3. Request does contain the (submit)button value

I tested both cases with all kind of JQuery versions (3.5.1, 3.4.1,  1.12.0). Whatever JQuery version I used the behaviour (Foundation >= 6.6.0) stays the same.

## Context

With version >= 6.6.0 we are not able to handle mulitple form requests on a page.

## Your Environment

- Foundation version(s) used: >= 6.6.0 
- Browser(s) name and version(s): Chrome (81.0.4044.138)
- Device, Operating System and version:  Windows 10
- Link to your project:

**Comment by DanielRuf** [comment]
> The (submit)button in the form contains the property name.

Since 6.6.0 we use `jQuery.submit()`. Forms which are submitted using JS do not contain the submit button in the request data.

This is known. Please see https://github.com/jquery/jquery/issues/2321#issuecomment-102667799 and https://github.com/foundation/foundation-sites/issues/12066 for multiple workarounds.

Closing as duplicate.

**Comment by arjen-t** [comment]
Thanks for your feedback and additional info, much appreciated!
