### ISSUE TITLE
$buttongroup-spacing variable not working -- Foundation 6.6.3

### ISSUE THREAD

**Issue by amygilbert** [foundation/foundation-sites#12074]
## What should happen?
When I set the $buttongroup-spacing variable in the _settings.scss file to something other than 1px, the gaps between the buttons should change in the button group. 

This worked in 6.6.1. Since there was an update to the button-group css in 6.6.2, that may be when it was introduced. 

## What happens instead?

The setting doesn't have any effect on the spacing in the button group.

## Possible Solution

I have a workaround in my own scss like this:
```
.button-group {
  .button:not(:last-child) {
    margin: 0 $global-margin $global-margin 0;
  }
  @include breakpoint(large) {
    &.stacked-for-medium .button:not(:last-child) {
      margin: 0 $global-margin 0 0;
    }
  }
  @include breakpoint(medium) {
    &.stacked-for-small .button:not(:last-child) {
      margin: 0 $global-margin 0 0;
    }
  }
}
```
I am also doing a margin bottom to create a gap between them when stacked but that is not an issue since there isn't a variable for that -- though maybe there should be.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/amygilbert/pen/QWjxEZJ
I made this codepen though I'm not sure if variables are supported in codepen

How to reproduce:
1. Create a button group
2. Set variable $buttongroup-spacing to anything other than 1px

## Context

...

## Your Environment

- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- Device, Operating System and version: Windows 10 Version 10.0.18363 Build 18363
- Link to your project: https://phoenixsoftware.com/support_ejes.htm (this links to my live site, still on 6.6.1 which has a button group properly spaced using the $buttongroup-spacing variable.

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @amygilbert,

thanks for reporting this. We will check that.

**Comment by DanielRuf** [comment]
The variable is defined at https://github.com/foundation/foundation-sites/blob/v6.6.3/scss/components/_button-group.scss#L15 and used at https://github.com/foundation/foundation-sites/blob/v6.6.3/scss/components/_button-group.scss#L34

I can still see them used at https://github.com/foundation/foundation-sites/blob/v6.6.3/scss/components/_button-group.scss#L56-L57

This should normally work:

<img width="1189" alt="Bildschirmfoto 2020-05-11 um 20 02 59" src="https://user-images.githubusercontent.com/827205/81595253-768b4a80-93c2-11ea-9588-da9a8a56f3a0.png">

**Comment by DanielRuf** [comment]
Basically this is not how SCSS works at Codepen. The part in the SCSS section is loaded after the CSS file and this does nothing in combination with the CSS file.

**Comment by DanielRuf** [comment]
I have tested it and I can not reproduce it. When I set `buttongroup-spacing` to `10px` I also see it in the generated code and it is applied to the elements.

<img width="692" alt="Bildschirmfoto 2020-05-11 um 20 20 30" src="https://user-images.githubusercontent.com/827205/81596815-ff0aea80-93c4-11ea-9378-46cc6f025184.png">

**Comment by DanielRuf** [comment]
We nee d a reproducible testcase where we can actually see the issue - without any further changes made by you.

**Comment by amygilbert** [comment]
Inspecting it in Chrome, I see what is overriding it: https://github.com/foundation/foundation-sites/blob/develop/scss/components/_button-group.scss#L119

**Comment by DanielRuf** [comment]
The code that you linked is ~4 years old:

<img width="1016" alt="Bildschirmfoto 2020-05-11 um 20 31 56" src="https://user-images.githubusercontent.com/827205/81597760-8573fc00-93c6-11ea-86f6-f3756b076795.png">

**Comment by amygilbert** [comment]
Installing 6.6.3 changed my formatting. I was simply reporting a bug. I can live with my workaround

**Comment by DanielRuf** [comment]
It seems https://github.com/foundation/foundation-sites/commit/fb8d42e4d3a4729d0740c9bf0042a8f586491496#diff-d0689b3f481699857ae2680a820ff6aaR101 added the problematic code.

**Comment by amygilbert** [comment]
Yes, I am using expanded buttons. I did link to my current site which also uses expanded buttons

**Comment by amygilbert** [comment]
Yes. That looks like it. Thanks

**Comment by DanielRuf** [comment]
It seems the history is confusing as my PR introduced other changes - it looks like it has to do with changes in the `develop` branch.

I will prepare a PR to remove this change in the line that you pointed to.
