### ISSUE TITLE
move away from jQuery?

### ISSUE THREAD

**Issue by trymeouteh** [foundation/foundation-sites#12076]
Will Foundation move away from jQuery? I know it is useful but I think it is better if Foundation had no dependencies and JavaScript has come a long ways, making it so jQuery is not needed for developing JS quickly.

Or even to have Foundation not require jQuery and have a optional jQuery integration JS script to allow people to use jQuery with Foundation if they wish.

**Comment by DanielRuf** [comment]
Hi @trymeouteh,

this is planned for Foundation Sites 7.

#11687
