### ISSUE TITLE
$enable-cite-block is missing !default from scss

### ISSUE THREAD

**Issue by alexkuc** [foundation/foundation-sites#12072]
## What should happen?

According to [docs](https://get.foundation/sites/docs/typography-base.html#blockquotes), it should be possible to disable styling of `<cite>…</cite>` tag using `$enable-cite-block` in `_settings.scss`.

## What happens instead?

Foundation framework styles `<cite>…</cite>` tag regardless of the value of `$enable-cite-block`

## Possible Solution

File `scss/typography/_base.scss` on the [L200](https://github.com/foundation/foundation-sites/blob/f6dc0a5c91945a0ea1b6fc8e6866a97f781ae9d4/scss/typography/_base.scss#L200) is missing `!default`.

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:

1. `git clone https://github.com/alexkuc/foundation-sites-cite-block-bug`
2. `yarn`
3. `yarn build`
4.  `yarn start` or use alternative hosting such as nginx or apache
5. navigate to `http://localhost:8888/` in order to open `index.html` which should be:

![Screenshot 2020-05-07 20 55 56](https://user-images.githubusercontent.com/3331946/81328847-3f592880-90a6-11ea-8e15-b535c61d1cb5.png)

but instead it is:

![Screenshot 2020-05-07 20 56 11](https://user-images.githubusercontent.com/3331946/81328863-46803680-90a6-11ea-94ae-6aafe6f575ef.png)

## Context

Not possible to disable formatting of `<cite>…</cite>` so I guess the context is typograhpy / custom css?

## Your Environment

- Foundation version(s) used: `foundation-sites@6.6.3`
- Browser(s) name and version(s): `Version 81.0.4044.129 (Official Build) (64-bit)`
- Device, Operating System and version: `OSX 10.13.61`
- Link to your project: https://github.com/alexkuc/foundation-sites-cite-block-bug

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @alexkuc,

thanks for the hint. It seems it slipped through in https://github.com/foundation/foundation-sites/commit/c9fd9d7344cf3b391af75d5cf1d55dee8cd60282

And the same applies to `$enable-code-inline`.
Do you want to provide a PR which fixes this?

**Comment by alexkuc** [comment]
@DanielRuf I have created PR #12073. I hope I followed the format of the guidelines correctly (template and [CONTRIBUTING.md](https://github.com/foundation/foundation-sites/blob/develop/CONTRIBUTING.md)). If I made a mistake, please let me know so I can fix it. Thank you!

**Comment by DanielRuf** [comment]
@alexkuc thank you for your contribution. I will check this when I find some time.
