### ISSUE TITLE
Stackable media objects not behaving correctly

### ISSUE THREAD

**Issue by lguariento** [foundation/foundation-sites#12092]
I have a structure like so:

```
<div class="grid-container fluid">
    <div class="grid-x grid-margin-x fluid" id="content">
        <div class="cell medium-offset-1 medium-7 small-12>
            <div class="content-section">
                <div class="media-object stack-for-small">
                    <div class="media-object-section"> # object1
                        <div class="thumbnail">
                            <img src="">
                        </div>
                   </div>
                   <div class="media-object-section"> # object 2
                   [....]      
                   </div>
                </div>
            </div>
        </div>

        <div class="cell medium-3 columns small-12">
        Upcoming events...
        </div>
    </div>
</div>
```

For large and small screen it works as expected: the stackable items are stacked in small screens and one next to the other for large. The issue is for medium-size displays, where this happens (this is an iPad):

![HqSwJ](https://user-images.githubusercontent.com/10143842/84754979-02435880-afb9-11ea-9b44-fea02a0e66a7.png)

Am I overlooking something obvious?

**Comment by DanielRuf** [comment]
Hi @lguariento,

please provide a codepen which uses the latest version of Foundation Sites (v6.6.3) and which reproduces this so we can check this in detail.

**Comment by lguariento** [comment]
Hello, here it is:

https://codepen.io/lguariento/pen/xxZEzOL?editors=1100

**Comment by DanielRuf** [comment]
By default we use the `$-zf-zero-breakpoint` (which is `small`) and compile the CSS for it there. And this applies it just to the breakpoint small and not medium or others.

See https://github.com/foundation/foundation-sites/blob/v6.6.3/scss/components/_media-object.scss#L66 and https://github.com/foundation/foundation-sites/blob/v6.6.3/scss/components/_media-object.scss#L36

If you need it for medium too you can either use the scss version and generate the needed styles using the media-object-stack mixin (https://get.foundation/sites/docs/media-object.html#media-object-stack) or create the needed CSS class manually.

https://github.com/foundation/foundation-sites/blob/v6.6.3/dist/css/foundation.css#L3522

I have done this at https://codepen.io/DanielRuf/pen/LYGRBpq?editors=1100 and added a few spaces and soft hyphens for better automatic text breaks.

**Comment by lguariento** [comment]
I've quite new to the scss version, although I guess I'll have to give it a try at some point. Your edits to the codepen makes it look MUCH better now! Thank you for the details and the workaround.
