### ISSUE TITLE
[Drilldown Menu] data-back-button broken

### ISSUE THREAD

**Issue by NiklasBr** [foundation/foundation-sites#12095]
## Expected Behavior

When using the `data-back-button` attribute it should take effect.
...

## Current Behavior

The default is never orverridden.
...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/ncoden/pen/dQmVgg

```html
<nav class="navigation__mobile" role="navigation">
  <ul class="vertical menu drilldown" data-drilldown>
    <li><a href="/products">Products</a>
      <ul class="vertical menu nested">
        <li><a href="/products"><span>navigation.label.view-all-in</span> Products</a></li>
        <li><a href="/NO/products/linjemateriell-transmisjon36-kv">Linjemateriell</a>
          <ul data-back-button="&lt;li class=&quot;js-drilldown-back&quot;&gt;&lt;a tabindex=&quot;0&quot;&gt;navigation.label.return-toProducts&lt;/a&gt;&lt;/li&gt;" class="vertical menu nested">
            <li><a href="/NO/products/linjemateriell-transmisjon36-kv"><span>navigation.label.view-all-in</span> Linjemateriell</a></li>
            <li><a href="/NO/products/linjemateriell-transmisjon36-kv/isolatorer">Isolatorer</a>
              <ul data-back-button="&lt;li class=&quot;js-drilldown-back&quot;&gt;&lt;a tabindex=&quot;0&quot;&gt;navigation.label.return-toLinjemateriell - Transmisjon&gt;36 kV&lt;/a&gt;&lt;/li&gt;" class="vertical menu nested">
                <li><a href="/NO/products/linjemateriell-transmisjon36-kv/isolatorer"><span>navigation.label.view-all-in</span> Isolatorer</a></li>
                <li><a href="/NO/products/linjemateriell-transmisjon36-kv/isolatorer/isolatorer-hengestrekk-transmisjon-725-kv">Isolatorer - transmisjon</a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </li>
  </ul>
</nav>
```

How to reproduce:
1. Add the `data-back-button` to items in the drilldown navigation

## Context

We would like to add the previous level as an indicator to the navigation
...

## Your Environment

- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): Firefox 77
- Device, Operating System and version: Windows 10, MacOS 10.13.6
- Link to your project: -

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @niklam,

options have to be set on the component. So you have to add the `data-back-button` after `data-drilldown`. Not in a ul or li element some levels under it.

https://codepen.io/DanielRuf/pen/mdVOKza?editors=1000

If you need a custom back button, try watching the events triggered by the drilldown menu like `open.zf.drilldown` and others and interactively update the button content:

https://get.foundation/sites/docs/drilldown-menu.html#js-events

**Comment by DanielRuf** [comment]
Related: https://github.com/foundation/foundation-sites/issues/9352

**Comment by NiklasBr** [comment]
> https://codepen.io/DanielRuf/pen/mdVOKza?editors=1000

This didn't work, it has the same text on all levels, which doesn't make any sense.

**Comment by DanielRuf** [comment]
> If you need a custom back button, try watching the events triggered by the drilldown menu like open.zf.drilldown and others and interactively update the button content:

**Comment by DanielRuf** [comment]
We do not natively support different back button texts per level so you have to create a custom solution.

What you request is a new feature, this is not a bug.

**Comment by NiklasBr** [comment]
Occasionally the line between unclear/missing documentation, missing functionality, and bugs are blurred.

**Comment by DanielRuf** [comment]
> Occasionally the line between unclear/missing documentation, missing functionality, and bugs are blurred.

![image](https://user-images.githubusercontent.com/827205/85010364-2beab400-b160-11ea-9f64-d498204111d1.png)

![image](https://user-images.githubusercontent.com/827205/85010402-39a03980-b160-11ea-839e-8e221610b3ac.png)

![image](https://user-images.githubusercontent.com/827205/85010456-550b4480-b160-11ea-8289-106849dcb70d.png)


Well, how plugins can be configured is described in the docs and also in the examples. For the options we look only at the top level where the component is initialized using the data-plugin attribute.

**Comment by DanielRuf** [comment]
Please keep in mind that frameworks like Foundation Sites, Bootstrap and more only cover the most common use cases. If you need a special use case or custom behavior you always have to write some custom JS with your desired business logic.

What can we improve in the docs to make it more clear?

In general your downvote is not that helpful, especially because frameworks always cover the most common use cases and are the "foundation" (pun not intended) of the whole project.
