### ISSUE TITLE
Please consider to make it ready to use in Vue

### ISSUE THREAD

**Issue by simar88** [foundation/foundation-sites#12090]
I love Foundation, i use it for almost all of my web based project.
Recently i started use Vue for some ideas and i love it too.
I'm using Foundation combined with it, but sometimes i need to refresh component by myself or attach some events to adapt behaviours.
Please consider to make a version or similar, ready to use together with Vue.
I think that other people other then me will appreciate it.
Thanks for your works

**Comment by DanielRuf** [comment]
Hi @simar88,

there may be already solutions from the community. See https://github.com/search?q=foundation+vue

For example https://github.com/vue-foundation/vue-foundation

We may improve this in Foundation v7.
