### ISSUE TITLE
window.default is set to contain the foundation object

### ISSUE THREAD

**Issue by macdabby** [foundation/foundation-sites#12096]
## What should happen?

Including the foundation.js file should make Foundation and other plugins available on a page. It does so by filling in window[Foundation] = .... and window[Abide] ...., etc

https://github.com/foundation/foundation-sites/blob/develop/dist/js/foundation.js#L8

## What happens instead?

In the list of plugins to include, there is a `default` which ultimately overwrites `window.default` when this file is included in the browser:

https://github.com/foundation/foundation-sites/blob/develop/dist/js/foundation.js#L103

This causes issues with other js applications running in the page.

## Possible Solution

Can the default be removed from this? I have tested with `delete window.default` after the file loads and everything seems to work fine.

## Test Case and/or Steps to Reproduce (for bugs)

<script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/js/foundation.min.js"></script>
<script>
console.log(window.default);
</script>

## Context

Somehow this interferes with other applications because it's affecting the global namespace

## Your Environment
- Foundation version(s) used:  6.6.3
- Browser(s) name and version(s): chrome, firefox
- Device, Operating System and version: mac os

## Checklist
- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
> In the list of plugins to include, there is a `default` which ultimately overwrites `window.default` when this file is included in the browser:

Well, simple solution:

don't expect that globals are safe

> This causes issues with other js applications running in the page.

Which applications sets / uses `window.default`?

In general webpack transpiles the `default` export to this:
`/* harmony default export */ __webpack_exports__["default"] = (_foundation_core__WEBPACK_IMPORTED_MODULE_1__["Foundation"]);`

See https://github.com/foundation/foundation-sites/blob/develop/js/foundation.js#L36 and the descriptions at https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/export

The default export is needed for the ESM and CJS packages in Nodejs (`require(packagename).default`).

**Comment by DanielRuf** [comment]
Just a short example why it is a bad idea to use `window` globals:

https://codepen.io/DanielRuf/pen/vYLyrKd?editors=1111

When you use Foundation Sites in a Nodejs project and bundle it, there should be normally no global objects then as this is scoped then.

**Comment by DanielRuf** [comment]
> Can the default be removed from this?

It is safe to remove but we won't change the bundles. This is the first time that someone mentioned the window globals and that there might be conflichts with other libraries. In this case these libraries should never rely on `window.default` as you can see in my codepen.

**Comment by macdabby** [comment]
Yeah, I understand I shouldn't trust globals, but then why is this script modifying them?
The module I'm having issues with is video.js. Essentially at some point, it complains that `window.setTimeout` doesn't exist.

I don't know much about how this works in a nodejs project honestly, I'm using it on a PHP project by including it in a script tag.

**Comment by DanielRuf** [comment]
This is how webpack writes the exports.

**Comment by DanielRuf** [comment]
> Essentially at some point, it complains that window.setTimeout doesn't exist.

We don't remove or unset this.
In this case please open a bugreport in video.js regarding the global window object.

**Comment by DanielRuf** [comment]
See https://github.com/videojs/video.js/issues/5758
