### ISSUE TITLE
Disable tab

### ISSUE THREAD

**Issue by nitinsinghal123** [foundation/foundation-sites#12108]
Hi

Can you please tell me how to disable a tab ? I can't find anything in the documentation.

I am using version 6.

Regards

**Comment by DanielRuf** [comment]
Hi @nitinsinghal123,

can you provide more information and some codepen so we can better understand what you mean?

**Comment by nitinsinghal123** [comment]
Hi @DanielRuf 

I am just trying an example on the page: https://get.foundation/sites/docs/tabs.html

Under Basics heading, when you go down a bit lower you can see Tab 1 to Tab 6. Out of these 6 tabs, lets say I want to disable Tab 4. It should be visible, but not clickable.  

Regards

**Comment by DanielRuf** [comment]
There is no such feature in Foundation Sites.
You may want to create a custom class to apply the needed styles and use `pointer-events: none` or a different solution.

Keep in mind that you can still open it using the JS methods of the tabs component.

**Comment by nitinsinghal123** [comment]
Thanks @DanielRuf for the suggestion.

**Comment by DanielRuf** [comment]
What did you try so far? `_handleTabChange` is a method, you may want to listen for the events.

**Comment by nitinsinghal123** [comment]
No, I haven't tried _handleTabChange. I am looking for a working example for this. 

I have tried jQuery way & that is working fine, But I want to try foundation Tab's method to solve this.

This is what I have tried & it is working fine for me:

`jQuery("[data-tabs] > li > a.dsbl").bind("click", function(e) {
    e.preventDefault();
    e.stopImmediatePropagation();
    e.stopPropagation();
});`

Regards

**Comment by DanielRuf** [comment]
The method is to trigger the change, not to catch / listen for it.
Yes, your solution is valid (adding another listener and catch the event bubbling from the element and stop / cancel it).

Closing as resolved as there are mayn ways to get the desired result.
