### ISSUE TITLE
Broken link on download page

### ISSUE THREAD

**Issue by KHiis** [foundation/foundation-sites#12112]
Ideally the https://get.foundation/emails/getting-started.html `Download the boilerplate` should send to download link, but currently it serves the https://get.foundation/downloads/foundation-emails.zip - right one would be https://s3.amazonaws.com/zurb-foundation/foundation-emails.zip

**Comment by DanielRuf** [comment]
Thanks for reporting this. We will fix this in https://github.com/foundation/foundation-marketing/tree/master/src/pages/emails

**Comment by DanielRuf** [comment]
Should be fixed with https://github.com/foundation/foundation-marketing/commit/d9f53a40bd521d760cea082fc4189e0e7fb82c2a
