### ISSUE TITLE
$.imagemin.jpegtran is not a function

### ISSUE THREAD

**Issue by kevinmu17** [foundation/foundation-sites#12113]
## What should happen?
Foundation watch fires this error and breaks completely

## What happens instead?
jpegtran is no more

## Possible Solution
it should be replaced with $.imagemin.mozjpeg. I want to do a pull request, but i can't find this issue.
It is located in the root file: 
gulpfile.babel.js 
line 144

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
1. $ foundation new
2. choose: A website (Foundation for Sites)
3. choose: project name
4. choose: ZURB Template: includes Handlebars templates and Sass/JS compilers
5. $ foundation watch

## Context
it's annoying since this has to be fixed manually every time I start a new project

## Your Environment
- Foundation version(s) used: 6.6.3

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi, thanks for reporting this.

You probably mean https://github.com/foundation/foundation-zurb-template.

**Comment by kevinmu17** [comment]
Yeah thats the one, thanks! but the PR is disabled, how can i make a PR on https://github.com/foundation/foundation-zurb-template

**Comment by DanielRuf** [comment]
Closing as this should be resolved with the next release, the PR was merged. Thanks for your contribution.
