### ISSUE TITLE
[Starter Projects] Custom download is a webpack project file

### ISSUE THREAD

**Issue by MarkHTML** [foundation/foundation-sites#12116]
Firstly, I don't use webpack so sorry if I am missing something here but I assumed custom downloads would remain the same and not be webpack projects files that need to be processed again by webpack or somthing.

## Expected Behavior
When you do a custom download you get the jquery dependent foundation.js file as per the starter projects example video

... 

## Current Behavior
You get a webpack file with a bunch of eval() javascript functions which is no good for normal installations.

...

## Test Case and/or Steps to Reproduce (for bugs)

Go to https://download.get.foundation/sites/download/#customizeFoundation

Select some custom options

Download and extract files

open foundation.js

See all the webpack nonsense instead of usual var Foundation version = '6.6.3' etc at the top

## Context
I can no longer download a custom version of foundation and copy and paste these files into my project, the webpack version doesn't load in a web browser. Do you want me to have to use webpack with custom downloads now?

...

## Your Environment
- Foundation version(s) used: Latest (6.6.3)
- Browser(s) name and version(s): Any
- Device, Operating System and version: Windows 10

**Comment by DanielRuf** [comment]
> Go to [download.get.foundation/sites/download/#customizeFoundation](https://download.get.foundation/sites/download/#customizeFoundation)

This is the customizer which uses gulp + webpack.

You do not have to add webpack or anything else. The generated files are self-contained and have only the standalone webpack-loader. Nothing special so far.

**Comment by DanielRuf** [comment]
What exact error do you get?

**Comment by MarkHTML** [comment]
Thanks for your quick response.

I get 'Foundation.onImagesLoaded is not a function'

**Comment by MarkHTML** [comment]
> > Go to [download.get.foundation/sites/download/#customizeFoundation](https://download.get.foundation/sites/download/#customizeFoundation)
> 
> This is the customizer which uses gulp + webpack.
> 
> You do not have to add or use webpack or anything else. The generated files are self-contained and have only the standalone webpack-loader. Nothing special so far.

Thanks for explaining the stack here. I was concerned opening up foundation.js and seeing webpack and the use of 'eval()', developers always come at me with pitchforks because of security concerns of using this function on sites so I was concerned.

**Comment by DanielRuf** [comment]
> Thanks for explaining the stack here. I was concerned opening up foundation.js and seeing webpack and the use of 'eval()', developers always come at me with pitchforks because of security concerns of using this function on sites.

This is no problem in this context. This is how webpack generates the code.

If you need the pure JS builds, why not use https://unpkg.com/foundation-sites@6.6.3/dist/js/foundation.js or https://unpkg.com/foundation-sites@6.6.3/dist/js/foundation.min.js?

Can you provide a reproducible testcase? For me it looks as some code calls `Foundation.onImagesLoaded` but it is not included or not called the correct way.

Because it is included for a very long time: https://github.com/foundation/foundation-sites/search?q=onImagesLoaded&unscoped_q=onImagesLoaded

So far we did not see this error with the builds.

**Comment by MarkHTML** [comment]
It's a bug with my code, thanks for confirming. I will try the pure js version.
