### ISSUE TITLE
[XY Grid] Shrink issue with getting vertical scroll

### ISSUE THREAD

**Issue by Niklasos** [foundation/foundation-sites#12123]
## Expected Behavior
When having a long text in a container with shrink class on the container it should(?) do a linebreak..

## Current Behavior
As it is right now I get a vertical scroll when I have a long text.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/niklasos/pen/VwaYaaB?editors=1100

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
> height: 50px;

Try to remove this code.

**Comment by DanielRuf** [comment]
Also shrink for only one cell makes not much sense.

https://codepen.io/DanielRuf/pen/yLOyOqb?editors=1100

**Comment by Niklasos** [comment]
> > height: 50px;
> 
> Try to remove this code.

This did not work for me.

**Comment by Niklasos** [comment]
> Also shrink for only one cell makes not much sense.
> 
> https://codepen.io/DanielRuf/pen/yLOyOqb?editors=1100

I know it doesn't but I replicated the problem using only one cell :).

**Comment by DanielRuf** [comment]
Not a common use case (only ine cell with shrink).

**Comment by Niklasos** [comment]
> Not a common use case (only ine cell with shrink).

Yes maybe that is true but in my use case I need it to work like it did in the old flexbox grid where you don't get a vertical scroll. I think it should work like this for XY Grid aswell(?).

Flexbox Grid: https://codepen.io/niklasos/pen/LYNEzrJ?editors=1000

**Comment by DanielRuf** [comment]
> I believe it should work like this for XY Grid aswell(?)

Unfortunately this is not the case. If you need the flex grid you can enable it in the Sass version or use some custom CSS.

**Comment by Niklasos** [comment]
> > I believe it should work like this for XY Grid aswell(?)
> 
> Unfortunately this is not the case. If you need the flex grid you can enable it in the Sass version or use some custom CSS.

Alright, thank you!
