### ISSUE TITLE
Improve settings nomenclature for dropdown-menu

### ISSUE THREAD

**Issue by pine3ree** [foundation/foundation-sites#12136]
Hello, I have found a few little discrepancies in `_settings.scss` and `components/_dropdown-menu.scss`:

1. `$dropdown-menu-item-color-active` and `$dropdown-menu-item-background-active` do not follow previous nomenclature `$dropdownmenu-*`. All other setting vars follow the convention `$componentname-*`, where the component's code lies in the file `components/_component-name.scss`
2. `$dropdownmenu-background` is applied to `.dropdown.menu > li > a` while `$dropdownmenu-submenu-background` is applied to the `ul[class=is-dropdown-submenu]` container. IMHO this variable should be renamed to `$dropdownmenu-item-background`. Maybe we could keep `$dropdownmenu-background` to syle the bg of the whole dropdown ul.

3. It would be nice to have inner li, a, ul... all inheriting the background and color from the previous containing ul and have complete symmetric settings to override this behaviour:
  _// top-level and defautl for inner-levels inside dropdown.menu_
  `$dropdownmenu-item-color`
  `$dropdownmenu-item-color-active`
  `$dropdownmenu-background`
 ` $dropdownmenu-background-active`
  _// dropdown submenus_
  `$dropdownmenu-submenu-item-color: null !default` // set value to override in submenus
  `$dropdownmenu-submenu-item-color-active: null !default` // set value to override in submenus
  `$dropdownmenu-submenu-background: null !default` // set value to override in submenus
  `$dropdownmenu-submenu-background-active: null !default` // set value to override in submenus

**Comment by DanielRuf** [comment]
Thanks for your valuable input.

>  1. `$dropdown-menu-item-color-active` and

I think we changed some things there in the past. In general these would be breaking changes if we do not provide the option to use both.

Same for all other proposals to rename variables.

And all these extra variables, this would be quite much. Probably relevant for Foundation Sites 7.

**Comment by pine3ree** [comment]
Hello @DanielRuf 
...about the BC change, we could just add an @if to check if unconsistent-var-name is set and use it to set the consistently-named var. 
kind regards.

**Comment by DanielRuf** [comment]
Afaik we never did it like this. I'm not 100% sure but so far I see no high priority to change or add new variable names. Because then we should check all components, update the docs and plan a release.

Probably too much compared to normal and small bugfixes.

**Comment by pine3ree** [comment]
Ok @DanielRuf,
as you said we could change it for version 7 adding a note in the migration docs. If there is no interest for version 6.x, you can close the issue. best regards.
