### ISSUE TITLE
Mediaqueries upTo documentation correct?

### ISSUE THREAD

**Issue by Lefthandmedia** [foundation/foundation-sites#12132]
<img width="883" alt="FirefoxScreenSnapz008" src="https://user-images.githubusercontent.com/3350108/91044859-420c6900-e616-11ea-9064-c9b374c848b8.png">

## Description

 In the Mediaqueries page ( https://get.foundation/sites/docs/media-queries.html) > heading Javascript, 
 it is stated beneath the line that says 
"**// ↓ True for "medium" or larger**" 
`Foundation.MediaQuery.is('medium down');
Foundation.MediaQuery.upTo('medium');`

Should the line above this not be:  "// ↓ True for "medium" or **SMALLER**" 

...

## Possible Solution

...

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
You are correct. Thanks for catching this. A PR which fixes this is very welcome.

**Comment by Lefthandmedia** [comment]
Hi While investigating this i found there is more not working correctly or documented unintuitive

I made a small test script on a resize listener
```console.log('MediaQuery.current = ', Foundation.MediaQuery.current); 
console.log('is (medium up)', Foundation.MediaQuery.is('medium up'));
console.log('is (medium only)', Foundation.MediaQuery.is('medium only'));
console.log('is (medium down)', Foundation.MediaQuery.is('medium down'));
console.log('atLeast (medium)', Foundation.MediaQuery.atLeast('medium'));
console.log('only (medium) ', Foundation.MediaQuery.only('medium'));
console.log('upto (medium)', Foundation.MediaQuery.upTo('medium'));
```
On a small breakpoint this results in:
*MediaQuery.current =  small*
*is (medium up) true*
*is (medium only) false*
*is (medium down) false*
*atLeast (medium) false*
*only (medium)  false*
*upto (medium) true*

Obviously the first three are wrong when in small breakpoint, (medium up) should result in **false**.
and (medium down) should return  **true**

when the screensize is in medium this is logged:
 *MediaQuery.current =  medium*
 *is (medium up) true*
 *is (medium only) true*
 *is (medium down) true*
 *atLeast (medium) true*
 *only (medium)  true*
 *upto (medium) true*

Which was throwing me off because i assumed 'upTo medium' was not 'including medium'. i was expecting upTo(medium) to be false when in medium. There is no way of telling the breakpoint is smaller then 'medium' from the context of 'medium'

**Comment by DanielRuf** [comment]
> Obviously the first three are wrong when in small breakpoint, (medium up) should result in **false**

This is currect, small is small up which, Foundation Sites is mobile first.

**Comment by DanielRuf** [comment]
> Obviously the first three are wrong when in small breakpoint, (medium up) should result in **false**

This is correct, small is small up which, Foundation Sites is mobile first.

**Comment by Lefthandmedia** [comment]
What is correct? that (medium up) should result in **false**? or is it supposed to return **true** when in small breakpoint?

**Comment by DanielRuf** [comment]
We should check that in detail. There was some confusion regarding this in the past. Which exact version of Foundation Sites do you use?

**Comment by Lefthandmedia** [comment]
"foundation-sites": "6.6.0",
i can agree that Foundation.MediaQuery.is('medium') will result in true when on a small screen because F6 is mobile first. 
But Foundation.MediaQuery.is('medium up'), NB: the UP, can't logically be true then imho.
Looking in foundation.util.mediaQuery.js i can see on #191 that 'down' is defined as atLeast(size). My guess is that up and down are wrongly swapped (line #191 and #195)

**Comment by DanielRuf** [comment]
> "foundation-sites": "6.6.0",

Ok, 6.6.3 is the latest / newest version. I think we fixes related issue in the releases before this.

**Comment by DanielRuf** [comment]
> The comments in the code also state that when there is no modifier (up, only or down) given atLeast() will be used as fallback. the actual code doesn't do that. it will fallBack to upTo();
> I could make a MR to fix this.... if it is indeed wrong.

We should check that in a separate issue with a proper codepen and testcases as so far the tests do not fail. Or we do not have tests that cover this.
