### ISSUE TITLE
improve/extend pagination component (v.7)

### ISSUE THREAD

**Issue by pine3ree** [foundation/foundation-sites#12137]
## What is missing?
Support for optional first/last elements

## What is wrong now ?
`:first-child` and `:last-child` are assumed to be the pagination previous/next elements, so a pagination layout like the following (the pattern I mostly use)

FIRST PREV ... 5 6 7 **8** 9 10 11 ... NEXT LAST
« ‹ ... 5 6 7 **8** 9 10 11 ... › »

will not work correctly in mobile mode.

## Possible Solution
- use `.pagination-previous`, `.pagination-next` class selectors to make them always visible instead of `:first-child` and `:last-child`
- add  `.pagination-first` and `.pagination-last` classes
- add `$pagination-arrow-first` and `$pagination-arrow-last` string settings to customize first/last item icons
- add `$pagination-mobile-first-last` boolean settings to allowing making first/last item visible on mobile devices

**Comment by DanielRuf** [comment]
Thanks for the suggestion.

I guess in your use case you can use a simple link on both sides (outside of the pagination wrapper) to implement the needed feature. Correct?

Closing and marking as feature request for v7.

**Comment by pine3ree** [comment]
Hello @DanielRuf,

In fact I usually add the features listed in the "possible solution" section, overriding foundation last-child, first-child settings :-D. SInce first/last are pagination elements I don't like the idea of having them placed outside of it. Not using pseudo selectors also has the benefit to allow custom patterns, such as:

PREV NEXT | 1 ... **6** ... 100 

1 ... **6** ... 100 | PREV NEXT

etc etc

The role of an element is also better represented by its class than by its position.

kind regards
