### ISSUE TITLE
Uncaught TypeError: e.indexOf is not a function -- jquery-3.5.1.min.js

### ISSUE THREAD

**Issue by samuelsennev** [foundation/foundation-sites#12135]
Can anyone help me with this?

![Captura de Tela (141)](https://user-images.githubusercontent.com/58773754/91180979-bbf82d00-e6be-11ea-9c88-086f8f04b78d.png)

**Comment by DanielRuf** [comment]
This is a bug in waypoints.js, not in foundation.js.

Also please provide some more information / code.
Closing as this should be reported at https://github.com/imakewebthings/waypoints/issues
