### ISSUE TITLE
Foundation 6.6.3 Uncaught TypeError in foundation.util.touch.js with jQuery v1.12.4

### ISSUE THREAD

**Issue by jackmorizo** [foundation/foundation-sites#12153]
I want to drag the slider-handle of the foundation slider but I get the following Error-Message in multiple Browsers while emulating Mobile user agents. It also happens on android or ios devices.

```
foundation.util.touch.js:155 Uncaught TypeError: Cannot read property '0' of undefined
    at handleTouch (foundation.util.touch.js:155)
    at HTMLSpanElement.eval (foundation.util.touch.js:149)
    at HTMLSpanElement.dispatch (jquery.js?ver=5.5.1:3)
    at HTMLSpanElement.r.handle (jquery.js?ver=5.5.1:3)
handleTouch @ foundation.util.touch.js:155
eval @ foundation.util.touch.js:149
dispatch @ jquery.js?ver=5.5.1:3
r.handle @ jquery.js?ver=5.5.1:3
```

The Error starts in the Touch-Event-Handler because it is not guaranteed that the original Event is passed to the Handler.
https://github.com/foundation/foundation-sites/blob/8f1cb4749195e8037bd5947ef30938be754585d0/js/foundation.util.touch.js#L124

There is no check if the passed event is really the original event.

A possible solution would be to implement something like this into the handleTouch funktion at:
https://github.com/foundation/foundation-sites/blob/8f1cb4749195e8037bd5947ef30938be754585d0/js/foundation.util.touch.js#L131

```js
var handleTouch = function handleTouch(event) {
    if( event.originalEvent ){
        event = event.originalEvent;
    }
   // ...
}
```
An other solution would be to load the jquery version provided by Foundation but this is not a good solution since other jQuery plugins might have some issues since the jQuery version provided with foundation does not have the same interface like the one you can download directly from jQuery.

**Comment by DanielRuf** [comment]
> An other solution would be to load the jquery version provided by Foundation but this is not a good solution since other jQuery plugins might have some issues since the jQuery version provided with foundation does not have the same interface like the one you can download directly from jQuery.

We use / bundle the official jQuery releases.

There is the noConflict mode in jQuery, so you can use multiple versions: https://api.jquery.com/jQuery.noConflict/

Please see https://github.com/foundation/foundation-sites/issues/11763

We don't support old / outdated jQuery versions and these have already reached their end of life and should not be used in production due to several security issues.

**Comment by DanielRuf** [comment]
> dispatch @ jquery.js?ver=5.5.1:3

Looks like you use WordPress, there is a plugin to switch jQuery versions and you can always include a separate jQuery version too.

https://de.wordpress.org/plugins/jquery-updater/

As you can see here, we support only jQuery 2.2 and newer: https://github.com/foundation/foundation-sites/blob/v6.6.3/package.json#L34

**Comment by jackmorizo** [comment]
Hey Guys thanks for your respones. Unfortunately we have to use jQuery v1.12.4 in Production since of some dependencies. 
Anyway you helped me a lot
Cheers :-)
