### ISSUE TITLE
How to exclude foundation/components/_type.scss 

### ISSUE THREAD

**Issue by NitinBuzz** [foundation/foundation-sites#12151]
## What should happen?
Wanted to exclude global styles and foundation/components/_type.scss
Have used $include-html-global-classes: false; - but _types.scss is not getting excluded.
...

## What happens instead?
Have used $include-html-global-classes: false; - but _types.scss is not getting excluded.
...

**Comment by DanielRuf** [comment]
Which version of Foundation Sites do you use?
I see no such file at https://github.com/foundation/foundation-sites/tree/develop/scss/components

https://github.com/foundation/foundation-sites/tree/develop/scss

Please provide a full example / reproducible test case (some test repository).

**Comment by NitinBuzz** [comment]
Using v5.3

**Comment by NitinBuzz** [comment]
Migrated to latest foundation and it looks good now. Thank you
