### ISSUE TITLE
Add Travis 

### ISSUE THREAD

**Issue by nandithags11** [foundation/foundation-sites#12157]
## Description

Add travis for CI

## Possible Solution

Travis CI is a hosted continuous integration service used to build and test software projects hosted at GitHub and Bitbucket. Travis CI provides various paid plans for private projects, and a free plan for open source. TravisPro provides custom deployments of a proprietary version on the customer's own hardware.

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
We use GitHub Actions for CI.
