### ISSUE TITLE
Error on the Foundation-Website

### ISSUE THREAD

**Issue by chmich** [foundation/foundation-sites#12174]
```https://zurb.com/university```

klicking on Foundation Certification

receiving Error 522 Connection timed out

see webarchive below

thanks,
Chris

![image](https://user-images.githubusercontent.com/31048265/98529300-bc47a380-227d-11eb-904c-ae28f1849254.png)

**Comment by DanielRuf** [comment]
For me it works here.

https://zurb.com/university

![grafik](https://user-images.githubusercontent.com/827205/98533400-3a5a7900-2283-11eb-9f41-0957d7e3813a.png)

As Foundation Sites is not maintained by ZURB anymore but volunteers it's best to contact directly the people at zurb.com if you still see this error.

**Comment by DanielRuf** [comment]
It seems they still link to https://foundation.zurb.com/learn/certification.html, which should be https://get.foundation/learn/certification.html

As Foundation Sites is not maintained by ZURB anymore but volunteers it's best to contact directly the people at zurb.com regarding this error.

Our current website is at https://get.foundation/
