### ISSUE TITLE
Custom Build Download is Not Working

### ISSUE THREAD

**Issue by hecforce** [foundation/foundation-sites#12197]
I was surprised to see that this link is dead. Will this dead link be resolved? If so, when?
**Dead Link:** https://download.get.foundation/sites/download

Thanks,

**Comment by DanielRuf** [comment]
Closing as duplicate of https://github.com/foundation/foundation-sites/issues/12189

Please check the open and pinned issues and use the search before opening new issues. Thank you.

**Comment by hecforce** [comment]
Thanks Daniel, 

I did search but apparently missed the pin. It would be nice to have that page up and running again. At least there is a work around. I appreciate it.
