### ISSUE TITLE
Can't download zurb foundation from https://download.get.foundation/sites/download

### ISSUE THREAD

**Issue by JayJayAng** [foundation/foundation-sites#12196]
## Expected Behavior

...

## Current Behavior

...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] This is a bug report or a feature request.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by ErvinSabic** [comment]
Looks like they gotta get in touch with their hosting provider.

**Comment by DanielRuf** [comment]
Please see the pinned issue.
It has nothing to do with the hosting provider.

https://github.com/foundation/foundation-sites/issues/12189

cc @joeworkman
