### ISSUE TITLE
Link errors from v5 documentation

### ISSUE THREAD

**Issue by jimfenton** [foundation/foundation-sites#12190]
## Description

Menu links from the Foundation 5 documentation seem to be broken. For example, from https://get.foundation/sites/docs-v5/ pulling down Docs -> F5 Sites Docs goes to https://get.foundation/sites/docs/v/5.5.3/ which is 404. Pulling down to Docs -> F6 Sites Docs goes to https://get.foundation/sites/docs which is correct but renders (Firefox 84.0.1) with no CSS; debug console says it was not found.

## Possible Solution

For the former issue, correct the link. I'm not sure what's causing the CSS not to be found.

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
> Docs goes to https://get.foundation/sites/docs which is correct but renders (Firefox 84.0.1) with no CSS; debug console says it was not found.

Try it with a trailing slash.

cc @joeworkman there is probably a setting for this

**Comment by jimfenton** [comment]
Ah, didn't notice the lack of a trailing slash. That's it, so adding the slash to the link will correct that part of the problem.

**Comment by DanielRuf** [comment]
> Menu links from the Foundation 5 documentation seem to be broken. For example, from [get.foundation/sites/docs-v5](https://get.foundation/sites/docs-v5/) pulling down Docs -> F5 Sites Docs goes to [get.foundation/sites/docs/v/5.5.3](https://get.foundation/sites/docs/v/5.5.3/) which is 404

I think this should lead to the same v5 URL. I'll check that.

**Comment by kgalusha95** [comment]
I am having this same issue. Any update? I tried [(https://get.foundation/sites/docs-v5/5.5.3 )] to see if that might work, but it did not.

**Comment by DanielRuf** [comment]
> Try it with a trailing slash.

`https://get.foundation/sites/docs-v5/`

**Comment by DanielRuf** [comment]
> I think this should lead to the same v5 URL. I'll check that.

It should be the same. `https://get.foundation/sites/docs-v5/`

**Comment by kgalusha95** [comment]
I can get to that page fine. I am trying to download the css from here https://get.foundation/sites/docs-v5/css.html, but the "download css" button goes to a 404.

**Comment by DanielRuf** [comment]
> I can get to that page fine. I am trying to download the css from here [get.foundation/sites/docs-v5/css.html](https://get.foundation/sites/docs-v5/css.html), but the "download css" button goes to a 404.

Please try this one: https://github.com/foundation/foundation-marketing/blob/master/src/downloads/foundation-5.5.3.zip

**Comment by kgalusha95** [comment]
Great! Thank you for your very fast responses.

**Comment by DanielRuf** [comment]
If you need any additional files, take a look at https://unpkg.com/browse/foundation-sites@5.5.3/.
