### ISSUE TITLE
foundation instalation local link doesnt work

### ISSUE THREAD

**Issue by itachi-dev-01** [foundation/foundation-sites#12194]
hi, i try to instal the last entire pack ok foundation site in local and this link doesnt work => https://download.get.foundation/sites/download

**Comment by Summer88** [comment]
Did you try last release?
https://github.com/foundation/foundation-sites/releases/tag/v6.6.3

**Comment by itachi-dev-01** [comment]
i dont know how to use this file, because i dont find the usefull files i need:

![filestructure](https://user-images.githubusercontent.com/77319608/104318360-96d65080-54df-11eb-91fb-ebe925bb37ac.jpg)

**Comment by reinhardmohr** [comment]
Hi, itachi-dev-01,

I often ran into the same problem – as I am not the developer guy with all the "complicated" tools like gulp and dist and scss …
… I am more into css and html.
So it‘s usually much better you download the file from 
https://get.foundation
There you find a very convinient starter template named index.html that I usually adapt to my needs. That's much easier!
But I found – to make javascript things like dropdown work – you have to add an additional line of code near the end of the source code. A bit different for different versions.
It once used to be something like
"initialize foundation.js" 
and last time was
<script>  $(document).foundation(); </script>

I hope this helps – as Foundation is a great framework. But sometimes it‘s a bit hard to start – but then it gets great and easy!
Thanks for using it!
Reinhard

**Comment by DanielRuf** [comment]
Please see the pinned issue regarding the download page: https://github.com/foundation/foundation-sites/issues/12189

**Comment by DanielRuf** [comment]
The rest of the files are at https://unpkg.com/browse/foundation-sites@6.6.3/dist/ and in our template repos:

https://github.com/foundation/foundation-zurb-template
https://github.com/foundation/foundation-sites-template

**Comment by itachi-dev-01** [comment]
DanielRuf think you for your help ! 
I have not seen the problem posted before me. I am sorry
