### ISSUE TITLE
Support for non-rectangular displays (e.g. notches)

### ISSUE THREAD

**Issue by Zignature** [foundation/foundation-sites#12202]
## What is missing?

Foundation 6 currently doesn't account for notches in displays.
As is also the case with the toolbar on the iPhone X for instance.

IMHO Foundation for Sites needs to support this out of the box as more devices with non-rectangular displays will emerge.

## What is wrong now ?

Display notches and (iPhone) toolbars interfere with the layout.

Example of iPhone toolbar interfering with sticky bottom menubar:
![iphone-sticky-bottom-error](https://user-images.githubusercontent.com/4068757/108192706-e3cbc900-7114-11eb-93c9-1247788bb0be.jpg)

## Possible Solution

The use of css environment variables (user agent-defined constants) will solve the issue:
![iphone-sticky-bottom-error-fixed](https://user-images.githubusercontent.com/4068757/108197559-d44f7e80-711a-11eb-8fc7-0a34d2f86f6c.jpg)

For iOS 11.0 - 11.2:
```
padding-top: constant(safe-area-inset-top);
padding-right: constant(safe-area-inset-right);
padding-bottom: constant(safe-area-inset-bottom);
padding-left: constant(safe-area-inset-left);
```

For later OSes:
```
padding-top: env(safe-area-inset-top);
padding-right: env(safe-area-inset-right);
padding-bottom: env(safe-area-inset-bottom);
padding-left: env(safe-area-inset-left);
```

For the environment variables to work `viewport-fit=cover` needs to be added to the `content` attribute of the `<meta name="viewport">` tag e.g. `<meta name="viewport" content="viewport-fit=cover">`.

---

In [my fork](https://github.com/Zignature/foundation-sites) of Foundation for Sites I made some edits:
### foundation.util.mediaQuery.js
line ~91 just before:
```
var self = this;
var $meta = $('meta.foundation-mq');
```
 I added:
```
var $metaViewport =  $('meta[name="viewport"]');
var $metaViewportFit = $('meta[content*="viewport-fit=cover"]');
// add meta viewport tag if not present
if (!$metaViewport.length) {
  $('head').append('<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, viewport-fit=cover">');
} else {
  // add viewport-fit=cover if not present which is mandatory for the use of css environment variables
  if (!$metaViewportFit.length) {
    $metaViewport.attr('content', (i, value) => \`${value || ""}, viewport-fit=cover\`);
  }
}
```
to make sure a correct meta viewport tag is present.

### _global.scss
line ~161 just after:
```
body {
  margin: 0;
  padding: 0;
```
I added:
```
  // using environment variables to account for non-rectangular displays e.g. phones with notches
  padding-top: constant(safe-area-inset-top);
  padding-right: constant(safe-area-inset-right);
  padding-bottom: constant(safe-area-inset-bottom);
  padding-left: constant(safe-area-inset-left);

  padding-top: env(safe-area-inset-top);
  padding-right: env(safe-area-inset-right);
  padding-bottom: env(safe-area-inset-bottom);
  padding-left: env(safe-area-inset-left);
```
---

**Extra suggestion**
A mixin may be handy so that it can be applied to any element:
```
@mixin safe-padding($areas, $fallback:'') {
	$padding-no-env: 0;
	@if $fallback != '' {
		$padding-no-env: $fallback;
		$fallback: ", " + $fallback;
	}

	/* padding for browsers that do not support environment variables */
	@each $area in $areas {
		padding-#{$area}: #{$padding-no-env};
	}

	@supports (top: constant(safe-area-inset-top)){
		/* support for iOS 11.0 - 11.2 */
		@each $area in $areas {
			padding-#{$area}: constant(safe-area-inset-#{$area}#{$fallback});
		}
	}

	@supports (top: env(safe-area-inset-top)){
		@each $area in $areas {
			padding-#{$area}: env(safe-area-inset-#{$area}#{$fallback});
		}           
	}
}
```

Usage examples:
- `body { @include safe-padding( top right bottom left ) }`
output:
```
body {
  /* padding for browsers that do not support environment variables */
  padding-top: 0;
  padding-right: 0;
  padding-bottom: 0;
  padding-left: 0;
}
@supports (top: constant(safe-area-inset-top)) {
  body {
    /* support for iOS 11.0 - 11.2 */
    padding-top: constant(safe-area-inset-top);
    padding-right: constant(safe-area-inset-right);
    padding-bottom: constant(safe-area-inset-bottom);
    padding-left: constant(safe-area-inset-left);
  }
}
@supports (top: env(safe-area-inset-top)) {
  body {
    padding-top: env(safe-area-inset-top);
    padding-right: env(safe-area-inset-right);
    padding-bottom: env(safe-area-inset-bottom);
    padding-left: env(safe-area-inset-left);
  }
}
```

- `.className { @include safe-padding( top, 1rem ) }`
output:
```
.className {
  /* padding for browsers that do not support environment variables */
  padding-top: 1rem;
}
@supports (top: constant(safe-area-inset-top)) {
  .className {
    /* support for iOS 11.0 - 11.2 */
    padding-top: constant(safe-area-inset-top, 1rem);
  }
}
@supports (top: env(safe-area-inset-top)) {
  .className {
    padding-top: env(safe-area-inset-top, 1rem);
  }
}
```

---

**References:**
- [MDN Web docs env()](https://developer.mozilla.org/en-US/docs/Web/CSS/env())
- [CSS Tricks: “The Notch” and CSS](https://css-tricks.com/the-notch-and-css/)

## Context

I created a menubar to stick to the bottom of the screen. It turned out the menubar got stuck behind the toolbar of the iPhone X and was therefore unusable 

After doing some research, I found out the same problem arises with notches in displays.

## Your Environment

- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): Any
- Device, Operating System and version: any device with non-rectangular displays e.g. with notches in its display

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Related: https://github.com/foundation/foundation-sites/issues/11188

**Comment by Zignature** [comment]
Yes, I saw that one too after I posted.
I apologize, it's because of a spelling error (nodge instead of notch) that I didn't find it before posting...

I still think it's a good idea since I expect more devices with non-rectangular displays to come in to existance.
Devices with rounded corners on displays, or round displays you currently see on smartwatches, but larger. And even notches might resurface. And what about device attributes such as toolbars that may interfere...

A variable to turn on or off as was mentioned in that post could work as a compromise, but that's only for people that work with Sass.

For the time being I'll use my mixin :)

**Comment by DanielRuf** [comment]
> I apologize, it's because of a spelling error (nodge instead of notch) that I didn't find it before posting...

No problem, I just link the issue so all relevant details are available and others can check both issues.

**Comment by DanielRuf** [comment]
> In [my fork](https://github.com/Zignature/foundation-sites) of Foundation for Sites I made some edits:

The changes look good. A PR is very welcome.

**Comment by Zignature** [comment]
> > In [my fork](https://github.com/Zignature/foundation-sites) of Foundation for Sites I made some edits:
> 
> The changes look good. A PR is very welcome.

[PR #12199](https://github.com/foundation/foundation-sites/pull/12199)
