### ISSUE TITLE
[XY Grid] No description of the grid in the documentation

### ISSUE THREAD

**Issue by iainhallam** [foundation/foundation-sites#12207]
Just been reading the XY Grid documents at https://get.foundation/sites/docs/xy-grid.html, and I had to go hunting for the basic information on how many columns there were in the grid, and when I should use the `small`, `medium`, and `large` classes. I found better explanation on the float grid page.

**Comment by DanielRuf** [comment]
> The XY grid works very similarly to the standard float grid, but includes a number of useful features only possible with Flexbox, like horizontal and vertical alignment, automatic sizing and a full vertical grid.

https://get.foundation/sites/docs/grid.html

Also all grids use 12 columns by default (like most other frontend frameworks too.
