### ISSUE TITLE
is foundation-sites broken?

### ISSUE THREAD

**Issue by slacey-gmhc** [foundation/foundation-sites#12201]
I've been a long time user and fan of foundation sites.
I just got a new laptop and installed the foundation cli as well as node, yarn, and gulp. When i run the command foundation new i get this error message.

**_fs.js:45 } = primordials; ^ ReferenceError: primordials is not defined_**

I've cloned the github repo, installed with yarn, and when i run yarn start i get another error message.

**_$ gulp C:\Users\UserName\Desktop\foundation\foundation-sites\node_modules\node-sass\lib\binding.js:13 throw new Error(errors.unsupportedEnvironment());^ Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)_**

Is there something I am missing or doing incorrectly?

**Comment by DanielRuf** [comment]
Please use nvm, n or nodenv to switch to Node 10.

This is a known issue with gulp .

See:
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
https://github.com/foundation/foundation-sites/search?q=primordials+is%3Aissue&type=issues
https://stackoverflow.com/a/56253873/753676

**Comment by slacey-gmhc** [comment]
DanielRuf thank you. Do you know of where I can find updated documentation for foundation-sites v6.6.3?

**Comment by DanielRuf** [comment]
The current documentation that you can find online is the latest available version.

**Comment by aderowbotham** [comment]
Does Zurb Foundation have / or can you provide updated instructions for "use nvm" in the context of setting up Foundation?

The documentation on the Foundation website [here](https://get.foundation/sites/docs/installation.html) doesn't work. And the fix [here](https://timonweb.com/javascript/how-to-fix-referenceerror-primordials-is-not-defined-error/) does not work.

**Comment by DanielRuf** [comment]
Did you already try `nvm use 10` or similar?

**Comment by aderowbotham** [comment]
Node version is 12.  I have never heard of **nvm** but will Google it.

If Foundation officially requires the use of **nvm** or ways of using an older version of Node then could the documentation possibly be updated to explain the steps required?

**Comment by DanielRuf** [comment]
nvm or Node Version Manager is a tool to switch between Node version, see https://github.com/nvm-sh/nvm

**Comment by aderowbotham** [comment]
@DanielRuf Thank you, I was finally able to setup a new Foundation project with Node 10 via nvm
