### ISSUE TITLE
This is now hosted at https://download.get.foundation/sites/download/

### ISSUE THREAD

**Issue by JonathanRimmer** [foundation/foundation-sites#12211]
This is now hosted at https://download.get.foundation/sites/download/

_Originally posted by @DanielRuf in https://github.com/foundation/foundation-sites/issues/11826#issuecomment-605529890_

Is there an issue with the custom download on the foundation zurb site. I have been trying to download a custom version of the css for a month or so now but all I get is the following:

This account has been disabled. Please visit https://uberspace.de/support.
Dieser Account wurde deaktiviert. Bitte besuche https://uberspace.de/support.

Is this issue being worked on and will it be back up and running soon?

Many thanks

**Comment by DanielRuf** [comment]
Please see https://github.com/foundation/foundation-sites/issues/12189 and the comments.

**Comment by DanielRuf** [comment]
The issue is pinned, so you should be able to see it at the top of the issues.

**Comment by DanielRuf** [comment]
> Is this issue being worked on and will it be back up and running soon?

I don't know. Please ask @joeworkman. I am not actively involved anymore.
