### ISSUE TITLE
Customizer - cannot generate custom build

### ISSUE THREAD

**Issue by despecial** [foundation/foundation-sites#12214]
## What should happen?
run the customizer at localhost (localhost:3000/sites/download) and generate a custom build

## What happens instead?
error: ENOENT: no such file or directory, stat '/tmp/tmp.6.6.3.cb886060b0b32519298b8dce38a6f133.zip'

Console:

> Fri, 19 Mar 2021 10:23:24 GMT node-foundation-customizer:server ./node_modules/.bin/gulp customizer --modules /tmp/tmp.6.6.3.cb886060b0b32519298b8dce38a6f133.json --output /tmp/tmp.6.6.3.cb886060b0b32519298b8dce38a6f133
>  
> Fri, 19 Mar 2021 10:23:24 GMT node-foundation-customizer:server Error: spawn /bin/sh ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
>     at onErrorNT (internal/child_process.js:415:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> 

## Test Case and/or Steps to Reproduce (for bugs)
```
git clone git@github.com:zurb/node-foundation-customizer && cd node-foundation-customizer
npm install

npm start

npm run foundation
```

**Comment by DanielRuf** [comment]
Please ee the note about installing foundation as dependency.

https://github.com/foundation/node-foundation-customizer/blob/master/package.json#L7

https://github.com/foundation/node-foundation-customizer/blob/master/README.md#installing-dependencies

**Comment by despecial** [comment]
Unfortunately, it still throws an error when trying to run "npm start"
```
Error: Cannot find module 'body-parser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/XXXXX/foundation/node-foundation-customizer/app.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

```

**Comment by DanielRuf** [comment]
You have to generate the files once and install foundation-sites.

> audit fix --force

That upgrades packages and is not recommended.

Please use the issue tracker at https://github.com/foundation/node-foundation-customizer/issues and try all the recommended steps.

The correct order should be:

```
npm i
npm foundation
npm start
```

**Comment by despecial** [comment]
Thanks - I am not sure where the miscommunication is.
If I follow your instructions it results in the same problem again and again. No custom build is generated

```
$ npm i
(node:90833) ExperimentalWarning: The fs.promises API is experimental
 
up to date, audited 821 packages in 2s
 
11 packages are looking for funding
  run `npm fund` for details
 
30 vulnerabilities (3 low, 6 moderate, 20 high, 1 critical)
 
To address all issues (including breaking changes), run:
  npm audit fix --force
 
Run `npm audit` for details.

$ npm foundation
(node:90843) ExperimentalWarning: The fs.promises API is experimental
 
Usage: npm <command>
 
npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
npm run <foo>      run the script named <foo>
npm <command> -h   quick help on <command>
npm -l             display usage info for all commands
npm help <term>    search for help on <term>
npm help npm       more involved overview
 
All commands:
 
    access, adduser, audit, bin, bugs, cache, ci, completion,
    config, dedupe, deprecate, diff, dist-tag, docs, doctor,
    edit, exec, explain, explore, find-dupes, fund, get, help,
    hook, init, install, install-ci-test, install-test, link,
    ll, login, logout, ls, org, outdated, owner, pack, ping,
    prefix, profile, prune, publish, rebuild, repo, restart,
    root, run-script, search, set, set-script, shrinkwrap, star,
    stars, start, stop, team, test, token, uninstall, unpublish,
    unstar, update, version, view, whoami
 
Specify configs in the ini-formatted file:
    /Users/despecial/.npmrc
or on the command line via: npm <command> --key=value
 
More configuration info: npm help config
Configuration fields: npm help 7 config
 
npm@7.6.3 /usr/local/lib/node_modules/npm
```

I will open an issue at the tracker link.

**Comment by DanielRuf** [comment]
Ah sorry, I mean `npm run foundation`.
