### ISSUE TITLE
Showcase link is dead

### ISSUE THREAD

**Issue by CherryDT** [foundation/foundation-sites#12213]
## What should happen?

The link "Foundation Showcase" prominently positioned in the navbar of https://get.foundation/ should go to a page that showcases Foundation.

## What happens instead?

It goes to https://zurb.com/responsive where it tells me that there isn't much to see (404):

![image](https://user-images.githubusercontent.com/6010463/111302364-9a0ec980-8653-11eb-8098-e6f0f1367282.png)

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by Samji** [comment]
Clicking the main menu item: Showcase links to the same 404 page.

**Comment by DanielRuf** [comment]
The page was never transferred and it seems ZURB removed it.

**Comment by CherryDT** [comment]
Okay, but I'm confused now - the link still exists and links to the dead page despite this issue being closed, shouldn't it be removed then?
