### ISSUE TITLE
[Installation] Download Foundation button leads to 404 Not Found

### ISSUE THREAD

**Issue by michymy** [foundation/foundation-sites#12229]
## Expected Behavior

Download Foundation button is expected to lead us to download a starter template with compiled CSS and JavaScript.

## Current Behavior

Download Foundation button leads to a 404 Not Found page. 

## Possible Solution

Fix broken page so that the download button works.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Go to https://get.foundation/sites/docs/installation.html#download
2. Click on the blue "Download Foundation" button
3. Error message "The requested URL /sites/download was not found on this server." appears

## Context

I'm trying to download the Foundation starter template onto my computer via the easiest way possible.  

## Your Environment

- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): Chrome 90.0.4430.93 (Official Build) (64-bit) & Firefox 86.0.1 (64-bit)
- Device, Operating System and version: DESKTOP-HFGQP2Q, Win 10 20H2
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [ ] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Please see the pinned issue: https://github.com/foundation/foundation-sites/issues/12189

**Comment by michymy** [comment]
Thanks for your reply Daniel. May I know why can't the Download link on the website be fixed to make it easier for future users? Instead of them having to go through the forums to find a solution.

**Comment by DanielRuf** [comment]
I'm not actively involved as core-contributor anymore.

PRs are very welcome.
