### ISSUE TITLE
Problem with page: download link does not work

### ISSUE THREAD

**Issue by SomogyiR69** [foundation/foundation-sites#12220]
## What should happen?
Page should open / download should start.

## What happens instead?
The following text appeared on the page, nothing else.

"This account has been disabled. Please visit https://uberspace.de/support.
Dieser Account wurde deaktiviert. Bitte besuche https://uberspace.de/support."

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): Safari Version 14.0.3 
- Device, Operating System and version: MacBook Air (M1, 2020) macOS Big Sur version 11.2.2
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Please see the pinned issue for details: https://github.com/foundation/foundation-sites/issues/12189

**Comment by DanielRuf** [comment]
Prepackaged downloads are available as zip at https://github.com/foundation/foundation-sites/issues/12189#issuecomment-753383167
