### ISSUE TITLE
[Starter Projects] Download Foundation 6 button skips page with download options

### ISSUE THREAD

**Issue by bkline** [foundation/foundation-sites#12225]
## Expected Behavior
According to the _Starter Projects_ video, the **Download Foundation 6** button should take the user to a page which offers several options for selecting which Foundation package should be downloaded.

## Current Behavior
Clicking on that button instead bypasses the download options page and proceeds to download `Foundation-sites-6.6.3-CSS.zip` immediately. Entering the URL shown in the video for the download options page results in the following error message.
![image](https://user-images.githubusercontent.com/1634628/115299896-59f8a600-a12d-11eb-853a-1fe9998ba01b.png)

## Possible Solution
Restore the download options page.

How to reproduce:
1. Navigate to https://foundation.zurb.com (as instructed in the video)
2. Click on **Download Foundation 6** (as instructed in the video)
3. Notice that the download options page does not appear
4. Note that a zip file is selected for you and downloaded.
5. Navigate to https://foundation.zurb.com/site/download.html (URL shown in the video)
6. Read error message

## Context
The behavior described above removes the options to select a packaging of Foundation appropriate for the needs of the user.

## Your Environment
- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): N/A (happens with any browser)
- Device, Operating System and version: N/A (same behavior on MacOS, Linux, Windows)
- Link to your project: haven't gotten that far

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
>     5\. Navigate to [foundation.zurb.com/site/download.html](https://foundation.zurb.com/site/download.html) (URL shown in the video)

This doesn't exists anymore since the project was given to the community. The zip file is what you are looking for.

What you are currently looking for is the customizer. Please see the pinned issue at https://github.com/foundation/foundation-sites/issues/12189 and carefully read my comments there.

**Comment by bkline** [comment]
Well, what I was _really_ looking for was the correct forum for reporting the discrepancy between the documentation on the https://get.foundation web site describing how the download page for that site works and the actual behavior of that download page for that site, in the hopes that such a report would eventually result in getting that documentation of the site's behavior and the actual behavior to match again. According to https://get.foundation/get-involved/faq.html this is where such reports are supposed to be filed (see the link to this issue tracking page at that bottom of that page). What you're implying is that's not true, and this is _not_ the place for such discrepancies to be reported. Can you please tell me where is the appropriate place?

**Comment by DanielRuf** [comment]
Hi @bkline,

this is the correct place, but the videos are old and outdated.
Nothing that we can fix (we could only remove all old videos).
