### ISSUE TITLE
Consider dropping support for IE9

### ISSUE THREAD

**Issue by NagayamaToshiaki** [foundation/foundation-sites#12245]
IE9 and IE10 is EOL as of 2021.
https://www.essent.com/SupportNotices/Blog/Internet-Explorer-9-and-10-Support-Ends-March-31-2017.htm
Why do you keep supporting those obsolete browsers?
Now you syould only support IE11 (until at least next year) along with other modern browsers.

**Comment by joeworkman** [comment]
Foundation 7 will definitely drop support for IE
