### ISSUE TITLE
When the Reveal Opening Animation Has Finished, Do Sth

### ISSUE THREAD

**Issue by Mozhdeh-d** [foundation/foundation-sites#12252]
I'm using foundation zurb v6, and I want to know when the reveal has opened completely. I used the code below to understand when the reveal has opened:

```
$(document).on('open.zf.reveal', '.commentReveal', function () {
   Some Codes Here
})
```

And it worked properly, But when I set an animation to opening & closing the reveal, It won't work anymore. So I think I have to use a code to see when the animation is finished as well. Actually I suppose that I need a callback for reveal animation.

And this is my reveal element:

```
<div class="reveal commentReveal" data-reveal data-close-on-click="true" data-animation-in="scale-in-up fast" data-animation-out="scale-out-down fast">
    .....
</div>
```

Is there a trigger to see when the reveal opening animation has finished? I'd appreciate any help on this issue :(

**Comment by joeworkman** [comment]
So if you add a console.log statement into callback, it doesn't work? It sure does work for me.
