### ISSUE TITLE
6.7.0 is causing puppeteer + Chromium download

### ISSUE THREAD

**Issue by simshaun** [foundation/foundation-sites#12254]
## What should happen?

`npm i foundation-sites` should not install puppeteer as well

## What happens instead?

puppeteer is required, triggering a Chromium download

## Possible Solution

Move the puppeteer requirement to devDependencies.

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:
1. `npm i foundation-sites`

## Context

Puppeteer triggers a 100MB+ Chromium download. On slow connections like mine, it takes a while.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by logic01** [comment]
My entire team has just got our Angular project development come to a screeching halt over this.

**Comment by xavierfoucrier** [comment]
Yes, this is only useful for development environment and shouldn't be required when installing `foundation-sites`.

**Comment by joeworkman** [comment]
Sorry. It got added as a dependency instead of a dev dependency. I completely overlooked that. I will get that fixed in 6.7.1. Thanks.
