### ISSUE TITLE
NPM version maintenance

### ISSUE THREAD

**Issue by paolosax** [foundation/foundation-sites#12251]
## Description

Hello, I just like to know if newer versions of Foundation will be ported to the foundation-sites npm package as well
...

## Possible Solution

...

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by joeworkman** [comment]
I ran out of time on Friday. I will be doing this today.
