### ISSUE TITLE
SassError: $color: null is not a color

### ISSUE THREAD

**Issue by mikaeldiener** [foundation/foundation-sites#12257]
## What happens?

Upgraded to the latest (6.7.0) npm package, and I get the following error when compiling my scss:

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: null is not a color.
    ╷
176 │ $anchor-color-hover: scale-color($anchor-color, $lightness: -14%);
    │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  styles\_settings.scss 176:22       @import

**Comment by DontFretBrett** [comment]
Our team had the same issue. Also with scale-color. When we hard coded package to 6.6.3 our build was fixed again.

**Comment by joeworkman** [comment]
Can you please give me details on how to replicate this? v6.7.0 build fine for me.

**Comment by mikaeldiener** [comment]
Our webpack pipeline also worked perfectly with v6.6.3. Except for the obsolete dart sass errors.

Details about our webpack setup:
sass: 1.29.0
sass-loader: 12.1.0
webpack: 5.42.1
mini-css-extract-plugin: 1.3.1

**Comment by joeworkman** [comment]
Do you have `@include add-foundation-colors;` in your settings file?
