### ISSUE TITLE
Foundation-Sites 6.7.x breaks zurb-foundation-template yarn build

### ISSUE THREAD

**Issue by erutan** [foundation/foundation-sites#12270]
## What should happen?

Yarn should properly build dependencies on install, and the gulp process should create a local instance of the site without erroring out.

## What happens instead?

Yarn fails to build, node-gyp and node-pre-gyp error out. node-gyp is pinned to 3.8.0, for kicks I did a global build of the latest version of node-gyp (8.2) on my machine and it built fine. I also re-installed xcode command line tools, reinstalled node, cleaned yarn caches out, deleted and rebuilt `node-modules` etc.

Yarn start errors out on sass, build, and default tasks... which isn't too surprising.

## Possible Solution

Not my area of expertise. :(

A workaround is locking foundation to 6.6.3 in package.json, 
`    "foundation-sites": "=6.6.3",`

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:

1. `git clone https://github.com/zurb/foundation-zurb-template fails`
2. `cd fails`
3. `yarn`
4. `yarn start` (optional)

## Your Environment

- Foundation version(s) used: 6.6.3, 6.7.1, 6.7.2
- Browser(s) name and version(s): NA
- Device, Operating System and version: MacBookPro13,3, MacOs 11.5.2, Node v12.22.6, Yarn 1.22.5

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ArkinSolomon** [comment]
Try removing `yarn.lock` and `package-lock.json`. Then run `yarn` and `yarn start`.

**Comment by erutan** [comment]
I had tried that earlier, but I guess when I had experimented with upgrading to yarn 2.

The site builds and serves locally (with a lot of warnings) with the lock files gone, but rendering mixed html & markdown is broken on a page now. Browsersync is bugged out and works intermittently.

```
warning browser-sync > socket.io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning browser-sync > socket.io > socket.io-parser > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning browser-sync > socket.io > engine.io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning gulp > glob-watcher > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning gulp > glob-watcher > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning gulp > glob-watcher > anymatch > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning gulp > glob-watcher > anymatch > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning gulp-imagemin > imagemin-gifsicle > exec-buffer > tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning gulp-imagemin > imagemin-gifsicle > gifsicle > bin-build > tempfile > uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning gulp-imagemin > imagemin-gifsicle > gifsicle > bin-build > decompress > buffer-to-vinyl > uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning gulp-imagemin > imagemin-gifsicle > gifsicle > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp-sass > node-sass > node-gyp > tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
warning gulp-sass > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning gulp-sass > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning gulp-sass > node-sass > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning gulp-sass > node-sass > request > har-validator@5.1.5: this library is no longer supported
warning gulp-sourcemaps > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning panini > highlight.js@8.9.1: Version no longer supported. Upgrade to @latest
warning style-sherpa > highlight.js@8.9.1: Version no longer supported. Upgrade to @latest
warning uncss > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning uncss > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning uncss > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning uncss > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

**Comment by ArkinSolomon** [comment]
It seems to work for me even with the warnings

Yarn 1.22.11, MacOS 12 Beta, Node 12.22.6.

Updating files reloads the page properly, and the page looks fine, are you using the default template? Also do you have gulp installed globally? 

```
$ gulp -v
CLI version: 2.2.0
Local version: 4.0.2
```

**Comment by erutan** [comment]
The markdown/browsersync issues were going through a custom site built off of the template I was kicking the tires on to see if I could run it with 6.7.x.

Markdown behaviour changing is tied to the parsing module jumping forward - it's not really "wrong", but it's different. Partials used to be injected into a page and then rendered, whereas now they need `{{#markdown}}` and `{{/markdown}}`. Whitespace also acts differently - you need an empty line after HTML for something to be parsed as markdown, though thankfully you don't need two empty spaces after a line to have it act as a new paragraph.

The browsersync not reloading is very itermittent - it'll work most of the time but miss occasionally (5%?). I've noticed this for both SCSS and HTML. This never happened in 6.6.3, but I haven't tried unlocking yarn and pinning 6.6.3.

Gulp is not installed globally (I've had my laptop be a bit of a mess before, so I mostly just keep things in directory and/or use something like Lando for more involved projects). I am running commands from CLI.

```
gulp -v
zsh: command not found: gulp
```

**Comment by ArkinSolomon** [comment]
Ah ok, what browser are you using?

**Comment by erutan** [comment]
Firefox, whatever the latest stable version is (on phone atm).

**Comment by ArkinSolomon** [comment]
Did you try any other browsers?

**Comment by joeworkman** [comment]
I just shipped updates to foundation-cli today. It definitely works now (with a few caveats) https://github.com/foundation/foundation-cli/releases/tag/v2.3.0
