### ISSUE TITLE
[Dropdown Menu] JS - Error in trigger name

### ISSUE THREAD

**Issue by Gilles-MUESS** [foundation/foundation-sites#12298]
Hello,

After an issue and a reading of the code, the event triggered after you open a dropdown is not 'show.zf.dropdownMenu' but 'show.zf.dropdownmenu'. I guess it may be the same for the 'hide.zf.dropdownmenu'.

**Comment by joeworkman** [comment]
The event that gets triggered is `show.zf.dropdownMenu`. The hide event is `hide.zf.dropdownMenu`
