### ISSUE TITLE
Drilldown _hideAll does not work in 6.7.x

### ISSUE THREAD

**Issue by driskell** [foundation/foundation-sites#12308]
## What should happen?

When calling $element.foundation('_hideAll') on a Drilldown which is currently in a submenu should restore it to the root.

## What happens instead?

The Drilldown menu disappears

## Possible Solution

I believe a regression in #12038 caused this - as it adds new invisible classes to aid in keyboard navigation. However, the invisible class added to the root menu is not removed in a call to _hideAll, and so the submenu is hidden and the root menu never re-appears.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case on 6.7.3: https://codepen.io/Driskell/pen/oNeoJpa
Compare to 6.6.3 which works: https://codepen.io/Driskell/pen/NWvwmxW

## Context

N/A

## Your Environment

- Foundation version(s) used: 6.7.3
- Browser(s) name and version(s): Chrome 95 but also present in all other browsers
- Device, Operating System and version: macOS Monterey
- Link to your project: N/A

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by pebutler3** [comment]
@joeworkman can I take this one?

**Comment by joeworkman** [comment]
> @joeworkman can I take this one?

Go for it Mr. Butler! 😀

**Comment by driskell** [comment]
Thanks @pebutler3 !

**Comment by dejan-cti** [comment]
There is still an issue with this fix, because there can be other elements (other than `<ul>`) that receive `invisible` class, and don't get properly removed on `hideAll()`. 

I've noticed `is-closing` class is being added when keyboard is used for tabbing, which then gets replaced with `invisible` class that never gets removed on `hideAll()`
