### ISSUE TITLE
foundation.min.css and foundation.min.js downloads are all messed up

### ISSUE THREAD

**Issue by travisengh** [foundation/foundation-sites#12314]
## What should happen?
Downloading these files should provide you with the essential files you requested and should be able to be used immediately
...

## What happens instead?
The files are all jumbled into single lines and out of order syntax wise
...

## Possible Solution

None at the moment.
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case:  This is not a bug, but an inconsistency in the downloads

How to reproduce:
1. Download the entire package and see if it happens again.
2. It happens every time I download the package.
3.

## Context

I have been unable to utilize the foundation.min.css file for my portfolio website. I have been using the foundation.css file, but don't need all of the extras.
...

## Your Environment

- Foundation version(s) used: 6
- Browser(s) name and version(s): Chrome and Firefox
- Device, Operating System and version: Fedora 
- Link to your project: No link currently available.

## Checklist

- [ x ] I have read and follow the CONTRIBUTING.md document.
- [ x ] There are no other issues similar to this one.
- [ x ] The issue title and template are correctly filled.

I have attached an image below:
![Screenshot from 2021-11-05 09-50-14](https://user-images.githubusercontent.com/84947185/140530362-619cefca-fbb4-4316-bf87-ef69215a5b14.png)
![Screenshot from 2021-11-05 09-53-43](https://user-images.githubusercontent.com/84947185/140530689-97350f92-eb7c-489d-aa28-543b1d4d37d9.png)

**Comment by joeworkman** [comment]
Answered here... https://github.com/foundation/foundation-sites/discussions/12313
