### ISSUE TITLE
Node Modules Not Installed after 'foundation new' on Windows

### ISSUE THREAD

**Issue by axfreeman** [foundation/foundation-sites#12329]
## Expected Behavior

I am using Windows 10

I am trying to create a new foundation project, following the installation instructions on the 'foundation for sites' page, version 6.7.4, using this URL 
[(https://get.foundation/sites/docs/installation.html)]

I have installed foundation-cli using the command 
`npm install --global foundation-cli`

I have node.js installed. Typing `node -v` yields `v16.3.0`

I use Visual Studio Code, and open a new blank folder. I open a terminal (the same result arises with Windows Powershell)

I try to create a new project by typing
`foundation new`

I expect to get a new working site

...

## Current Behavior

I am asked whether I wish a basic or email template and select 'a Website (Foundation for Sites)'

I entitle the project `mysite`

I am asked which template I wish to use and select Basic Template

mysite is created, but the script reports the error

` Node modules not installed. Try running yarn install manually.`

I type

cd mysite
npm install

(I have repeated using the suggested yarn install but the result is the same)

The install reports errors: the central such seems to be a problem with my version of Python - it faults a line written in Python2 syntax, thus:

`npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];`

...

## Possible Solution

there are two issues. 
The first is that node_modules is not installed in the project. I don't know why this fails
The second is that when trying to install this manually, the install script conflicts with my version of Python (3.10.0)
Maybe this can be fixed with a Python2 installation.
Or, maybe the script can be modified so it provides for a Python3 installation.

I'm new to foundation, so I don't have any other suggestions.
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.npm install --global foundation-cli
2.foundation new
3.select 'A Website'
4.select 'Basic Template'
`PS C:\Users\afree\Documents\Github\foundation> foundation new
? What are you building today? A website (Foundation for Sites)
? What's the project called? (no spaces) mysite
? Which template would you like to use? Basic Template: includes a Sass compiler`

## Context

I wanted to create a fresh foundation sites install
...

## Your Environment

- Foundation version(s) used: 6.7.4
- Browser(s) name and version(s):  no browser
- Device, Operating System and version: PC, windows 10
- Link to your project: couldn't create one

## Checklist

- [x ] I have read and follow the CONTRIBUTING.md document.
- [x ] This is a bug report or a feature request.
- [x ] There are no other issues similar to this one. (the nearest I could find was #11776)
- [x ] The issue title and template are correctly filled.

**Comment by kebalz** [comment]
For a less headache solution, just use the manual setup steps, here is my suggestion:

1. Install Yarn globally -> npm install -g yarn
2. git clone https://github.com/foundation/foundation-zurb-template your-projectname
3. cd to your-projectname
4. yarn (Just run the yarn command in the command line and let the process complete)
5. After the completion of step 4, run 'yarn start' to start building.

The result will be the same, or maybe even more faster than running the 'Foundation watch' (at least that what I have experienced thus far).

I hope that helps you.

**Comment by DanielRuf** [comment]
> For a less headache solution, just use the manual setup steps, here is my suggestion:

That is exactly the same, what the CLI does.

Please run `npm i -g windows-build-tools` to have Python 2 (needed by Node itself for compiling binary dependencies / packages like node-sass).

**Comment by kebalz** [comment]
> Please run npm i -g windows-build-tools to have Python 2
 
I did that, but the result is still not good.

'Foundation new' will only create the template without the Node Modules.

I am using windows 10, node v16.3.0 with npm v7.15.1 and Foundation CLI v2.3.0

Refer attached shot

![f6-cli--error-Screenshot_1](https://user-images.githubusercontent.com/13607335/141666198-5e77e509-3889-4142-a94f-c9150bae0008.jpg)

**Comment by DanielRuf** [comment]
Please try `npm i` manually or `yarn` (if it is installed) to see the actual errors.

**Comment by kebalz** [comment]
I did npm i, still within the same environment as the previous one.

The result is in the attached shot:
![f6-cli--error-Screenshot_2](https://user-images.githubusercontent.com/13607335/141679160-e5d6a8ef-7f12-4fe4-814c-67e56330e991.jpg)

**Comment by kebalz** [comment]
But then, the build tool running perfect via Yarn.

Refer attached shot:
![f6--yarn-Screenshot_2](https://user-images.githubusercontent.com/13607335/141679391-b2c4002a-bf47-4253-9b71-07aa7f8927f3.jpg)

**Comment by DanielRuf** [comment]
Your Node version is probably too new.

**Comment by DanielRuf** [comment]
Yarn is just an alternative package manager instead of npm. You should check if everything works with Node 14.

**Comment by DanielRuf** [comment]
At least Node 12 should work. See https://github.com/foundation/foundation-sites/actions/runs/1414129515

**Comment by kebalz** [comment]
> Your Node version is probably too new.

I see. I will try to check the installation again with different node environment as suggested above. 

But as at this point I am kind of loving Yarn more and more. The time it took to initialize the build-tools is very impressive.

Will report back here the result when I'm done experimenting with the recommended node version.

TQ.

**Comment by axfreeman** [comment]
Thanks for all these kind offers. Since there is still some experimentation going on, I will wait a bit. I will try the following

(a) 'pure yarn' as Kebalz suggests [https://github.com/foundation/foundation-sites/issues/12329#issuecomment-968076839](https://github.com/foundation/foundation-sites/issues/12329#issuecomment-968076839)

(b) Install Python 2

(c) Node 12.

I did already try a number of different routes to get the install, but without success.

I didn't realise at the time but it seems that ZURB is no longer supporting Foundation - a pity if it's true.

**Comment by ITZAP** [comment]
The Yarn procedure @kebalz posted will work for you.
@axfreeman I worked through all the installation issues you mention.
Check out the solutions I discovered here #12317

**Comment by DanielRuf** [comment]
Generally yarn is not required to get it working. Also please always use the windows-build-tools and then open a new terminal session. `npm audit fix` is generally problematic in most projects. Regardinf'g the primordial issue, this is well known (please search the issues and stackoverflow). It means that your Node version is too new. Node 12 or 10 is supported.

**Comment by ITZAP** [comment]
@DanielRuf thank you !
So bottom line: The Foundation installation procedure needs a bigtime workover to iron out all the issues users are encountering.

**Comment by DanielRuf** [comment]
Afaik the new maintainer is currently working on it. Besides this, you can always switch to a different Node version with `nvm`, `nodenv`, `n` or any alternative solution.

**Comment by kebalz** [comment]
> (a) 'pure yarn' as Kebalz suggests #12329 (comment)

The conclusion to the installation test that have been run by @ITZAP really reflecting my experience after upgrading the CLI and the node.js.

Now  I just use the CLI to generate the folder structure and then Yarn to get the Node_modules and to initialize the Build-Tools. The solution works great.

Currently using windows 10, node 16.3.0, npm 7.15.1, Foundation-cli 2.3.0

> I did already try a number of different routes to get the install, but without success.
To @axfreeman, you might want to check your git version. I currently run git version 2.24.0.windows.2 . Not sure whether that will make any different to your situation. but just in case.

**Comment by joeworkman** [comment]
Node 12 & 14 are currently functional. In order to support newer versions of node, a lot of work would need to be done to determine which dependencies are breaking on Node 16+. If anyone would like to assist in figuring that out, a PR would be much appreciated.

**Comment by axfreeman** [comment]
Thanks all. I'm a newbie to JS frontend coding in general so on a learning curve. The discussion is helpful, thanks to all. I've studied @ITZAP's post  #12317 which I'd recommend to anyone studying this thread, and I will try downgrading node and git. I hope this thread has been useful to the maintainers. @DanielRuf https://github.com/foundation/foundation-sites/issues/12329#issuecomment-970850851 what search terms would get me to relevant posts on the primordial issue? I did some searching just using the error message, but didn't come across much, which is why I started this thread.

**Comment by DanielRuf** [comment]
@axfreeman git is not the problem and should not be downgraded. Same for Node.

In this case install an older version with nvm and switch to it, so other projects can still use new Node versions.

Regarding "primordials is not defined":

https://www.google.com/search?q=primordials+not+defined+stackoverflow

https://github.com/foundation/foundation-sites/search?q=primordials&type=issues

https://stackoverflow.com/questions/56245622/foundation-referenceerror-primordials-is-not-defined-when-starting-a-foundat/56253873#56253873

**Comment by axfreeman** [comment]
@DanielRuf thanks. I see what the problem is now.
