### ISSUE TITLE
Fix Colorname Selectors SASS Warning ("You probably don't mean to use the color value black in interpolation here.")

### ISSUE THREAD

**Issue by thomasfrobieter** [foundation/foundation-sites#12333]
Compiling foundation-sites with a current version of SASS (1.43.4), throws various of those issues:

> Warning: You probably don't mean to use the color value white in interpolation here.
> It may end up represented as white, which will likely produce invalid CSS.
> Always quote color names when using them as strings or map keys (for example, "white").
> If you really want to use the color value here, use '"" + $name'.
> 
>     ╷
> 377 │           &.#{$name} {
>     │               ^^^^^
>     ╵
>     node_modules/foundation-sites/scss/components/_button.scss 377:15  foundation-button()

Needs to be fixed by writing the selector like so:

`&#{"." + $name} {`

or 

`&.#{"" + $name} {`

.. but the first one doesn't look that ..hacky.

**Comment by joeworkman** [comment]
Would you like to submit a PR?

**Comment by joeworkman** [comment]
I tried to generate these same warnings but could not. What are you running to see these?

**Comment by thomasfrobieter** [comment]
I got these by running our custom gulp sass build task (stripped it down to the relevant part):

```
function buildSass() {
  return src(config.sassRegex, {
      since: lastRun(buildSass)
    })
    //find files that depend on the files that have changed
    .pipe(sassInheritance({
      dir: 'scss/'
    }))
    .pipe(plumber()) // Hint: Plumber always need to be piped first!
    .pipe(sass.sync().on('error', sass.logError))
    .pipe(rename({
      suffix: '.min'
    }))
    .pipe(dest('./' + config.folderCss));
};
```

Relevant Versions:

- sass: 1.43.5
- node: 14.17.6

Similar issues: 
https://github.com/ConciseCSS/concise.css/issues/52
https://stackoverflow.com/questions/57455245/how-to-i-solve-this-sass-interpolation-issue

**Comment by joeworkman** [comment]
Thanks. I will work on replicating this. Any PRs would be helpful if you have the time.

**Comment by glen-84** [comment]
I think a better fix is to just quote your map keys, as suggested in the [Sass documentation](https://sass-lang.com/documentation/values/maps):

> Most of the time, it’s a good idea to use quoted strings rather than unquoted strings for map keys. This is because some values, such as color names, may look like unquoted strings but actually be other types. To avoid confusing problems down the line, just use quotes!

So change something like:

```scss
$foundation-palette: (
    // ...
    black: #000
);
```

To:

```scss
$foundation-palette: (
    // ...
    "black": #000
);
```

Perhaps the Foundation Sass should do this as well, just to set an example.

**Comment by thomasfrobieter** [comment]
@glen-84 great simple fix, I've tested this right now, works perfectly fine! 

**So we just need to fix these files:**
- https://github.com/foundation/foundation-sites/blob/8846fdad0289d1a0a80929c92a4245fcb781c662/scss/settings/_settings.scss#L71
- https://github.com/foundation/foundation-sites/blob/8846fdad0289d1a0a80929c92a4245fcb781c662/scss/_global.scss#L27
- probably the docs

**Comment by ameotoko** [comment]
It seems that `_settings.scss` should not be edited directly, because it is (re)generated by a gulp task.
