### ISSUE TITLE
Reveal fullscreen safari 15 iOS touch location

### ISSUE THREAD

**Issue by billattalktome** [foundation/foundation-sites#12341]
## What should happen?
When using real full, in safari 15 on iOS, only when you have scrolled down on the opening page the touch coordinates are off.

you can view this on the foundation documentation, scroll down to open the full reveal and the close X can't be clicked in its normal position, it can be clicked only at the top of the X.  

If you close and open again, without scrolling the page at all you can see that you can click anywhere on the X to close.

We have a lot of options in our modal as we have a video player, and all the options/links are off.  If you zoom, switch tabs, switch orientation, anything to make the page repaint then it works as expected.

I have tried all kinds of hacks to work around this (resetting viewport scale, requesting video fullscreen and exiting, setting the page position fixed before opening the modal, nothing has worked.  

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://get.foundation/sites/docs/reveal.html scroll down to fullscreen reveal and try and click the center or bottom of the X on iOS safari 15.

iOS 15, safari 15, latest foundation.

- [ x] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.

**Comment by billattalktome** [comment]
Is there anyone that can give an update on this, foundation reveal full screen is basically unusable on iOS.

**Comment by joeworkman** [comment]
You can easily apply your own CSS for now to resize it to your liking using `max-width` and `max-height`
