### ISSUE TITLE
Equalizer not working in zurb foundation

### ISSUE THREAD

**Issue by pandiarajanrajamanickam** [foundation/foundation-sites#12357]
`<div class="tabs-wrapper">
            
            <ul class="tabs df-form-subtabs tabs-scroll-list" data-tabs="" data-equalizer="" role="tablist" id="forms-tab">
                                                              
                                      <li class="tabs-title is-active " role="presentation">
                      <a href="#pane22-annuity" role="tab" tabindex="0" aria-selected="true" aria-controls="pane22-annuity" data-equalizer-watch="" style="height: 55px;">
                        Annuity
                      </a>
                    </li>
                                                        
                                                    
                                      <li class="tabs-title end" role="presentation">
                      <a href="#pane22-life" role="tab" tabindex="0" aria-selected="false" aria-controls="pane22-life" data-equalizer-watch="" style="height: 55px;">
                        Individual
                      </a>
                    </li>
                                                        
                                                    
                                    
                                                            </ul>
          </div>`
Here, If I removed the data equalizer it is working fine for me. otherwise it is not working. what is the reason?

**Comment by joeworkman** [comment]
Do you have a webpage or codepen that illustrates the problem?

**Comment by pandiarajanrajamanickam** [comment]
> Do you have a webpage or codepen that illustrates the problem?

No

**Comment by denisahac** [comment]
@pandiarajanrajamanickam in order for us to see what was the problem you need to provide us detailed explanation on how the HTML is constructed and how are you calling the `Equalizer` module and etc. but it's best to provide us a sample page/codepen where you can replicate the issue?
