### ISSUE TITLE
Text Decoration Classes are not working!!!

### ISSUE THREAD

**Issue by EhsanT007** [foundation/foundation-sites#12350]
The text-underline, text-overline, text-line-through and text-truncate are not working as said in the docs [here](https://get.foundation/sites/docs/prototyping-utilities.html#text-truncate)

I downloaded foundation 6.7.4 [here](https://joeworkman-archive.s3.us-east-1.amazonaws.com/Foundation-Sites/css-project/latest/Foundation-Sites-CSS.zip)

When I search for these classes for example the class text-underline in the foundation.css, there is no such class!!!

**Comment by joeworkman** [comment]
The prototyping utility classes are not compiled into the CSS download. You will need to use the Sass version and compile a build in order to have them built into the framework CSS. 

https://get.foundation/sites/docs/starter-projects.html#zurb-template
