### ISSUE TITLE
Where is customise foundation page? In 6.7.4

### ISSUE THREAD

**Issue by DigitalStorm1** [foundation/foundation-sites#12402]
## Description

...

## Possible Solution

...

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DigitalStorm1** [comment]
Cannot find customise foundation as described in video

**Comment by fkazemi5236** [comment]
Yes, it is
One of the differences between Foundation and other frameworks was that the user had the power to choose between options.
