### ISSUE TITLE
Version 6.4.2 Dropdown submenu not opening on TAB keystroke focus

### ISSUE THREAD

**Issue by skeeneyman** [foundation/foundation-sites#12425]
We are being audited for OCR compliance and one of their main issues is the fact the sub menus of our top navigation do not open with a TAB keystroke.

On focus (TAB keystroke) submenus open. Basically, I need the menus to mimic the hover event.

...

On focus (TAB keystroke) submenus do not open but instead require an arrow down to open submenus

...

If this already a feature, maybe somebody can tell me how to activate it.

...

https://nutrition.fultonschools.org/ open the website and attempt to use the tab key to access the top navigation sub menus.

...

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Chrome
- Device, Operating System and version: Windows 10
- Link to your project:  https://nutrition.fultonschools.org/

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x ] This is a bug report or a feature request.
- [x ] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.

**Comment by joeworkman** [comment]
I do not think that behavior is a common standard. Do you have an example that works as you describe?
