### ISSUE TITLE
sass Tutorial image Link broken

### ISSUE THREAD

**Issue by niccokunzmann** [foundation/foundation-sites#12424]
## Description

https://get.foundation/learn/advanced-sass-hmanchanda-1.html

When I click on the sass Tutorial image, I hat to an almost blank site. See screenshot. That image.
...

## Possible Solution

...

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

![Screenshot_20220502-090704](https://user-images.githubusercontent.com/564768/166197490-3bfda0ce-1026-4b41-8800-e2610de2aee6.png)

**Comment by joeworkman** [comment]
Thanks. I removed that from the list. I will be removed from the site shortly.
