### ISSUE TITLE
[Flex Grid] ISSUE NAME HERE

### ISSUE THREAD

**Issue by balveerchhimpa** [foundation/foundation-sites#12478]
How we can use foundation-flex.css via CDN or direct path , without any import method.
I want put direct foundation-flex.css in my html code

please help

**Comment by maietta** [comment]
Your question lacks any real information and is posted in the wrong repository. Please close this issue and try again in the correct forum with more information so people can understand what it is you are trying to do.

**Comment by BaveerChhimpa** [comment]
How we can use foundation-flex.css via CDN or direct path , without any import method.
I want put direct foundation-flex.css in my html code

please help
