### ISSUE TITLE
GUI VERY BADE

### ISSUE THREAD

**Issue by Abdellox** [foundation/foundation-sites#12470]
Be Simple .. 
Make it easy it will be strong...

Too much talk is useless...

You must immediately rearrange the site

 Oraganization  Oraganization  Oraganization   Oraganization  Oraganization  Oraganization  Oraganization  Oraganization  Oraganization .............................................

**Comment by maietta** [comment]
Um, okay?

**Comment by joeworkman** [comment]
I spent a long time patching some bandaids on the existing website last month. It's far from perfect but it will do until we can get a fresh and clean site For F7. I don't want to waste too much time developing a new site for F6 right now.

**Comment by maietta** [comment]
> I spent a long time patching some bandaids on the existing website last month. It's far from perfect but it will do until we can get a fresh and clean site For F7. I don't want to waste too much time developing a new site for F6 right now.

Hi Joe.

I see you a lot around here, looks like you are doing most of the maintenance and other work from what I can see. I would like to talk with you about the direction of F7 and what I can do to assist. I'm sort of in the dark here about the direction of 7 but I suspect 7 needs to work both as a standalone framework but also be compatible to be dropped into other build frameworks. I am using Foundation 6.5.x with Vue 3 using the Vite build system and it works quite well, but it's a bit of a hack to get it working right.

I'd like to see how I can be of help here as I'd love to see a 7 come to fruition. Would you be willing to have a short conversation with me on the matter? If so, shoot me an email and I'll send you my cell. If so, it's nick@premoweb.com. Thanks.
