### ISSUE TITLE
Custom Download CSS not found

### ISSUE THREAD

**Issue by BaveerChhimpa** [foundation/foundation-sites#12482]
Hi

How we can use **custom download** css from latest website ?

**Comment by markparnell** [comment]
@BaveerChhimpa the custom download page is no longer available - it was hosted separately from the main site. You can try running a local copy of it (see e.g. https://github.com/foundation/foundation-sites/issues/12189#issuecomment-753383167), however we've tried that ourselves on a number of different machines without success.

We've been using Foundation for years, but the inability to generate a custom download means we are seriously looking at alternatives.

**Comment by maietta** [comment]
The long term solution would be to incorporate the SASS version into a build system.

I put together a Vue 3 + PHP stack that incorporates Foundation for Sites as an alternative to Custom Download method. I never looked back.

You can check out the system here:
 https://github.com/PremoWeb/SDK-Foundation-Vue/tree/main/frontend
