### ISSUE TITLE
Support dart sass

### ISSUE THREAD

**Issue by valentinsenm** [foundation/foundation-sites#12493]
## What is missing?

Compatibility with dart-sass.

## What is wrong now ?

Using dart-sass, I get a lot of warnings (which you can choose to quiet with `--quiet-deps`). But it would be nice to  be able to use it and know that it will work in the future too. 

## Context

Both node-sass and ruby-sass is now deprecated and recommends switching to use dart-sass instead. Additionally, node-sass doesn't support mac's arm64, so people with newer macs simply aren't able to build anything with it. 

## Your Environment

Foundation 6.7.5
Sass 1.55.0

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by stephanebastian** [comment]
I could provide a pull request if is still maintained and PR are merged (which is not what it looks since the last merge goes  back to July 2022)
