### ISSUE TITLE
Support on maintaining legacy projects with m1 / arm64

### ISSUE THREAD

**Issue by ursbraem** [foundation/foundation-sites#12509]
## What is wrong now ?
We have a few foundation legacy projects that don't seem to be working on arm64 processor (using ddev with a debian docker container, so it's basically linux on arm64). I would appreciate some advice on how to migrate those to a stable buildable setup. Either by simplifying the dependencies to what is really needed, compatibility with newer node versions, or just moving to a simpler gulp process (build, watch, copy js and scss, no templating, no bower, no browsersync etc.)

## Current state

This works on a intel mac inside a ddev linux container:

```
#!/bin/bash

npm install nvm;
nvm install 10;
nvm use 10;
npm install -g --silent foundation-cli@2.2.5;
npm install -g --silent gulp-sass@4;
npm install -g --silent bower;
cd packages/sitepackage/Resources/Private/Foundation;
bower install
npm install --silent
echo "🎉 Now you can use foundation watch and build."
```

On a m1 mac I can use `npm install -g --silent gulp-sass@8;` and `npm install --only=production` (as @DanielRuf) suggested in the phantomjs discussions here to get through the install. 

But then I get the `Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 10.x` upon `foundation build`

I have seen in the issues that node-sass errors are not strictly a part of foundation, of course. Thing is, when I change node to higher versions, other things in foundation will fail. 

So I'm a bit stuck here and wanted to enquire for some guidance on how to make such a project maintainable again.

PS: how do I read the version of foundation? `foundation -v` is the cli of course so no use

**Comment by joeworkman** [comment]
6.9 is shipping today. It requires node 18 though.
