### ISSUE TITLE
warning " > sass-true@4.0.0" has incorrect peer dependency "node-sass@^4.0.0".

### ISSUE THREAD

**Issue by jee-mj** [foundation/foundation-sites#12510]
upon cloning into the repo, running yarn nets the following:
![image](https://user-images.githubusercontent.com/28581723/204703230-3672c534-8ec6-4d20-8401-ff41e4a57012.png)

## Description

I don't know what the problem is.
...

## Possible Solution

It is beyond me to suggest a potential solution at this stage. The best I can do to help a solution be identified is report this as an issue.
...

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by anitagraham** [comment]
I don't think it is your problem, amd your build is being built.
You might find it works 'better' if you install dart-sass instead of node-sass.
