### ISSUE TITLE
warning " > foundation-sites@6.7.5" has incorrect peer dependency "motion-ui@latest".

### ISSUE THREAD

**Issue by maietta** [foundation/foundation-sites#12532]
Not a big deal, just a warning. However, I feel I should drop a line here mentioning it. Seems only one "solution" exists on line to remove this and that's to move from node-sass to sass as the node-sass dependency is depreciated. That doesn't apply here.

warning " > foundation-sites@6.7.5" has incorrect peer dependency "motion-ui@latest".

I've been told and I agree, that using the "latest" tag in dependencies are generally a bad idea and thus I think could be the reason for this warning. Not sure. It's hardcoded in the packages.json in this project repo.

Don't know if this should be hardcoded and resolve this warning, or left as-is as so far, nothing seems actually broken.

**Comment by maietta** [comment]
> This could easily be resolved by replacing the tag `@latest` by the actual required base dependency like the other ones. Anyone in the team willing to do that? If not I can submit a PR for this... but this seems overkill.

Thanks for pointing that out. Seems like such a simple fix but I'm actually not sure the correct way to implement this in my projects. Would love to see this fixed in the repo.

**Comment by erutan** [comment]
> Thanks for pointing that out. Seems like such a simple fix but I'm actually not sure the correct way to implement this in my projects. Would love to see this fixed in the repo.


`    "motion-ui": "^2.0.3",` is in my package.json and my site builds on 6.7.5.

`    "motion-ui": "2.0.4",` should work and be more explicit.

I'm using zurb-foundation-template for a small site I built for someone and am just keeping it on 6.7.5:

` "foundation-sites": "~6.7.5",`
