### ISSUE TITLE
[Welcome to Foundation 6] ISSUE NAME HERE

### ISSUE THREAD

**Issue by Adromane** [foundation/foundation-sites#12540]
## Expected Behavior

...

## Current Behavior

...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by Adromane** [comment]
How fonction  the other issues

**Comment by Adromane** [comment]
that's just it what i want know

**Comment by maietta** [comment]
Please close this.
