### ISSUE TITLE
i wanna know how i can do my Code review in the my github

### ISSUE THREAD

**Issue by Adromane** [foundation/foundation-sites#12556]
## What should happen?

...

## What happens instead?

...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by Adromane** [comment]
i wanna know how i can do my Code review in the my github

**Comment by Adromane** [comment]
Say me  how i can do my Code review in the my github

**Comment by maietta** [comment]
Hey @Adromane You need to stop spamming. **I have reported your account for review.**

**If you have any important data on GitHub, now would be a great time to obtain a backup.**

**Comment by ameotoko** [comment]
This repo is turning into a trash dump

**Comment by maietta** [comment]
> This repo is turning into a trash dump

That's like, just your opinion, man.

It's more active than any repo you can start.

**Comment by Adromane** [comment]
Ok
