### ISSUE TITLE
Sidebar navigation on the sites v6 docs site is broken

### ISSUE THREAD

**Issue by timgilbert** [foundation/foundation-sites#12564]
Looking at the [official documentation site](https://get.foundation/sites/docs/) many of the links in the sidebar are currently broken. For example, the "Installation" link goes to https://get.foundation/installation. Looks like the actual URL is https://get.foundation/sites/docs/installation.

It seems like some of the links are correct on the main page, but then when you navigate to a different page, most of the links there are broken.

This seems to have happened in the last few days.

## Current Behavior

Many links lead to 404 pages

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:
1. Navigate to https://get.foundation/sites/docs/
2. Click any link in the left-side menu
3. On the resulting page, click a different sidebar link

## Your Environment

(n/a)

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by delightsofdecay** [comment]
Came to report this same issue. My current work around is to search "site:" with Google.

**Comment by amazingsey** [comment]
Same issue, my current workaround is manually editing the url to the right format. 
E.g. clicking on Off-canvas under Containers leads to
`https://get.foundation/off-canvas` (broken) but the correct url is
 `https://get.foundation/sites/docs/off-canvas.html`

**Comment by Asterovim** [comment]
Same bug here with chrome / edge.

**Comment by joeworkman** [comment]
dup #12578
