### ISSUE TITLE
[Welcome to Foundation 6] Foundation Documentation Links Broken

### ISSUE THREAD

**Issue by ccpotter** [foundation/foundation-sites#12575]
## Expected Behavior

https://get.foundation/sites/docs/xy-grid
...

## Current Behavior

Links are absolute paths. They are linking from a root expectation and should be /sites/docs/[LINKNAME]
https://get.foundation/xy-grid
...

## Possible Solution

Make links either relative or add /sites/docs/[LINKNAME]
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Use the left sidebar https://get.foundation/sites/docs/. All links are broken 404s. Should be an easy fix.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] This is a bug report or a feature request.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by joeworkman** [comment]
dup #12578
