### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by CoderofOne** [foundation/foundation-sites#12571]
## Description

Go to https://get.foundation/sites/docs/

Click on
General > XY Grid
https://get.foundation/xy-grid

## Possible Solution

...

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by adrianbbk** [comment]
This is the same for all items in the side navigation

**Comment by joeworkman** [comment]
dup #12578
