### ISSUE TITLE
Many docs pages not working

### ISSUE THREAD

**Issue by itserik0** [foundation/foundation-sites#12576]
## Expected Behavior

The Foundation docs pages should work
...

## Current Behavior

But most of them throw a 404 error. Like [this one](https://get.foundation/button). 
...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Navigate to Foundation docs
2. Click into any doc (ex [table](https://get.foundation/table))
3.

## Context

...

## Your Environment

- Foundation version(s) used: 6.5
- Browser(s) name and version(s): all 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] This is a bug report or a feature request.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by joeworkman** [comment]
dup #12578
