### ISSUE TITLE
update zurb-foundation-template package.json with new dart-sass dependency.

### ISSUE THREAD

**Issue by erutan** [foundation/foundation-sites#12588]
## What should happen?

The site should build.

## What happens instead?

The site errors out due to dependency failure.

## Possible Solution

Update package.json to use dart-sass vs node-sass.

This is discussed obliquely in https://github.com/foundation/foundation-sites/issues/12581 and https://github.com/foundation/foundation-sites/issues/12532 but there's no active issue to update zurb-foundation-template

## Test Case and/or Steps to Reproduce (for bugs)

Build a site using the zurb-foundation-template package.json

- [x ] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.

**Comment by joeworkman** [comment]
I will get this done today after the 6.9 release
