### ISSUE TITLE
!!["!Here's Gaa To Watch!"]#!! Offaly v Laois Live Coverage Free On final Gaa 08 June 2024

### ISSUE THREAD

**Issue by jokar2025** [foundation/foundation-sites#13128]
Laois v Offaly: Everything You Need To Know About The Joe McDonagh Cup Final
Laois v Offaly: Everything You Need To Know About The Joe McDonagh Cup Final
Finn Duffy
[🔴➤ ►🌍📺📱👉 gaa finle](https://free-online-tv-s.blogspot.com/2024/06/gaa.html)

[🔴➤ ►🌍📺📱👉 gaa finle](https://free-online-tv-s.blogspot.com/2024/06/gaa.html)

By Finn Duffy
Jun 08, 2024 12:15 PM
Share this article
Facebook Share
Twitter Share
Twitter Share
Twitter Share
Twitter Share
Laois are set to take on their neighbours Offaly this weekend in the final of the Joe McDonagh Cup as both sides look to grab hurling's second-tier competition and promotion to the provincial championships. Here's everything you need to know about this years Joe McDonagh Cup final Laois v Offaly.

The two sides began their championship campaign against each other in Portlaoise in April, with the O'Moore County getting the better of the Faithful County despite Offaly holding a 0-21 to 0-15 lead with less than 20 minutes to go. Laois midfielder Paddy Purcell would grab two late goals, including one in the last minute, to win his side the match 2-21 to 0-24.

READ HERE: The 10 Best Hurlers In Ireland Under The Age Of 20 In 2024
READ HERE: McManus Calls For Championship Restructure After Carlow Relegation
Laois would kick on with the momentum gained from the win and would subsequently batter batter Meath 7-29 to 1-16 in round two in Trim. Willie Maher's men would then travel to Austin Stack Park to face Kerry, where they would defeat the Kingdom 1-25 to 0-18. The O'Moore County booked their place in the Joe McDonagh final in a dominant 4-31 to 0-17 win over Down at home.

In the last day of fixtures, Laois travelled to Westmeath where they would lose for the only time in the round-robin, with the Lake men getting a 2-26 to 0-16 win in Mullingar. Despite this, Laois would still finish the round-robin at the top spot.

Meanwhile Offaly would bounce back quickly from their opening day defeat. They would welcome Westmeath to O'Connor Park in round two where the Faithful County would win 2-23 to 1-20 despite a red card to captain Jason Sampson within seconds of throw-in. Round three would see Johnny Kelly's side cruise past Meath 5-31 to 3-16 in Trim.

An impressive win 3-24 to 0-15 at home to Kerry in round four was followed by a round five win away to Down in Ballycran. Despite a late comeback effort by the home side, Offaly would win 5-23 to 3-25 in the end to round-robin second and book their place in the final.

**Comment by rajukar002** [comment]
ss

### **### [📺📱👉🥊 𝐂𝐋𝐈𝐂𝐊 𝐇𝐄𝐑𝐄 𝐎𝐍𝐋𝐈𝐍𝐄 𝐋𝐈𝐕𝐄 𝐒𝐓𝐑𝐄𝐀𝐌 ](https://t.co/3r79Zb5Hr5)**

### **### [📺📱👉🥊 𝐂𝐋𝐈𝐂𝐊 𝐇𝐄𝐑𝐄 𝐎𝐍𝐋𝐈𝐍𝐄 𝐋𝐈𝐕𝐄 𝐒𝐓𝐑𝐄𝐀𝐌 ](https://t.co/3r79Zb5Hr5)**

[![](https://camo.githubusercontent.com/d37c93bf5e010ce1a06bf1cfc5864d665e7dd3c652e62a7fecea7899c9f40262/68747470733a2f2f692e696d6775722e636f6d2f67645a6138456d2e6a7067)](https://t.co/3r79Zb5Hr5)



### **### [📺📱👉🥊 𝐂𝐋𝐈𝐂𝐊 𝐇𝐄𝐑𝐄 𝐎𝐍𝐋𝐈𝐍𝐄 𝐋𝐈𝐕𝐄 𝐒𝐓𝐑𝐄𝐀𝐌 ](https://t.co/3r79Zb5Hr5)**

### **### [📺📱👉🥊 𝐂𝐋𝐈𝐂𝐊 𝐇𝐄𝐑𝐄 𝐎𝐍𝐋𝐈𝐍𝐄 𝐋𝐈𝐕𝐄 𝐒𝐓𝐑𝐄𝐀𝐌 ](https://t.co/3r79Zb5Hr5)**

[![](https://camo.githubusercontent.com/d37c93bf5e010ce1a06bf1cfc5864d665e7dd3c652e62a7fecea7899c9f40262/68747470733a2f2f692e696d6775722e636f6d2f67645a6138456d2e6a7067)](https://t.co/3r79Zb5Hr5)

### **### [📺📱👉🥊 𝐂𝐋𝐈𝐂𝐊 𝐇𝐄𝐑𝐄 𝐎𝐍𝐋𝐈𝐍𝐄 𝐋𝐈𝐕𝐄 𝐒𝐓𝐑𝐄𝐀𝐌 ](https://t.co/3r79Zb5Hr5)**

### **### [📺📱👉🥊 𝐂𝐋𝐈𝐂𝐊 𝐇𝐄𝐑𝐄 𝐎𝐍𝐋𝐈𝐍𝐄 𝐋𝐈𝐕𝐄 𝐒𝐓𝐑𝐄𝐀𝐌 ](https://t.co/3r79Zb5Hr5)**

[![](https://camo.githubusercontent.com/d37c93bf5e010ce1a06bf1cfc5864d665e7dd3c652e62a7fecea7899c9f40262/68747470733a2f2f692e696d6775722e636f6d2f67645a6138456d2e6a7067)](https://t.co/3r79Zb5Hr5)


### **### [📺📱👉🥊 𝐂𝐋𝐈𝐂𝐊 𝐇𝐄𝐑𝐄 𝐎𝐍𝐋𝐈𝐍𝐄 𝐋𝐈𝐕𝐄 𝐒𝐓𝐑𝐄𝐀𝐌 ](https://t.co/3r79Zb5Hr5)**

### **### [📺📱👉🥊 𝐂𝐋𝐈𝐂𝐊 𝐇𝐄𝐑𝐄 𝐎𝐍𝐋𝐈𝐍𝐄 𝐋𝐈𝐕𝐄 𝐒𝐓𝐑𝐄𝐀𝐌 ](https://t.co/3r79Zb5Hr5)**

[![](https://camo.githubusercontent.com/d37c93bf5e010ce1a06bf1cfc5864d665e7dd3c652e62a7fecea7899c9f40262/68747470733a2f2f692e696d6775722e636f6d2f67645a6138456d2e6a7067)](https://t.co/3r79Zb5Hr5)


[![](https://camo.githubusercontent.com/d37c93bf5e010ce1a06bf1cfc5864d665e7dd3c652e62a7fecea7899c9f40262/68747470733a2f2f692e696d6775722e636f6d2f67645a6138456d2e6a7067)](https://t.co/3r79Zb5Hr5)



☝️

☝️

☝️
