### ISSUE TITLE
[Accordion Menu] Adding a nested menu after creation does not work 

### ISSUE THREAD

**Issue by dmamolina** [foundation/foundation-sites#8301]
**How can we reproduce this bug?**

Create an empty accordion menu

``` html
<ul id="navigation" class="vertical menu" data-accordion-menu>
</ul>
```

Add a nested menu and reInit:

``` javascript
      var liItem = '<li>' + 
              '<a href="#">Test</a>' + 
              '<ul class="menu vertical nested">' +
              '</ul>' +
            '</li>';

      $('ul#navigation').append(liItem);
      Foundation.reInit($('ul#navigation'));
```

**What did you expect to happen?**

The elements of the submenu are not hidden and the arrow to collapse/expand the accordion is not shown.

Adding the `data-submenu` attribute to the `ul.menu.nested` element and the class `is-accordion-submenu-parent` to the `li` element fixes the issue:

``` html
<li class="is-accordion-submenu-parent">
  <a href="#">Test</a>
  <ul class="menu vertical nested" data-submenu>
  </ul>
</li>
```

These attrs and classes are included in the [Feather function of the nest util](https://github.com/zurb/foundation-sites/blob/master/js/foundation.util.nest.js#L22), but it looks like this method is not called with the Foundation.reInit call, but on creation.

**Comment by colin-marshall** [comment]
@Owlbertz @brettsmason can you please take a look at this? I see it was mentioned in #9348 which you guys had heavy involvement in. Thanks!

**Comment by Owlbertz** [comment]
Issue seems to persist, altough as the author said it can be avoided when applying the attributes manually.

I created [this pen](https://codepen.io/Owlbertz/pen/NyWyBw) for any further analysis.
Is this actually a bug (i.e. do we want `reInit()` to take care of these attributes)?

**Comment by DanielRuf** [comment]
What is the current status of this issue?

**Comment by DanielRuf** [comment]
Current status is that only the arrow is missing: https://codepen.io/DanielRuf/pen/GRRNRaP

**Comment by brettsmason** [comment]
@DanielRuf It's been a long time since I worked on this, but adding the class `accordion-menu` to the `UL` seems to add the arrow correctly. It does mention this in the docs: https://foundation.zurb.com/sites/docs/accordion-menu.html#submenu-toggle

**Comment by DanielRuf** [comment]
@brettsmason I guess we can close it then as this is documented?

**Comment by brettsmason** [comment]
@DanielRuf Yeah I'd say so.
However, you could make an arguement for it being mentioned in the basics section too, as the other menu components mention using their respective class, but accordion doesn't.
