### ISSUE TITLE
Accordion Menu Bouncing in Certain Cases

### ISSUE THREAD

**Issue by LDigital84** [foundation/foundation-sites#8403]
This bug may be related to #7157 but it's not the easiest to replicate. 

I happen to notice that on occasion when I have an accordion menu (in an off canvas) that the menus would "bounce" open and closed repeatedly. I would see it but not be able to reproduce it. 

My client finally found a way to make it happen. He said: 

> When one selects a new menu item, BEFORE the page has fully loaded, you can force a “bouncing menu.”

Even though we know how to make it happen, it still doesn't always happen, even when I attempt to force it.

Any thoughts on this?

**Comment by christianmagill** [comment]
I've experienced the same issue

**Comment by christianmagill** [comment]
Possibly related https://github.com/zurb/foundation-sites/issues/8411

**Comment by echavezNS** [comment]
Can I see the code, I check the closed issue #7157 and I saw that there is something wrong when using the class `is-active` combined with the attribute `aria-expanded="true"`

**Comment by Lynda333** [comment]
@echavezNS - Here is the site the code is on: http://www.kerryblues.info/ pull out the menu in the off canvas and that is the accordion menu.

**Comment by DanielRuf** [comment]
Hi @LDigital84,

We need a codepen to reproduce it in production for Foundation Sites 6.5.3.

**Comment by DanielRuf** [comment]
Closing as we did not get a codepen to reproduce it.
So we are labeling this issue as invalid and close it.
