### ISSUE TITLE
Interchange does not support JS fallback

### ISSUE THREAD

**Issue by paxperscientiam** [foundation/foundation-sites#8479]
Hi y'all,

This construct works perfectly when JS is disabled:

``` HTML
<a href="/assets/img/logos/large/type.png">
       <img data-interchange="[/assets/img/logos/small/type.png, small], [/assets/img/logos/medium/type.png, medium], [/assets/img/logos/large/type.png, large]" class="thumbnail" alt="Type Logo" src="/assets/img/logos/small/type.png">
      </a>
```

However, with JS enabled, both the media dependent image is loaded _and_ the fallback image referenced in the <img /> "src" attribute. If Interchange were to ignore the "src" attribute, then this would be resolved.

EDIT: removed extraneous markup.

**Comment by paxperscientiam** [comment]
One possible solution:
````js
<a data-interchange data-interchange="[/assets/img/logos/small/type.png, small], [/assets/img/logos/medium/type.png, medium], [/assets/img/logos/large/type.png, large]" href="/path/to/asset">
<noscript>
<img src="/path/to/asset" />
</noscript>
</a>
````

**Comment by andycochran** [comment]
Hmm… In the spirit of mobile-first design, maybe the `data-interchange` array should not have a `[file,small]` pair?

**Comment by paxperscientiam** [comment]
@andycochran Hello, what are your thoughts on the differences betweeen the `srcset` attribute of HTML5 and Foundation's `data-interchange` JS component?

A big benefit of `srcset` -- when supported -- is that the browser won't "double" download images.

Unfortunately, according to [caniuse.com](http://caniuse.com/#search=srcset), stupid IE does not support it.

So, in a sense, interchange is a polyfill for internet explorer(s).

**Comment by IamManchanda** [comment]
Its so unfortunate that due to MR IE,
Things like [Picture tag](http://caniuse.com/#search=picture) and [srcset](http://caniuse.com/#search=srcset) can't get a go till now and we have to use something interchange!

**Comment by DanielRuf** [comment]
> Its so unfortunate that due to MR IE,
> Things like Picture tag and srcset can't get a go till now and we have to use something like interchange!

Except we use picturefill.

**Comment by DanielRuf** [comment]
> However, with JS enabled, both the media dependent image is loaded and the fallback image referenced in the "src" attribute. If Interchange were to ignore the "src" attribute, then this would be resolved.

This can not be prevented because the browser reads the `src` attribute and downloads the file. We have no control over this in general.

**Comment by DanielRuf** [comment]
You can prevent this by using a base64 fallback image which is very small (some placeholder).
