### ISSUE TITLE
[Equalizer] wrong height

### ISSUE THREAD

**Issue by pavelblazek** [foundation/foundation-sites#8684]
**How can we reproduce this bug?**
1. I'm using Drupal CMS
2. have two divs - first with text, second with image with data-interchange
3. seems it takes longer to load the image so the height is set by first (smaller) div with text
4. the height of div with img is wrong - img overflows
5. if I use just img without the data-interchange the height is set correctly
6. the only difference is if I use the data-interchange on img

**What did you expect to happen?**
Same height - I guess load the image first and than set the height. Might be caused by the Drupal
**What happened instead?**
The height is not set right - img overflows
**Test case:**
tested on CodePen - works fine

Give us a link to a CodePen or JSFiddle that recreates the issue.
- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by denisahac** [comment]
Can you resubmit the correct CodePen/JSFiddle links.

**Comment by pavelblazek** [comment]
http://codepen.io/pavelblazek/pen/YqObeW

It sets the height correctly when you resize the window, but not when it's loaded for the first time

**Comment by designerno1** [comment]
check it without interchange = works
Issue related to interchange img, equalizer check for loaded img, interchange (img without src) `img.complete = true`
maybe adding a case to the foundation onImagesLoaded function?

**Comment by jsilver951** [comment]
This is how I addressed this on a recent project. 

`	
$('*[data-equalizer] img').on('load', function() {
    new Foundation.Equalizer($("body"));
    // console.log("Equalizer after image loads");
});
`

**Comment by Jflem1290** [comment]
@jsilver951 - I found that the similar solution worked for me when using  `$(window).on("load", function(){})`. This way everything on the page gets initialized / loaded. 

Ref: Initializing
  http://foundation.zurb.com/sites/docs/javascript.html
   Although in the docs() under JavaScript it states that "$(document).foundation(); will kick off every Foundation plugin at once. " be sure to include a new instance of [Equalizer](http://foundation.zurb.com/sites/docs/equalizer.html).
` var elem = new Foundation.Equalizer(element, options);`

Reference from jQuery [document.ready](https://learn.jquery.com/using-jquery-core/document-ready/) - 
    Initializing the code below will run once the entire page is ready and has been loaded. I.e our images and text. 

    $(window).on("load", function() {
        //Foundation.Equalizer
        //referencing - http://foundation.zurb.com/sites/docs/equalizer.html
        //new Foundation.Equalizer - Creates a new instance of Equalizer.
        new Foundation.Equalizer($("body"));
    });

I would love some feedback as I am relatively new to Equalizer. Thanks!

**Comment by kball** [comment]
@Jflem1290 and @jsilver951 : The solution you've come to of running Equalizer after load seems reasonable in the general case - there's no way Equalizer can ever know about all the things that might cause heights to change - however I'd like it if we could build in some checks for the common case.

What if Equalizer checked each of its watched elements for images and waited for them all to load?  We could include a fallback of 5 or 10 seconds to handle things timing out or just getting stuck.

**Comment by Jflem1290** [comment]
@kball & @jsilver951 
I have made some changes based off of @kball feedback above. 
Changes made: Wrap the on.(load'... in a function, call the function, and lastly call the function again after x seconds to make sure that all of image loaded

```
var loadingAllImages = function() {
    $('*[data-equalizer] img').on('load', function() {
        new Foundation.Equalizer($("body"));
    });
}
loadingAllImages();	
setTimeout(loadingAllImages, 5000)
```
[Codepen](http://codepen.io/jflem1290/pen/QEVOXO)
There were a few other options that I tried integrating, but this seemed to work best for me.

I have provided a [link](http://stackoverflow.com/questions/544993/official-way-to-ask-jquery-wait-for-all-images-to-load-before-executing-somethin) to a referenced I used along with some other options such as using plugins for image loading, loading images dynamically, etc.

**Comment by Jflem1290** [comment]
@kball & @jsilver951 
I have made some changes based off of @kball feedback above as well as offline.

In the code below, I have made the Equalizer Plugin dependent upon the loading of all `[data-equalizer]` images. Also, I created a resize event which is initialized when the user changes the orientation of their device (mobile: tablet, phone)

```
$('*[data-equalizer] img')
        .load(function() {
            // init the Equalizer plugin after the images have been loaded
            var initEqual = new Foundation.Equalizer($("body"));
            // retrigger initEqual when the window is resized
            $(window).resize(function(initEqual) {
                console.log('window resized, load plugin again in case of height change);
                initEqual;
            })
        })
        .error(function(initEqual) {
            console.log('an error has occured')
        });
```
What I am contemplating is what to do in .error() so it works for all users. 
Error() can try to reload images, but if you made a mistake with file naming (image.png instead of image.jpg) this error will not be resolved unless it is changed. The initEqual variable should not be recalled in the error event because it will re-run until the error is resolved. 

[Link](http://codepen.io/jflem1290/pen/KrAYGQ) to Codepen example.
I would greatly appreciate any feedback. Thanks!

**Comment by jsilver951** [comment]
$(window).resize() calls the script too often and too many times on gallery pages. I have a throttle on mine that runs the script at intervals of 500ms. I'll post this tomorrow. 

Jflem1290, I agree that reloading initEqual wouldn't help if there's a hard code issue (file name) but it might if something loaded out of sync. Maybe increment a counter and only reinitialize it if the count is less than 2? Adding a console.log with the image's class or id and a message would be helpful for developers to personalize or comment out if they want to. 

@kball I feel that adding a timeout of 5 seconds for images to load will hinder people on slower connections or if a large number of images are being loaded.

**Comment by groovenectar** [comment]
To expand on @jsilver951's  suggestion, this snippet address issues with image caching and the event not being called:

```
jQuery.fn.extend({
    ensureLoad: function(handler) {
        return this.each(function() {
            if(this.complete) {
                handler.call(this);
            } else {
                jQuery(this).load(handler);
            }
        });
    }
});
```

```
jQuery(document).ready(function ($) {
    jQuery(document).foundation();

    jQuery('[data-equalizer]').find('img').ensureLoad(function() {
      new Foundation.Equalizer(jQuery('body'));
    });
});
```

Based on this: http://stackoverflow.com/questions/5624733/jquery-load-not-firing-on-images-probably-caching

**Comment by groovenectar** [comment]
Here is an update that seems to work even smoother:

```
jQuery(function ($) {
    $(document).foundation();
});

jQuery(window).on('load', function ($) {
    Foundation.reInit('equalizer');
});
```

This way you can get the speed of initializing at document ready, then fix just the equalizer height (if applicable) on window load

**Comment by kball** [comment]
Should be fixed in 6.3 by #9126

**Comment by rbrlortie** [comment]
I seem to be having this issue with _6.4.3_.

Equalizer won't listen to resize when the user starts as small and equalize on stack is set to false unless I set `data-resize` manually on the parent div. 

The only way to make it work correctly otherwise seems to use this snipped (as said above.)

```
jQuery(function ($) {
    $(document).foundation();
});

jQuery(window).on('load', function ($) {
    Foundation.reInit('equalizer');
});
```


This adds the `data-resize="myEqualizerId` attribute to the element and Foundation's Triggers then should be able to pick it up when it adds its listeners.

Problem is that this doesn't work when the user starts as small. I need to manually add `data-resize`, otherwise its never picked up when you size up to the next breakpoint. I see in util.triggers that it looks for $nodes using `jQuery('[data-resize]')` but this never returns anything since this script runs before the equalizer and nothing has `data-resize` yet unless set manually.

**Comment by DanielRuf** [comment]
The issue seems to be other elements like interchange.

https://codepen.io/DanielRuf/pen/gOOLLGg works.
This epens on your setup and on asynchronous code.
