### ISSUE TITLE
Shouldn't the custom download contain only checked items?

### ISSUE THREAD

**Issue by fluxxus** [foundation/foundation-sites#8806]
I went to download only the flex grid, checking only flex grid from all the available options.

Out of curiosity, why did the downloaded CSS contained normalize, type presets, animation classes?

I am not complaining, it is not hard to remove those styles and leave only the flex grid, but it would be much nicer if the downloaded package contained only the checked items.

**Comment by colin-marshall** [comment]
@Madebym normalize is a requirement for all Foundation components so it's included by default as a dependency on all customizer downloads. The point of customizer is so that you can select components and download a zip that allows you to be up and running right away.

The flex-grid, as far as I know, is not dependent on the animations classes so those do seem out of place in your download. #7033 is tracking customizer issues, I will ask in there.

**Comment by Madebym** [comment]
@colin-marshall Yes, I get the point of customizer, that is why I wanted only the flex-grid.

One correction to my initial message, Normalize is included(I understand that it is a dependancy), there are no typography presets, but the animation classes are definitely there.

So, the only intruder are the animations.

**Comment by DanielRuf** [comment]
So far motion-ui is generally imported.

See https://github.com/zurb/foundation-sites/blob/266378bbbf941ce5d51bc16c722e75f0c3c89d35/customizer/lib/sass.js#L13 and https://github.com/zurb/foundation-sites/blob/266378bbbf941ce5d51bc16c722e75f0c3c89d35/customizer/lib/sass.js#L19-L20

**Comment by DanielRuf** [comment]
There is no checkbox to add / remove motion-ui.

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/develop/customizer/lib/sass.js#L55-L62

**Comment by DanielRuf** [comment]
@colin-marshall who has access to the customizer repo and can jump in here?

**Comment by colin-marshall** [comment]
@DanielRuf we'll have access soon when we migrate everything. I'd say this issue is pretty low priority at this time.

**Comment by DanielRuf** [comment]
Ok, thanks for the info.

**Comment by DanielRuf** [comment]
@colin-marshall who would be responsible then and do the needed changes?

**Comment by DanielRuf** [comment]
Closing for now. We will rewrite many parts of the customizer.
