### ISSUE TITLE
button-dropdown not respecting $offset

### ISSUE THREAD

**Issue by diniscorreia** [foundation/foundation-sites#9030]
Hi there,

When using the button-dropdown mixin, the last parameter (offset/distance from arrow icon to button text) isn't respected - it always gets the default value (the right padding of the button).

Seems like an easy fix: the component mixin actually gets `get-side($button-padding, right)` instead of `$offset` on line 163 of button.scss

Thanks!

**Comment by DanielRuf** [comment]
@canterberrie could you still take a look at it?

**Comment by DanielRuf** [comment]
Not relevant anymore.

**Comment by DanielRuf** [comment]
The parameter is already passed through and has a default value. So it can be overwritten / set.
