### ISSUE TITLE
Magellan: include negative destination.margin-top when activating target link

### ISSUE THREAD

**Issue by klihelp** [foundation/foundation-sites#9155]
**How can we reproduce this bug?**
1. Add -10px margin-top for [data-magellan-target] destination element.
2. Target link will not activate when eg. destination_element.offset().top is 10px less

**What did you expect to happen?**
Link activates when destination_element.top-border hits the window.top.

**What happened instead?**
Link activated when destination_element.top-border 10px out..

**Comment by DanielRuf** [comment]
Hi @klihelp,

can you provide a PR?

**Comment by DanielRuf** [comment]
Unfortunately we also have no codepen or example to reproduce this.

We will reopen this issue when we have these details so we can test this and create a PR to resolve this.
