### ISSUE TITLE
Accordion: toggle/up/down methods acting strange

### ISSUE THREAD

**Issue by justinshaw** [foundation/foundation-sites#9199]
All relevant information is in [this](http://foundation.zurb.com/forum/posts/46990-accordion-toggleupdown-methods-acting-strange) forum post on foundation.zurb.com.

I discovered this over a month ago and am not willing to re-familiarize myself with it to flesh out the description in this issue given the detail in that forum post, but short of it is that there's a problem wherein I had to force the attributes related to the expansion of a given panel to take on the values of an active panel. Otherwise the target panel would act as if it was active, but the accordion would not toggle. That was the workaround for what I perceived to be a bug.

**Comment by DanielRuf** [comment]
The target it the needed `data-tab-content`.

See https://codepen.io/DanielRuf/pen/mddOWRo?editors=1010 and https://github.com/foundation/foundation-sites/blob/3bc6d728dc9f03ae7f6f608990922bb69299b62b/js/foundation.accordion.js#L172
