### ISSUE TITLE
Dropdown Pane appearing in corner of screen

### ISSUE THREAD

**Issue by merlinpatt** [foundation/foundation-sites#9244]
**How can we reproduce this bug?**
Unfortunately this is a difficult to reproduce bug. I've only encountered it once, which is the screenshot you see. Another engineer on our team says they encountered it about half the time.

I apologize for not having clearer instructions or a code reproduction but I hope the screenshot helps. As you can see, for some reason, the pane is being absolutely positioned to the top left corner of the screen. I could fix this by turning off `position: absolute` or forcing a `top` and `left` value of 0, but I'd like to know why this is happening so I can prevent it in a less hack-ish way.

I looked through the [dropdown code for our version (6.1.2)](https://github.com/zurb/foundation-sites/blob/c8752851d92ce3d129811ffc10d91e02111e9a4c/js/foundation.dropdown.js) and I can't even find any code that sets the position absolutely. A search for `top` or `left` only returns results related to the pane position, not CSS rules.

Where in the code are the pane calculations happening?

**What did you expect to happen?**
I expected the dropdown pane to open under the dropdown button.

**What happened instead?**
The dropdown pane opened in the top left corner of the screen

![screenshot 15](https://cloud.githubusercontent.com/assets/421960/19213893/a975c78c-8d44-11e6-9b27-a59b42911d67.png)

**Comment by Owlbertz** [comment]
Hi @merlinpatt, were you able to check if this occurs in the latest version as well?

**Comment by merlinpatt** [comment]
@Owlbertz unfortunately I can't upgrade Foundation just yet because doing so causes other things to break due to dependency issues.

Do you know where / what does the absolute positioning calculations?

If I have a starting point, I might be able to figure out the issue.

**Comment by Owlbertz** [comment]
Hi @merlinpatt, I guess the code you are looking for is located in the `Foundation.Box.GetOffsets` function. You can find that in the Box-Util. 

However, your code seems a bit odd because of the parent `span`. If you are able to provide your current code as a CodePen or similar I might be able to have a deeper look.

**Comment by DanielRuf** [comment]
Can we reproduce this currently?

**Comment by DincaAdrian1991** [comment]
This is still reproducible in Foundation version 6.4.3, the "dropdown-pane" is positioning top left of the screen after a second use. We use this with an AngularJS app and after the scope change, it's broken, I've tried to destroy and init on the scope change, but no effect. Tried also Foundation.reInit, but with no avail. The element has applied a negative top and left position (comming from js somewhere) like this :
`    top: -607px;
    left: -1407.5px;` 

. I've tried also using specific positioning as specified in documentation and it works fine the first time, but after scope change, it sticks to top left as described. Is there any solution for this?

PS: We are in a painful process of upgrading our html/js after an upgrade from 5.5.3 to 6.4.3.

**Comment by DanielRuf** [comment]
> This is still reproducible in Foundation version 6.4.3, the "dropdown-pane" is positioning top left of the screen after a second use. We use this with an AngularJS app and after the scope change, it's broken, I've tried to destroy and init on the scope change, but no effect. Tried also Foundation.reInit, but with no avail. The element has applied a negative top and left position (comming from js somewhere) like this :
> top: -607px; left: -1407.5px;
> 
> . I've tried also using specific positioning as specified in documentation and it works fine the first time, but after scope change, it sticks to top left as described. Is there any solution for this?
> 
> PS: We are in a painful process of upgrading our html/js after an upgrade from 5.5.3 to 6.4.3.

Please provide a codepen or something else where we can easily reproduce this.

**Comment by rbrlortie** [comment]
I'm getting a very similar issue where the dropdown gets displayed outside of the screen everytime the trigger is right next to the edges of the screen. On my actual website, that's the upper right corner.

A bit of a pain to reproduce on codepen but here are two ways:

https://codepen.io/anon/pen/moPdNg (in a position absolute footer)
https://codepen.io/anon/pen/XGdWyg (in a position fixed footer)

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/vYYyJqB

**Comment by decabeza** [comment]
I've got a similar issue and I can fix it using `data-allow-bottom-overlap="false"` as is documented in [Foundation Dropdown Plugin Options](https://get.foundation/sites/docs/dropdown.html#js-options).

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/dropdown-pane-position-bug/3405/2
