### ISSUE TITLE
Checklist, Qualifications, and References for New Mutation Observation Trigger

### ISSUE THREAD

**Issue by coreysyms** [foundation/foundation-sites#9320]
# Checklist, Qualifications, and References for New Mutation Observation Trigger #

This issue will act as the checklist for Foundation Plugins that require integration of DOM mutation observation, qualification requirements, and as a bug issue reference point.

## Background ##
Mutation observation has been added to 6.3 in triggers, meaning all plugins have access to async triggers for DOM mutation and can key self-functions off the event change. Types of changes we can observe are the additions and removals of child nodes, parent/child relationships, and changes to the style attribute. Practically speaking, there is a number of "display none show hide" bug issues of plugins not correctly displaying that the implementation of this will mitigate.

## References ##
To see a demo of how this [works](http://tangerineindustries.com/Foundation/feature-mutation-trigger/with_mut.html) and [doesn't / currently works](http://tangerineindustries.com/Foundation/feature-mutation-trigger/without_mut.html)
 
## What Qualifies As A Mutation Event ##
The following qualifies as events post document.load
- Elements added / removed from the DOM
- JS style attributes change
- JS show / hide

## Plugins to update ##
- [x] Tabs
- [x] Interchange
- [x] Equalizer
- [ ] Accordion
- [ ] Reveal
- [ ] Magellan
- [ ] Orbit
- [x] Sticky (PR #9462 )
- [x] Togglers and Responsive Nav (PR #9475 )

# Related Issues #
*Please consolidate bug issues against this issue and not #9126*

**Comment by kball** [comment]
I'm going to take a look at this for slider and see if it will fix #8391

**Comment by kball** [comment]
Found a bug in drilldown menus (surfacing in responsive menus) that I believe mutation observers will fix.  Adding them.

**Comment by kball** [comment]
@coreysyms I noticed that the mutation observer implementation doesn't currently debounce... resulting in often getting lots of triggers all together.  Can you add that?

**Comment by prkirby** [comment]
Was this implemented for Orbit Slider? I am running 6.3.1, and have an equalizer inside of an orbit slider that is collapsing to 0 for everything but the first slide. 

`$ourProcess.on('slidechange.zf.orbit', function() {
      setTimeout(function() {
        Foundation.reInit($ourProcess.find('.process-info'));
      }, 200);
    });`

The code above works after waiting for orbit to finish its mutations, I believe, but it is obviously not a fix and couldn't be used in production. Is there something I'm missing or a way I could fix this?

**Comment by colin-marshall** [comment]
@coreysyms can you please review the status of this issue when you have a moment? Thanks!
