### ISSUE TITLE
.button-group buttons do not wrap as expected with flexbox enabled

### ISSUE THREAD

**Issue by johnbacon** [foundation/foundation-sites#9325]
`.button-group` components without flexbox enabled: http://codepen.io/johnbacon/pen/ZBzXMr
`.button-group` components with flexbox enabled: http://codepen.io/johnbacon/pen/gLYGBa

This appears to be due to the following: https://github.com/zurb/foundation-sites/blob/b1d99bb184d2bb8fb1ed2951c3e5ab8fb4f3a9d9/scss/components/_button-group.scss#L39

`nowrap` is the default value of `flex-wrap`, so I do not believe this needs to be specified at all in `_button-group.scss`. However, changing that value to `wrap` produces the expected result (consistent with non-flexbox): http://codepen.io/johnbacon/pen/eBOGbr

**Comment by rafibomb** [comment]
Hmmm, adding 

```
.button-group {
  flex-wrap: wrap;
}
```

Seems to do the trick as you said. This might be as simple as adding this property and value to the `.button-group` parent. Are you able to submit a PR for it? We'd merge it in.

**Comment by canterberrie** [comment]
Hey, this is going to be fixed in a PR for fixing button group spacing. You can see the commit here: https://github.com/zurb/foundation-sites/commit/22f33f072dcbbd33d2dfc03d476a4fc00acafeb6#diff-d0689b3f481699857ae2680a820ff6aaR39

**Comment by glen-84** [comment]
@canterberrie Any news regarding this issue?

**Comment by IamManchanda** [comment]
@rafibomb what's the status of this branch 
https://github.com/zurb/foundation-sites/compare/buttongroup-flex

**Comment by colin-marshall** [comment]
Paging @rafibomb

**Comment by DanielRuf** [comment]
Still not fixed. https://codepen.io/DanielRuf/pen/rNByzMo
