### ISSUE TITLE
Reproduce docs examples in codepens

### ISSUE THREAD

**Issue by kball** [foundation/foundation-sites#9401]
It came up in #9400 that it is very helpful to be able to see examples of components in isolation.  We should reproduce each of the `in-docs` examples into a codepen and include a link next to the example.

**Comment by DanielRuf** [comment]
At the moment we already have the links to the codepen versions or is there something missing?

**Comment by DanielRuf** [comment]
We should probably use storybook for this in the future. The other is too much work.
