### ISSUE TITLE
Reveal trigger link preventDefaults on return key but not on click

### ISSUE THREAD

**Issue by getup8** [foundation/foundation-sites#9422]
https://jsfiddle.net/kekut502/

I expect the modal to take precedence over following the link, so a preventDefault() call.  Weirdly, it's called when you use the Return key to initiate the modal (see: <https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L149>) but not when you click it.

Basically, if the user allows JS, I want the modal to be called, and if not, I want the link to be followed.  I would think this should be the default behavior.

**Comment by ChaseIndustries** [comment]
I took a look at this and just adding a click event with a preventDefault() call on the $anchor element seemed to have worked.

```
if (this.$anchor.length) {
      this.$anchor.on('keydown.zf.reveal', function(e) {
        if (e.which === 13 || e.which === 32) {
          e.stopPropagation();
          e.preventDefault();
          _this.open();
        }
      })
      .on('click.zf.reveal', function(e){
        e.preventDefault();
      });
    }
```

**Comment by DanielRuf** [comment]
I can not really reproduce any issue or understand the problem.

Closing for now.
Feeld free to provide more information and we will check it then.
