### ISSUE TITLE
Issues pertaining to sass

### ISSUE THREAD

**Issue by paxperscientiam** [foundation/foundation-sites#9510]
**How can we reproduce this bug?**

**site link to `_settings.scss`**
The settings file on zurb.com should include a comment indicating the version it corresponds to -- [link](https://raw.githubusercontent.com/zurb/foundation-sites/master/scss/settings/_settings.scss).

I know it *should* correspond to the latest release, but it is not clear that this is so.

**concerning `app.scss`**
Why isn't [this](https://github.com/zurb/foundation-sites-template/blob/master/scss/app.scss) also included [here](https://github.com/zurb/foundation-sites/tree/develop/scss)?

Including would save a step for those who don't want/need to use the template repos.

**migration**
This is perhaps the biggest issue. I can use emacs' ediff to merge a newly released settings file into mine (same goes for `app.scss`); however, is there not a better way to do it? Is everyone who uses sass presumed to understand the ways of file merging? I honestly don't know, but this seems like it should be addressed.

EDIT: fixed section headings

**Comment by ncoden** [comment]
### 1. Site link to `_settings.scss`

I agree we should had a version number in the setting file, with maybe a link to the doc and changelog ?

### 2. `app.scss`

I seen some other packages that provide an index file (like our `foundation.scss`) **and** a "import now" file, which include everything automatically. We have `assets/foundation.scss`, but I don't know if `assets/` is only for the build process, or is intended to be imported directly.

### 3. Migration

I think the best we can do is to give the full list of breaking changes for the settings file. The migration would be easier, but will always have to be done manually. Some config variables are only renamed while others are removed or totally changed, so there is no automatic migration process we could provide.

**Comment by paxperscientiam** [comment]
Hi @ncoden 

Broadly speaking, lists of "public" variables, functions, and mixins from each version could be compared in such a way as to infer the deprecation status of said quantities. The resultant matrix could be used in a sass user's build process to inform them that `x`,`y`, and `z` quantities are not supported in version, say, 6.2 and above (corollary: supported in versions 5.2 to 6.1.7).

So, this is doable...whether or not it's worth the effort depends on what the demand from the community is.


PS:
Sorry about the insanely big headings!

**Comment by ncoden** [comment]
Maybe I didn't understood what you propose, but I think a well maintained changelog is the best (and simplest) thing we could provide to help to migrate.

**Comment by DanielRuf** [comment]
I am also for a well maintained changelog.

A reference to the version in the settings may be still useful.
