### ISSUE TITLE
Documentation page issue with iPad in horizontal orientation

### ISSUE THREAD

**Issue by ycrepeau** [foundation/foundation-sites#9806]
The title says it all. When using an iPad to view the documentation (http://foundation.zurb.com/sites/docs/), the right hand side bar moves to the left when I scroll down (enough to hide the first &lt;hr/>). 

![image](https://cloud.githubusercontent.com/assets/6821466/23263839/68d4c338-f9ad-11e6-82b1-229a4560ecb6.png)

**Comment by ycrepeau** [comment]
Same behaviour with: Safari, Google Chrome and Firefox. 
With Opera mini and Brave, the element does not slides down.

**Comment by DanielRuf** [comment]
Hi, does this still occur?

**Comment by DanielRuf** [comment]
Closing as outdated as this does not happen in the v6 docs.
