### ISSUE TITLE
[Close Button] Incorrect button aligment

### ISSUE THREAD

**Issue by MProG** [foundation/foundation-sites#9879]
Foundation 6.3.0
In right to left format 'X' button aligment is incorrect for chrome.
`
.alert.callout data-closable=""
  p You can so totally close this!
  button.close-button aria-label=("Dismiss alert") data-close="" type="button"
    span aria-hidden="true"  &times;
`

Actual result 
![image](https://cloud.githubusercontent.com/assets/8362820/23993490/cd5d4866-0a51-11e7-92af-9bedba6cefcd.png)

**Comment by kball** [comment]
Looks like we are missing an rtl mode for `close-button`. @MProG would you like to put together a PR for this? I suspect you should be able to handle this simply by adding a check for `$global-text-direction` around this location: https://github.com/zurb/foundation-sites/blob/develop/scss/components/_close-button.scss#L11

You can see an example of the approach here: https://github.com/zurb/foundation-sites/blob/develop/scss/components/_button.scss#L79

**Comment by DanielRuf** [comment]
Created an example.
How should we handle this and which value and padding is best regarding a11y and design?
https://codepen.io/DanielRuf/pen/EEaBmW

cc @SassNinja @Owlbertz

**Comment by DanielRuf** [comment]
Could still need some feedback here =)

**Comment by DanielRuf** [comment]
Bump =)

cc @ncoden

**Comment by axoplasm** [comment]
Seems straightforward, any movement on this? thanks.

**Comment by joeworkman** [comment]
There is already a sass variable for this. It would break backwards compatibility to change how this works now. Simply customize the `$closebutton-position` var in the settings.scss file.
