### ISSUE TITLE
[Kitchen Sink] Page does not validate

### ISSUE THREAD

**Issue by greg-raven** [foundation/foundation-sites#9900]
#### How to reproduce this bug:

1. Open page in BBEdit
2. Check syntax
3. View syntax errors

#### What should happen:

You should get a dialogue box that says "no syntax errors">

#### What happened instead:

Line 368: Value “exampleHelpText” for id attribute of element “<p>” must be unique.
Line 353: ID or Name value “exampleHelpText” was previously used here.
Line 465: Value “panel1d-heading” for id attribute of element “<a>” must be unique.
Line 457: ID or Name value “panel1d-heading” was previously used here.
Line 467: Value “panel1d” for id attribute of element “<div>” must be unique.
Line 459: ID or Name value “panel1d” was previously used here.
Line 473: Value “panel1d-heading” for id attribute of element “<a>” must be unique.
Line 457: ID or Name value “panel1d-heading” was previously used here.
Line 475: Value “panel1d” for id attribute of element “<div>” must be unique.
Line 459: ID or Name value “panel1d” was previously used here.
Line 862: Element “<img>” requires that the attribute “alt” be specified.
Line 872: Element “<img>” requires that the attribute “alt” be specified.
Line 898: Document type doesn't permit attribute “frameborder” within element “<iframe>”.
Line 898: Document type doesn't permit attribute “allowfullscreen” within element “<iframe>”.
Line 963: Value “exampleHelpText” for id attribute of element “<p>” must be unique.
Line 353: ID or Name value “exampleHelpText” was previously used here.
Line 983: Value “pokemonRed” for id attribute of element “<input>” must be unique.
Line 401: ID or Name value “pokemonRed” was previously used here.
Line 984: Value “pokemonBlue” for id attribute of element “<input>” must be unique.
Line 402: ID or Name value “pokemonBlue” was previously used here.
Line 985: Value “pokemonYellow” for id attribute of element “<input>” must be unique.
Line 403: ID or Name value “pokemonYellow” was previously used here.
Line 989: Value “checkbox1” for id attribute of element “<input>” must be unique.
Line 413: ID or Name value “checkbox1” was previously used here.
Line 990: Value “checkbox2” for id attribute of element “<input>” must be unique.
Line 414: ID or Name value “checkbox2” was previously used here.
Line 991: Value “checkbox3” for id attribute of element “<input>” must be unique.
Line 415: ID or Name value “checkbox3” was previously used here.
Line 1057: Element “<img>” requires that the attribute “alt” be specified.
Line 1057: Element “<img>” requires that the attribute “src” be specified.
Line 1104: Element “<img>” requires that the attribute “alt” be specified.
Line 1198: Document type does not permit element “<button>” in content of element “<ul>”.
Line 1199: Document type does not permit element “<button>” in content of element “<ul>”.
Line 1464: Element “<img>” requires that the attribute “alt” be specified.
Line 1544: Document type doesn't permit attribute “width” within element “<th>”.
Line 1546: Document type doesn't permit attribute “width” within element “<th>”.
Line 1547: Document type doesn't permit attribute “width” within element “<th>”.
Line 1623: Element “<img>” requires that the attribute “alt” be specified.
Line 1631: Element “<img>” requires that the attribute “alt” be specified.
Line 1639: Element “<img>” requires that the attribute “alt” be specified.
Line 1940: Value of attribute “href” for element “<a>” is invalid; URL path needs encoding (“http://zurb.com/university/foundation-intro?utm_source=Foundation%20Docs&amp;utm_medium=Docs&amp;utm_content=Footer&amp;utm_campaign=Footer%20Upsell”).
Line 1945: Value of attribute “href” for element “<a>” is invalid; URL path needs encoding (“http://zurb.com/university/foundation-intro?utm_source=Foundation%20Docs&amp;utm_medium=Docs&amp;utm_content=Footer&amp;utm_campaign=Footer%20Upsell”).
Line 1945: In HTML 5 or XHTML, it's recommended to include a space before the trailing “/>” in empty XML elements.
Line 1945: Element “<img>” requires that the attribute “alt” be specified.

**Comment by DanielRuf** [comment]
These seem to be a11y related.

@Owlbertz

**Comment by evagm** [comment]
Is there a way to reproduce this without BBEdit?

**Comment by decabeza** [comment]
Hi @greg-raven, @DanielRuf can I work on this issue? 😌

**Comment by DanielRuf** [comment]
Hi @decabeza,

awesome, yes you can work on this issue =)
Feel free to ask if anything is unclear or you need some assistance.

**Comment by decabeza** [comment]
Hi @greg-raven, @DanielRuf I just created a new PR https://github.com/foundation/foundation-sites/pull/11862. 🙏😌
